### ISSUE TITLE
2.4.1 64bit  两个SS账号同时连接程序崩溃

### ISSUE THREAD

**Issue by dft2000** [shadowsocks/shadowsocks-qt5#161]
添加两个SS账号，同时连接程序崩溃，连接一个账号正常

**Comment by librehat** [comment]
同时连接的意思是先连接一个，然后再连接第二个崩溃吗？

此外，两个账号的本地端口是不是用的一样的？

**Comment by dft2000** [comment]
先连接一个，在连接一个；
两个本地端口是不一样的 ；
32位的版本也有这个问题存在！

**Comment by librehat** [comment]
Linux下没有这个问题，我等会儿到Windows下测试一下

**Comment by librehat** [comment]
我在Windows 8.1 x64下测试了没有问题。

**Comment by dft2000** [comment]
我也说一下情况，其实如果只有一个账号还是相当稳定的，但是多个账号的时候 就变的相当不稳定，
问题应该都是和套接字有关，如果多个账号但只链接一个其它的不连接也比较稳定，但是一旦多个账号需要同时运行时，就非常不稳定，我没看你的代码，但我估计和套接字的处理有关系，比如说端口已经被占用了，程序直接就崩溃了，
还有一些情况端口虽然没有被占用，但是一旦有程序连接本地端口时也会崩溃，这种情况我就不知道是怎么回事了。

**Comment by librehat** [comment]
可能跟`libQtShadowsocks`那边有关系，最近比较忙所以`libQtShadowsocks`很久没有去动了。过两个月再来填坑。

**Comment by librehat** [comment]
请测试一下最新的2.5.0

**Comment by dft2000** [comment]
正在试用 有问你我会反馈 谢谢

2015-09-21 22:06 GMT+08:00 Symeon Huang <notifications@github.com>:

**Comment by librehat** [comment]
Consider fixed
