### ISSUE TITLE
为什么此程序的窗口不能总是置顶显示？

### ISSUE THREAD

**Issue by lpssph** [shadowsocks/shadowsocks-qt5#162]
windows8.1下，当此程序最小化到右下角后，再次单击它的图标，它的窗口总是在别的程序后面（比如，浏览器），这样我不得不再次点击它在电脑桌面左边下面的任务栏图标，它的窗口才到最上面。 希望它能像大多数别的程序那样，单击右下角程序图标，其程序窗口就会展现在最上面。

**Comment by librehat** [comment]
Fixed in 690bf987deaf0b19487354306caf162954b46501

**Comment by lpssph** [comment]
2.4.2  版本并没有完全改善这个问题， 至少在win10 x64 中.

**Comment by librehat** [comment]
这下应该解决了，我刚刚在Win 10下测试了没问题。

**Comment by lpssph** [comment]
2.5.0 版本 win10 x64下，问题有所改善，但还是没有完全解决。 比如，点击它最小化按钮后，再点击它右下角托盘图标时，它的界面就难以回到最上面。点击关闭按钮后，再点系统托盘图标，倒是可以。而诸如迅雷等其他软件，上面两种情况下，点击系统托盘的图标，它们的界面都能回到最上面.
