### ISSUE TITLE
2.5.1 版本无法识别二维码

### ISSUE THREAD

**Issue by gmg137** [shadowsocks/shadowsocks-qt5#202]
2.5.1版本无法识别任何二维码，之前虽然不能识别屏幕上的二维码，但可以识别手动读取的二维码文件，现在则完全无法识别。
系统：openSUSE TumbleWeed
桌面：GNOME 3.16

**Comment by kodexor** [comment]
[windows10 x64 10240]
扫描屏幕上的二维码功能无效。
使用捕获器或自二维码图像读取功能正常。

**Comment by librehat** [comment]
Windows 7 测试 2.5.1 一切正常。

@gmg137 我猜测是zbar更新导致的问题，因为2.5.x根本就没有改读取二维码文件这一部分。
