### ISSUE TITLE
2.5.1 经常性假死，然后CPU占用飙高

### ISSUE THREAD

**Issue by h404bi** [shadowsocks/shadowsocks-qt5#206]
假死后点托盘图标毫无反应，并且代理也断了。
任务管理器看到CPU占用15%有多，平时也只是1%左右。
![default](https://cloud.githubusercontent.com/assets/5764917/10562045/01d462e6-757a-11e5-861b-f3e91fe4f77c.PNG)

另外也伴有 #205 的情况，切换服务器时崩溃退出。

*平台: Win10

**Comment by librehat** [comment]
请问使用的代理模式是SOCKS5还是HTTP？

**Comment by h404bi** [comment]
SOCKS5，服务端是 libev 版本。

**Comment by librehat** [comment]
就单独连接一个，然后就会假死？我无法重现这个问题。

**Comment by h404bi** [comment]
就是普通打开连接，一段时间后无故假死，并不是马上的。用着用着代理就突然断了，托盘无反应，只能结束进程。我知道这个可能很难重现，但我又不知道怎么拿到客户端假死后的 log，所以给不了更多 info。。我有用 Proxifier，但之前的版本并没出现这现象，所以应该不会是它造成的吧。

**Comment by librehat** [comment]
请测试一下2.6.0

**Comment by h404bi** [comment]
用了一天问题暂时没出现了。那我先关 issue，如果有问题再开。
