### ISSUE TITLE
2.5.1使用中遇到问题,ubuntu提示"无法启动XX"

### ISSUE THREAD

**Issue by getcha22** [shadowsocks/shadowsocks-qt5#207]
您好,很抱歉打扰.
我自行购买了vps,上月提前用完流量,shadowsocks被闲置了几天.
等待结算日vps流量清零,我想重新使用shadowsocks时,发现点击连接按钮时,提示`无法启动XX`.以下为日志的内容:
>Initialising ciphers...
>AES-256/CFB (aes-256-cfb) initialised.
>Running in local mode.
>TCP server listen failed.

在vps无法使用的时间内,我使用lantern进行翻墙,不知道是否因为这个软件的安装导致.
同时曾经修改过`etc/ssh/ssh_config`,`etc/ssh/sshd_config`中的port端口,目前为`Port 1080`,不知道是不是因为这个原因导致,如果是的话,这个值应该在哪里查找?

                                                                                          万分感谢!

**Comment by librehat** [comment]
你端口已经被占用了，换个本地端口。

**Comment by getcha22** [comment]
收到你的消息后,我尝试查看了1080端口,但是提示如下
>getcha22@getcha22-CW65S:~$ lsof -i:1080
>COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
>ss-qt5  2337 getcha22   16u  IPv4 873307      0t0  UDP localhost:socks

**Comment by librehat** [comment]
你的SSH服务器不是端口设在1080了吗？
可以用`netstat -nlp | grep 1080`看看谁在监听
