### ISSUE TITLE
@jemyzhang shadowsocks-qt5 v2.5.1何时可以有啊，大神

### ISSUE THREAD

**Issue by lsnmx** [shadowsocks/shadowsocks-qt5#211]
@jemyzhang shadowsocks-qt5 v2.5.1何时可以有啊，大神

**Comment by lsnmx** [comment]
@librehat

**Comment by XhstormR** [comment]
早就有了。
`https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v2.5.1`
