### ISSUE TITLE
可以连接，但是无法使用

### ISSUE THREAD

**Issue by bugparty** [shadowsocks/shadowsocks-qt5#215]
确认配置没有问题
TABLE (TABLE) initialised.
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 1080
Connecting 123.sankuai.com:80 from 127.0.0.1:57445
Connecting 123.sankuai.com:80 from 127.0.0.1:57446
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting 123.sankuai.com:80 from 127.0.0.1:57449
Remote socket debug: The remote host closed the connection
Connecting 123.sankuai.com:80 from 127.0.0.1:57451
Remote socket debug: The remote host closed the connection
Connecting 123.sankuai.com:80 from 127.0.0.1:57459
Connecting 123.sankuai.com:80 from 127.0.0.1:57460
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting 123.sankuai.com:80 from 127.0.0.1:57463
Remote socket debug: The remote host closed the connection
Stopped.
Initialising ciphers...
TABLE (TABLE) initialised.
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 1080
Connecting github.com:443 from 127.0.0.1:57526
Connecting api.github.com:443 from 127.0.0.1:57529
Connecting api.github.com:443 from 127.0.0.1:57528
Connecting assets-cdn.github.com:443 from 127.0.0.1:57530
Connecting assets-cdn.github.com:443 from 127.0.0.1:57531
Connecting avatars0.githubusercontent.com:443 from 127.0.0.1:57533
Connecting assets-cdn.github.com:443 from 127.0.0.1:57532
Connecting avatars3.githubusercontent.com:443 from 127.0.0.1:57535
Connecting avatars0.githubusercontent.com:443 from 127.0.0.1:57534
Connecting avatars3.githubusercontent.com:443 from 127.0.0.1:57536
Connecting collector.githubapp.com:443 from 127.0.0.1:57537
Connecting collector.githubapp.com:443 from 127.0.0.1:57538
Connecting github.com:443 from 127.0.0.1:57542
Connecting github.com:443 from 127.0.0.1:57539
Connecting github.com:443 from 127.0.0.1:57540
Connecting github.com:443 from 127.0.0.1:57541
Connecting www.google-analytics.com:443 from 127.0.0.1:57543
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting github.com:443 from 127.0.0.1:57560
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting github.com:443 from 127.0.0.1:57562
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting github.com:443 from 127.0.0.1:57564
Connecting clients2.google.com:443 from 127.0.0.1:57567
Remote socket debug: The remote host closed the connection
Connecting clients2.google.com:443 from 127.0.0.1:57569
Remote socket debug: The remote host closed the connection
Connecting clients2.google.com:443 from 127.0.0.1:57571
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting github.com:443 from 127.0.0.1:57573
Remote socket debug: The remote host closed the connection
Connecting github.com:443 from 127.0.0.1:57575
Remote socket debug: The remote host closed the connection
Connecting github.com:443 from 127.0.0.1:57577
Remote socket debug: The remote host closed the connection
Connecting github.com:443 from 127.0.0.1:57579
Remote socket debug: The remote host closed the connection

**Comment by librehat** [comment]
请检查防火墙的设置，你这出去的连接全部被中断了。

**Comment by junweigu** [comment]
@librehat 给点思路怎么检查啊？
