### ISSUE TITLE
能不能加上pac功能？我用遨游浏览器只能全局代理，没pac功能比较郁闷！

### ISSUE THREAD

**Issue by lukemin** [shadowsocks/shadowsocks-qt5#217]
shadowsocks-windows 有这个功能，但是界面不喜欢，还是你的直观！

**Comment by librehat** [comment]
https://github.com/shadowsocks/libQtShadowsocks/issues/48

**Comment by librehat** [comment]
Pull requests might be welcomed regarding PAC.
