### ISSUE TITLE
Ubuntu 14.04 中无法添加连接配置

### ISSUE THREAD

**Issue by felicitywang** [shadowsocks/shadowsocks-qt5#222]
按照安装指南添加源安装的，打开之后任务栏中项目全是灰色，一个都点不了。

**Comment by librehat** [comment]
那是因为Ubuntu可能不会显示菜单栏，你没链接当然点不了。
https://github.com/shadowsocks/shadowsocks-qt5/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%92%8C%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95#%E4%B8%8D%E6%98%BE%E7%A4%BA%E8%8F%9C%E5%8D%95%E6%A0%8F
