### ISSUE TITLE
Shortcut support and tray menu as enhancement?

### ISSUE THREAD

**Issue by legendtang** [shadowsocks/shadowsocks-qt5#223]
This is about user experience.

Like [shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows), I consider it be added support for tray menu so that desktop users (Mac, Windows, GNOME / KDE / Unity / *fce, etc) would make easy access to connect / disconnect from a single server and switch from one server to another.

Similarly, in the main user interface, we have to disconnect from a live server and connect to another. A shortcut would help to make this faster and this procedure could also be simplified.

**Comment by librehat** [comment]
Some users have dozens of connections. It'd be a disaster if we add them into tray menu.

Also, to keep consistency among all desktop environment, I have to remove the connect/disconnect actions (which would be ugly to implement for GTK+).

You're welcomed to add connect/disconnect to tray menu, but I won't accept changes that add connection list into tray menu.
