### ISSUE TITLE
建议增加用量修改功能

### ISSUE THREAD

**Issue by StrollStars** [shadowsocks/shadowsocks-qt5#224]
目前程序可以看到本期用量和累计用量，建议可以对其进行修改。

**Comment by librehat** [comment]
为什么要修改？

**Comment by StrollStars** [comment]
因为在使用该软件前的流量没有统计，会造成累计数的差异。

**Comment by librehat** [comment]
@StrollStars 那也只有本期用量有点差异吧？这个功能做起来不难，但是类似的网络连接管理器都不提供修改流量数据功能的。设计上就不应该允许这样操作。

**Comment by StrollStars** [comment]
我没说清，是用qt版客户端之前客户端所产生的流量，所以差的是累计数。
这个不是紧要的功能，不加也没关系。
