### ISSUE TITLE
Feedback: In one condition it crashed 100%

### ISSUE THREAD

**Issue by shixy91** [shadowsocks/shadowsocks-qt5#225]
Both in 2.5.1 and 2.6.0
My system is win7 x64 with sp1, my browser is chrome 46.0.2490.86 m with SwitchyOmega plugin, and I use the autoproxy-gfwlist, my server version is ss-libev version on centos 6.7 x64(for all my vpses).

This could be reproduced like this,
Firstly, open ss-qt5 client and chrome, view some pages(such as google, youtube or something else), do not close chrome in the following steps,
Secondly, open ss-qt5 UI and do something to the connection. For example, create a new connection, then disconnect the connected connection and connect the new one.
Thirdly, browse something in chrome(like google & so on).
Then ss-qt5 will crashed.
It seems that some TCP connection were cached caused the problem? I just guess that, I don't know if anyone else could reproduce this.
Thank you so much! :)

**Comment by lucisgh** [comment]
我的也一样，连接改动必崩溃

**Comment by librehat** [comment]
Can't reproduce on my laptop (Win 10 x64)

**Comment by shixy91** [comment]
@librehat Is there anyway that I can see the log when it crashed? If there maybe this will help.

**Comment by librehat** [comment]
Not on Windows.

**Comment by int347** [comment]
怎么才能提供一些详细信息呢？

**Comment by librehat** [comment]
Please try the latest `2.6.1` and report if the crash persists

**Comment by shixy91** [comment]
@librehat This worked, it didn't crash. It shows a little lagging after changing the connection, but it's fine. Thank you!
