### ISSUE TITLE
QSharedMemory::handle:: UNIX key file doesn't exist

### ISSUE THREAD

**Issue by uutoto** [shadowsocks/shadowsocks-qt5#227]
点击图标启动不了, 用命令行启动后, 提示"QSharedMemory::handle:: UNIX key file doesn't exist"

**Comment by librehat** [comment]
什么平台？Qt什么版本？是自己编译的吗？

**Comment by uutoto** [comment]
@librehat 按照教程通过添加源, 然后apt-get安装的, ubuntu 15.10,
今天更新了下系统, 重启后居然又可用了.
