### ISSUE TITLE
Ubuntu14.04 可以连接shadowsocks远程服务器，但是无法使用

### ISSUE THREAD

**Issue by kevinkelin** [shadowsocks/shadowsocks-qt5#229]
可以远程连接，也可检查延迟，但是就是没有流量
shadowsocks 2.8.2
日志显示

Initialising ciphers...
AES-256/CFB (AES-256-CFB) initialised.
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 3024
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
Local socket debug: The remote host closed the connection
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.

我的chrome代理是设置的socks5呀，哪里有问题呢？
切换到windows下没有问题

**Comment by librehat** [comment]
错误信息已经提示你连接不是SOCKS5类型了，你仔细检查你Chrome插件的设置。要不你就换成HTTP(S)代理模式。

**Comment by kevinkelin** [comment]
改用http(s)连接可以了

**Comment by zzt93** [comment]
出现同样的错误，切换成HTTP（S）之后, 错误变成了：
```
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 
```
请问是什么原因呢？
