### ISSUE TITLE
ubuntu14.04二维码添加连接，不能正常连接

### ISSUE THREAD

**Issue by zheteng123** [shadowsocks/shadowsocks-qt5#230]
我的环境是ubuntu14.04，使用Scan QR Code On Screen的方式添加连接，连接正常添加，但始终不能连接上，log如下：

Initialising ciphers...

AES-256/CFB (AES-256-CFB) initialised.

Listen UDP socket state changed to QAbstractSocket::BoundState 

Running in local mode.

TCP server listen failed.

麻烦帮忙解决下，多谢！

**Comment by librehat** [comment]
listen failed
估计你本地端口被占用了
