### ISSUE TITLE
使用捕获器扫描二维码崩溃

### ISSUE THREAD

**Issue by zzhangshuaii** [shadowsocks/shadowsocks-qt5#231]
系统：ubuntu 14.04，中文环境
可以捕获二维码并且读取信息，可是之后扫描二维码弹出的配置窗口点X关不掉，随后GUI直接崩溃。
谢谢作者！
For more info.Email me by zzhangshuaii@qq.com.

**Comment by librehat** [comment]
It should be fixed now. https://github.com/shadowsocks/shadowsocks-qt5/commit/ca20f08de8cfbb9def326da5580deb05ec0e7458

**Comment by zzhangshuaii** [comment]
Thx!
