### ISSUE TITLE
ubuntu 15.10 无法链接到服务器

### ISSUE THREAD

**Issue by CorlyDream** [shadowsocks/shadowsocks-qt5#232]
Running in local mode.
TCP server listen at port 1080
One-time message authentication is enabled.
Connecting www.google.com:443 from 127.0.0.1:45296
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:45300
Remote socket debug: The remote host closed the connection

我在windows和mac 上面都可以正常使用，然后在ubuntu上面就连不上代理服务器，这是为什么？查了很多资料都没查到，求大神解救。

**Comment by aimspike** [comment]
我的也连接不上，用的是 shadowsocks-qt5 linux 下面的最新版本，刚装的 ubuntu 15.10
连接正常，但是无法科学上网（google 连不上。。。）

**Comment by shoring** [comment]
你们解决了吗？我的也是，windows上都可以

**Comment by blackredscarf** [comment]
ubuntu 16.0.4 同问

**Comment by CorlyDream** [comment]
最后我把服务器上的shadowsocks-libev 升级到最新版，然后问题解决了
