### ISSUE TITLE
releases中能否提供deb包

### ISSUE THREAD

**Issue by VDerGoW** [shadowsocks/shadowsocks-qt5#233]
releases中能否提供deb包？现在只会从ppa安装

**Comment by librehat** [comment]
No.

**Comment by jingxa** [comment]
干你。。哥们

**Comment by VDerGoW** [comment]
怎么了？

**Comment by jingxa** [comment]
大哥，你好，能不能请问你一个问题，我使用的搬瓦工的vps，我在上面安装了一个软件，但是在国内网下这个软件不能运行，所以我想把整个vps系统克隆下来，但是我一直没找到方法，请问哈你知道如何弄吗？谢谢

**Comment by VDerGoW** [comment]
我也不懂额。。。。你看看这个有没有用，https://www.zhihu.com/question/20923114

或者查查怎么把整个Linux系统保存成镜像
