### ISSUE TITLE
在Ubuntu1404上让chrome浏览器使用shadowsocks还需要浏览器插件设置

### ISSUE THREAD

**Issue by windonground** [shadowsocks/shadowsocks-qt5#235]
# 我遇到的问题
我在Ubuntu1404上按照wiki当中的教程安装shadowsocks-qt5后,ss-qt5启动正常,但是无法在chrome浏览器中访问被墙网站.ss-qt5当中的流量使用一直为0,而日志显示初始化正常,却没有后续日志.
# 环境
Ubuntu1404
Google Chrome 46.0.2490.86 
# 排查过程
## 最后结果
发现竟然还需要在浏览器中安装一个代理插件,例如SwitchyOmega,并在其中配置成本地代理.
因为之前在Mac和Windows上使用shadowsocks都能直接代理浏览器的访问,都不用安装一个代理插件,所以感觉非常奇怪,费了很多时间排查这个问题.希望作者能在wiki中给后来者提到这个问题.

**Comment by librehat** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E7%9A%84%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE
