### ISSUE TITLE
Project ERROR: botan-1.10 development package not found，谢谢了！

### ISSUE THREAD

**Issue by wanghai1998** [shadowsocks/shadowsocks-qt5#236]
你好！首先感谢您能开发出这个作品，我的是Debian 8.2，在编译中，我也遇到了“Project ERROR: botan-1.10 development package not found”的问题。

下面是相关信息输出：
—————–
root@localhost:/home/abc/libQtShadowsocks-1.8.0# make
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/bin/qmake /home/abc/libQtShadowsocks-1.8.0/lib/libQtShadowsocks.pro -o Makefile.libQtShadowsocks ) && make -f Makefile.libQtShadowsocks
Project ERROR: botan-1.10 development package not found
Makefile:39: recipe for target ‘sub-lib-libQtShadowsocks-pro-make_first-ordered’ failed
make: *** [sub-lib-libQtShadowsocks-pro-make_first-ordered] Error 3
—————–
root@localhost:/# aptitude search botan
i botan1.10-dbg – multiplatform crypto library (debug)
i A libbotan-1.10-0 – multiplatform crypto library
i libbotan1.10-dev – multiplatform crypto library (development)
root@localhost:/#
—————–
root@localhost:/# uname -a
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
root@localhost:/#
—————–

谢谢了 ！！！

**Comment by librehat** [comment]
libbotan1.10-dev 这个安装了吗？ 我不了解debian
