### ISSUE TITLE
在关闭windows防火墙的情况下仍然出现Local socket debug: The remote host closed the connection

### ISSUE THREAD

**Issue by luffytam1988** [shadowsocks/shadowsocks-qt5#237]
手机上一直都可以用ShadowSocks翻墙，但最近电脑上任何一个ShadowSocks客户端都会频繁出现以下故障
以下均为windows7系统

System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)

ShadowSocks-Qt5的调试信息显示
Local socket debug: The remote host closed the connection

都说是防火墙的问题，彻底关闭win7自带防火墙并重启，错误信息依旧

以前改本地端口就能翻墙，但现在几天都不行了，我查了现在用的1080端口并没有占用的说

**Comment by librehat** [comment]
是不是安装了迅雷？

**Comment by luffytam** [comment]
卸载了，但在系统分区残留Thunder BHO Platform

**Comment by librehat** [comment]
Double check the profile (i.e. password, encryption method).

**Comment by luffytam** [comment]
我用二维码扫描miaoss的服务器，但还是被强迫关闭连接。之前卸载了bitcomet也重置过网络设置还是没有效果

**Comment by librehat** [comment]
可能扫码的结果错了？我不太确定，能否尝试手动输入配置？

**Comment by luffytam** [comment]
我确定扫码信息正确，从带有网络连接的安全模式进入系统可以正常翻墙

**Comment by librehat** [comment]
嗯，说明是其他软件干扰了。

**Comment by zhouAndy** [comment]
编译很是个问题。环境:openSUSE leap 42.1
