### ISSUE TITLE
[Ubuntu] Global menu disappeared after restoring from system tray

### ISSUE THREAD

**Issue by librehat** [shadowsocks/shadowsocks-qt5#241]

**Comment by madjxatw** [comment]
Doesn't it have system tray option for mate desktop? I installed it through Ubuntu PPA.

**Comment by librehat** [comment]
@madjxatw Please open another issue.

**Comment by librehat** [comment]
It seems to be "fixed" in `2.6.1`. An additional menubar would appear in addition to Ubuntu's Global Menu. Thus, the Global Menu disappears but it won't affect the functionality.
