### ISSUE TITLE
system tray doesn't display in mate desktop

### ISSUE THREAD

**Issue by madjxatw** [shadowsocks/shadowsocks-qt5#243]
The system tray icon only appears the first time that the client is launched. Close the client and relaunch, then the system tray no longer displays. Further, there is no option to turn on/off system tray in 'General settings'.

**Comment by librehat** [comment]
It's not possible to turn off system tray icon (why would you do that?)

It looks like a compatibility issue with Qt systemtray and the desktop environment. Please paste the result of `echo $XDG_CURRENT_DESKTOP` from terminal.

**Comment by madjxatw** [comment]
I am not meant to turn it off,  just think if I need to enable system tray in settings. Per your response, the system tray icon is supposed to be there.
>$XDG_CURRENT_DESKTOP=MATE
