### ISSUE TITLE
Status doesn't auto refresh in mate desktop 

### ISSUE THREAD

**Issue by madjxatw** [shadowsocks/shadowsocks-qt5#244]
The information below **status** tag doesn't refresh itself when ss is switching between connected and disconnected unless you click the title bar of the client window.
BTW, after disconnecting the client to the server, I find **udp** is still listening at 127.0.0.1:1080 even I terminate the client, but **tcp** quits as expected.
Not a big deal, but hope them be fixed at a proper time. Thanks!

客户端窗口**status**标签下的状态信息不会根据实际的连接情况而自动刷新，除非点击一下窗口的标题栏。另外，再断开连接后，运行netstat命令会发现1080端口仍然有udp监听，即使我退出客户端。不过都是小问题，有空解决下就OK。

**Comment by librehat** [comment]
Which version of Ubuntu your PC is running on?

**Comment by madjxatw** [comment]
14.04 LTS.
