### ISSUE TITLE
gnome环境下不能使用fcitx输入中文

### ISSUE THREAD

**Issue by wolfbloodzzx** [shadowsocks/shadowsocks-qt5#245]
系统：ubuntu-15.10
桌面环境：gnome
问题：
安装了fcitx和搜狗输入法，其它应用使用正常，发现在SSqt界面中不能输入中文，无法唤醒输入法

**Comment by librehat** [comment]
安装 fcitx-qt5

**Comment by wolfbloodzzx** [comment]
谢谢，安装了libfcitx-qt5，问题已解决
