### ISSUE TITLE
Crashes on Windows 2008 R2 SP1

### ISSUE THREAD

**Issue by sergio13848** [shadowsocks/shadowsocks-qt5#246]
使用的版本信息：![qq 20160109173629](https://cloud.githubusercontent.com/assets/5392727/12215443/98b77464-b6f7-11e5-8c33-00ef6ab6a4f1.png) win64
使用的平台为：Windows Server 2008 R2 sp1 ，64位，一天的使用下来已经奔溃几次了。日志当中也扑捉不到详细信息，希望可以追踪解决下奔溃问题，非常感谢。

**Comment by librehat** [comment]
Need more details. How to reproduce the crashes?

**Comment by sergio13848** [comment]
找到了个系统备份的dmp文件，打开看了下看不懂，信息如下：
![qq 20160110090317](https://cloud.githubusercontent.com/assets/5392727/12219297/10e40e08-b779-11e5-9ae7-ff3b159f154e.png)

**Comment by librehat** [comment]
dump信息基本等于没有……能说一下你怎么操作然后崩溃的?

**Comment by librehat** [comment]
Please try the latest `2.6.1` and report if the crash persists

**Comment by sergio13848** [comment]
好的，会再次使用及反馈问题

**Comment by sergio13848** [comment]
2.6.1奔溃比之前一个版本还频繁了。望修改

**Comment by librehat** [comment]
我没有Windows 2008，其他平台也无法重现。

你是打开什么操作也没有，然后它自己就崩溃了？

**Comment by sergio13848** [comment]
恩 自己奔溃。用回了2.6又一直很稳定了。

**Comment by librehat** [comment]
你不是说2.6也崩溃的吗？怎么又变成稳定了?
