### ISSUE TITLE
ubuntu下提示信息的bug

### ISSUE THREAD

**Issue by lmzlmz** [shadowsocks/shadowsocks-qt5#248]
在ubuntu下的客户端，手动配置正确的服务器ip和错误的密码后，提示已连接，并且测试延迟的时候延迟仍然在改变（按理说测试延迟的时候应该失败的）

**Comment by librehat** [comment]
因为延迟测试就是延迟测试，不验证服务器配置信息的。同理已连接实质是本地服务器已监听。

**Comment by lmzlmz** [comment]
那如果密码写错了的话是发现不了的吗？

**Comment by librehat** [comment]
View log, it should have some error messages in log.

**Comment by librehat** [comment]
This validation may be added in the future. https://github.com/shadowsocks/libQtShadowsocks/issues/64
