### ISSUE TITLE
something's wrong with my ss-qt5 client on ubuntu 14.04, it didn't work

### ISSUE THREAD

**Issue by shixy91** [shadowsocks/shadowsocks-qt5#249]
All the connection functions seem OK, but it didn't work. All delay test in UI showed error. And the delay test showed failed.
I had reinstalled my ubuntu, it still didn't work either.
I install ss-qt5 through ppa source.
I tried debugging logs, all lines showed remote socket error. How can I see the logs when ss-qt5 client start? I don't know if there's crashing between it and other apps.
Thank you so much!

**Comment by librehat** [comment]
Check your password and encryption method correctness.

**Comment by shixy91** [comment]
@librehat passwords and encryption method were right, cause these configuration was fine in Windows. Is it mean there's something wrong during the startup when I click the delay test button it just showed delay test failed?

**Comment by librehat** [comment]
You may also want to check your firewall settings. And check your server logs.
