### ISSUE TITLE
ubuntu15.04，用的是Qt5，显示已连接但还是无法科学上网，不知道什么原因？

### ISSUE THREAD

**Issue by feiger1992** [shadowsocks/shadowsocks-qt5#251]
看之前的问题说是看log，请问这个在哪里？抱歉自己搜索了也没有找到，在var/log里面也没有找到啊，是叫shadowsock.log吗？谢谢

**Comment by feiger1992** [comment]
在客户端那里看到的日志不算吧？这里显示的是
Initialising ciphers...
ChaCha (CHACHA20) initialised.
Running in local mode.
TCP server listen at port 1080

**Comment by librehat** [comment]
就是看这个，打开debug选项。你浏览器要做相应的设置。
