### ISSUE TITLE
libqtshadowsocks-dev is not in the repository

### ISSUE THREAD

**Issue by jych1224** [shadowsocks/shadowsocks-qt5#252]
easylife@easylife:~$ sudo apt-get install libqtshadowsocks-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 libqtshadowsocks-dev

**Comment by librehat** [comment]
请添加好ppa

**Comment by jych1224** [comment]
@librehat 我用的是deepin linux， 是基于debian的， 不支持PPA，怎么破

**Comment by librehat** [comment]
Build QtShadowsocks yourself

**Comment by HashCon** [comment]
同问
