### ISSUE TITLE
重装系统之后用不了了!!

### ISSUE THREAD

**Issue by hehehym** [shadowsocks/shadowsocks-qt5#253]
SS-QT5,服务端我也是用你的libshadowsocks,电脑出问题之后重装,然后就用不了了,google浏览器(已经装switchyomega自动切换),一切和以前的设置都一样,因为有同步账户~但是就是上不了,关键是用clowndy的版就能上(那个switchyomega要设成系统代理)..看log就是是说TCP链接超时或者说请确定你的连接方式是sock方式.~~

**Comment by librehat** [comment]
仔细检查设定
