### ISSUE TITLE
Problems with browsers on Ubuntu 15.10

### ISSUE THREAD

**Issue by KevinWangTHU** [shadowsocks/shadowsocks-qt5#254]
Not familiar with Ubuntu so this could a simple problem.

The connection was added successfully and it could connect to the SS server. The latency seems to be no problem (~200ms).
However I cannot use this connection as the proxy for Firefox/Chromium. I was pretty sure that I followed the steps (SOCKS5, 127.0.0.1, port etc) but I cannot connect to any website.

The log is like
Connecting tiles.services.mozilla.com:443 from 127.0.0.1:55136
Connecting tiles.services.mozilla.com:443 from 127.0.0.1:55140
Connecting developer.nvidia.com:443 from 127.0.0.1:55144
after trying to connect to nvidia.com

Thanks for your help!

**Comment by librehat** [comment]
It looks okay. Are you sure the server side' net work is okay?

**Comment by KevinWangTHU** [comment]
It seems to be related to the firewall. However my Ubuntu is crashed right now.
I guess I can figure it out. I will keep you updated.
And many thanks again.

**Comment by librehat** [comment]
Closed for now
