### ISSUE TITLE
ubuntu 安装ss-qt5第一次没反应，第二次安装打开就注销系统

### ISSUE THREAD

**Issue by KingzCheung** [shadowsocks/shadowsocks-qt5#255]
第一次安装的时候怎么点都没有反应，然后我打开卸载重装，结果再装就直接黑屏注销了系统

**Comment by shixy91** [comment]
what's you ubuntu version, my 14.04 is all fine, add the ppa repository and then yum install it.

**Comment by KingzCheung** [comment]
Mine is 15.10. I had add the ppa and then apt-get it.But I can not use it

**Comment by librehat** [comment]
Can't reproduce it. BTW I've tested Ubuntu 15.10.

Please check if you did anything wrong.
