### ISSUE TITLE
能否启动时默认最小化

### ISSUE THREAD

**Issue by xsh6528** [shadowsocks/shadowsocks-qt5#257]
windows里习惯开机自启动，并且默认是最小化的。

我在ubuntu下也想设置开机自启动，可是现在启动时一定会显示配置界面，每一次都要点一下"关闭"。

**Comment by xsh6528** [comment]
呃，设置里就有，我瞎了

**Comment by OwenChia** [comment]
@xsh6528 你好，请问你那勾选那个选项之后起作用了吗？我在 kde5 上勾选了也还是会弹出窗口来。
