### ISSUE TITLE
link SVGCleanerId_0 hasn't been detected!

### ISSUE THREAD

**Issue by shenxs** [shadowsocks/shadowsocks-qt5#259]
请问出现这样的问题是为什么?
我一直用的好好的,或许是其他的软件冲突造成的还是其他原因(昨天装了xware-desktop,不知道是不是它造成的)
卸载重装也没什么用,
从终端启动就显示了3行link SVGCleanerId_0 hasn't been detected!
并且提醒我无法启动**

**Comment by shenxs** [comment]
sorry,我先去卸载迅雷看看

**Comment by shenxs** [comment]
ok 自己解决了,其实不用卸载迅雷,只要将其后端服务关闭就可以,这时候ss-qt5就可以正常连接
同时迅雷后端服务也可以再次开启

**Comment by gundamlh** [comment]
> 只要将其后端服务关闭就可以
请问ss-qt5是在什么操作系统功能上运行的?

**Comment by shenxs** [comment]
用的Ubuntu的操作系统，具体的有点忘记了:smile:
