### ISSUE TITLE
Ubuntu15.10提示无法定位软件包

### ISSUE THREAD

**Issue by huyinjie** [shadowsocks/shadowsocks-qt5#260]
运行 sudo apt-get install shadowsocks-qt5
提示 无法定位软件包 shadowsocks-qt5

**Comment by librehat** [comment]
先添加ppa

**Comment by FrankBian** [comment]
sudo add-apt-repository ppa:hzwhuang/ss-qt5    
    sudo apt-get update    
    sudo apt-get install shadowsocks-qt5

按照这个顺序添加下来的，之前已经安装了相关的依赖包。

到```install shadowsocks-qt5```的时候 提示 ：

    Unable to locate package shadowsocks-qt5

系统版本：Ubantu 14.04.3  LTS

**Comment by ADSL0067** [comment]
我也遇到一样的问题

**Comment by wangzhenya** [comment]
> 我也遇到一样的问题

因为ppa:hzwhuang/ss-qt5 并没有18.04版本的源，因此会出现

E: 仓库 “http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu bionic Release” 没有 Release 文件 的错误。

这时，只要编辑/etc/apt/sources.list.d/hzwhuang-ubuntu-ss-qt5-bionic.list 文件，将bionic (18.04版本代号)改成xenial（16.04版本代号）

参考链接：https://www.codetd.com/article/3092913

**Comment by caoxuCarlos** [comment]
@wangzhenya 感谢，问题解决
