### ISSUE TITLE
打开链接上后 还是不能打开被墙的网站

### ISSUE THREAD

**Issue by weithink** [shadowsocks/shadowsocks-qt5#261]
打开链接上后 还是不能打开被墙的网站

**Comment by shixy91** [comment]
Had you set proxy for your browser?

**Comment by WanliTian** [comment]
this happens to me as well.

env:
ubuntu 15.10
chromium

my shadowsock client indicates that the connection has been built
but my browser returns `timeout error`

**Comment by WanliTian** [comment]
i can connect `127.0.0.1:1080` with `telnet`

**Comment by WanliTian** [comment]
client log:
Connecting 106.38.179.32:443 from 127.0.0.1:58000
Connecting 106.38.179.32:443 from 127.0.0.1:58006
Connecting 106.38.179.32:443 from 127.0.0.1:58010
Connecting 106.38.179.32:443 from 127.0.0.1:58014
Connecting 106.38.179.32:443 from 127.0.0.1:58018
Connecting 106.38.179.32:443 from 127.0.0.1:58022
Connecting 106.38.179.32:443 from 127.0.0.1:58026
Connecting 106.38.179.32:443 from 127.0.0.1:58030
Connecting 106.38.179.32:443 from 127.0.0.1:58034
Connecting 106.38.179.32:443 from 127.0.0.1:58038
Connecting 106.38.179.32:443 from 127.0.0.1:58042
Connecting 106.38.179.32:443 from 127.0.0.1:58046
Connecting 106.38.179.32:443 from 127.0.0.1:58050
Connecting 106.38.179.32:443 from 127.0.0.1:58056
Connecting 106.38.179.32:443 from 127.0.0.1:58060
Connecting 106.38.179.32:443 from 127.0.0.1:58064
Connecting 106.38.179.32:443 from 127.0.0.1:58068
Connecting 106.38.179.32:443 from 127.0.0.1:58072
Connecting 106.38.179.32:443 from 127.0.0.1:58076
Connecting 106.38.179.32:443 from 127.0.0.1:58080
Connecting 106.38.179.32:443 from 127.0.0.1:58084
Connecting 106.38.179.32:443 from 127.0.0.1:58094
Connecting 106.38.179.32:443 from 127.0.0.1:58098
Connecting 106.38.179.32:443 from 127.0.0.1:58104
Connecting 106.38.179.32:443 from 127.0.0.1:58108
Connecting 106.38.179.32:443 from 127.0.0.1:58112
Connecting 106.38.179.32:443 from 127.0.0.1:58116
Connecting 106.38.179.32:443 from 127.0.0.1:58120
Connecting 106.38.179.32:443 from 127.0.0.1:58124
Connecting 106.38.179.32:443 from 127.0.0.1:58128
Connecting 106.38.179.32:443 from 127.0.0.1:58132
Connecting 106.38.179.32:443 from 127.0.0.1:58136
Connecting 106.38.179.32:443 from 127.0.0.1:58140
Connecting 106.38.179.32:443 from 127.0.0.1:58144
Connecting 106.38.179.32:443 from 127.0.0.1:58148
Connecting 216.58.221.46:80 from 127.0.0.1:58152
Connecting 216.58.221.36:80 from 127.0.0.1:58156
Connecting 220.181.21.230:80 from 127.0.0.1:58164
Connecting 218.30.98.21:80 from 127.0.0.1:58180
Connecting 218.30.98.21:80 from 127.0.0.1:58184
Connecting 115.159.36.67:80 from 127.0.0.1:58188
Connecting 218.30.98.21:80 from 127.0.0.1:58192
Connecting 218.30.98.21:80 from 127.0.0.1:58218
Connecting 218.30.98.21:80 from 127.0.0.1:58222
Connecting 115.159.36.67:80 from 127.0.0.1:58226
Connecting 218.30.98.21:80 from 127.0.0.1:58230
Connecting 218.30.98.21:80 from 127.0.0.1:58234
Connecting 115.159.36.67:80 from 127.0.0.1:58238
Connecting 220.181.21.230:80 from 127.0.0.1:58254
Connecting 220.181.21.230:80 from 127.0.0.1:58262
Connecting 216.58.221.46:443 from 127.0.0.1:58268
Connecting 106.38.179.32:443 from 127.0.0.1:58276
Connecting 106.38.179.32:443 from 127.0.0.1:58280
Connecting 106.38.179.32:443 from 127.0.0.1:58284
Connecting 106.38.179.32:443 from 127.0.0.1:58288
Connecting 106.38.179.32:443 from 127.0.0.1:58292
Connecting 106.38.179.32:443 from 127.0.0.1:58300
Connecting 106.38.179.32:443 from 127.0.0.1:58304
Connecting 106.38.179.32:443 from 127.0.0.1:58308
Connecting 106.38.179.32:443 from 127.0.0.1:58312
Connecting 106.38.179.32:443 from 127.0.0.1:58316
Connecting 106.38.179.32:443 from 127.0.0.1:58320
Connecting 106.38.179.32:443 from 127.0.0.1:58324
Connecting 106.38.179.32:443 from 127.0.0.1:58328
Connecting 106.38.179.32:443 from 127.0.0.1:58332
Connecting 106.38.179.32:443 from 127.0.0.1:58336
Connecting 106.38.179.32:443 from 127.0.0.1:58342
Connecting 106.38.179.32:443 from 127.0.0.1:58346
Connecting 106.38.179.32:443 from 127.0.0.1:58350
Connecting 106.38.179.32:443 from 127.0.0.1:58354
Connecting 106.38.179.32:443 from 127.0.0.1:58356
Connecting 106.38.179.32:443 from 127.0.0.1:58362
Connecting 106.38.179.32:443 from 127.0.0.1:58366
Connecting 106.38.179.32:443 from 127.0.0.1:58370
Connecting 106.38.179.32:443 from 127.0.0.1:58374
Connecting 106.38.179.32:443 from 127.0.0.1:58378
Connecting 106.38.179.32:443 from 127.0.0.1:58382
Connecting 106.38.179.32:443 from 127.0.0.1:58386
Connecting 106.38.179.32:443 from 127.0.0.1:58392
Connecting 106.38.179.32:443 from 127.0.0.1:58396
Connecting 106.38.179.32:443 from 127.0.0.1:58404
Connecting 106.38.179.32:443 from 127.0.0.1:58408
Connecting 106.38.179.32:443 from 127.0.0.1:58414
Connecting 106.38.179.32:443 from 127.0.0.1:58418
Connecting 106.38.179.32:443 from 127.0.0.1:58422
Connecting 106.38.179.32:443 from 127.0.0.1:58426
Connecting 106.38.179.32:443 from 127.0.0.1:58430
Connecting 106.38.179.32:443 from 127.0.0.1:58434
Connecting 106.38.179.32:443 from 127.0.0.1:58438
Connecting 106.38.179.32:443 from 127.0.0.1:58442
Connecting 106.38.179.32:443 from 127.0.0.1:58446
Connecting 106.38.179.32:443 from 127.0.0.1:58450
Connecting 106.38.179.32:443 from 127.0.0.1:58454
Connecting 106.38.179.32:443 from 127.0.0.1:58494
Connecting 106.38.179.32:443 from 127.0.0.1:58498
Connecting 106.38.179.32:443 from 127.0.0.1:58506
Connecting 106.38.179.32:443 from 127.0.0.1:58514
Connecting 198.74.100.243:80 from 127.0.0.1:58518
Connecting 198.74.100.243:80 from 127.0.0.1:58520

**Comment by librehat** [comment]
请设置相应代理设置。
Chrome/Chromium要安装插件

**Comment by WanliTian** [comment]
插件我已经安装了！！并且firefox是有设置代理的地方的。
日志显示我的浏览器请求是发到客户端的。

**Comment by WanliTian** [comment]
@librehat 
@shixy91

**Comment by librehat** [comment]
那你檢查一下防火墻的設置，從客戶端到服務端的鏈接估計不通暢

**Comment by WanliTian** [comment]
@librehat 
客户端显示已经连接

**Comment by WanliTian** [comment]
@librehat 
比如我浏览器链接百度， 这是客户端的日志：
Connecting 220.181.112.244:443 from 127.0.0.1:45576

我在终端telnet 220.18.112.224 443可以连接
所以网络是没有问题的
并且我的iptables没有添加任何的规则

**Comment by librehat** [comment]
检查一下shadowsocks服务端的日志？

**Comment by WanliTian** [comment]
@librehat 

客户端确实没看出什么问题来。
求解决方案

**Comment by shixy91** [comment]
Please cat the logs on your server.
There might be something wrong on the server-side.
