### ISSUE TITLE
因本地端口问题无法启动

### ISSUE THREAD

**Issue by qwerty250** [shadowsocks/shadowsocks-qt5#262]
Initialising ciphers...
RC4-MD5 (RC4-MD5) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen failed.

系统重启后问题依旧，将本地端口从1080改为1081暂时解决。

**Comment by librehat** [comment]
检查是否有别的应用程序占用了1080端口
