### ISSUE TITLE
ubuntu14.04 64位 + chrome 48.0.2564.103 (64-bit) + SwitchyOmega 无法显示网页

### ISSUE THREAD

**Issue by LiuWenJu** [shadowsocks/shadowsocks-qt5#264]
如题描述，切换http(s)同样不能显示网页
[log.txt](https://github.com/shadowsocks/shadowsocks-qt5/files/126105/log.txt)

**Comment by shixy91** [comment]
please make sure you're using socks5 protocol in both ss-qt5 and switchyomega

**Comment by librehat** [comment]
Check your profile configuration.
And check your server side log.

**Comment by LiuWenJu** [comment]
I am sure my server and client have no problem.The same server it can work on my mobile phone,but can't work on my computer
![2016-02-12 16 33 51](https://cloud.githubusercontent.com/assets/10233397/13002107/d64f427e-d1a6-11e5-9c7a-ac0e550d63fd.png)
![2016-02-12 16 34 39](https://cloud.githubusercontent.com/assets/10233397/13002108/d64f647a-d1a6-11e5-8857-982a9e930b88.png)
![2016-02-12 16 36 01](https://cloud.githubusercontent.com/assets/10233397/13002106/d64d6094-d1a6-11e5-904e-c526c28ba159.png)
![2016-02-12 16 36 28](https://cloud.githubusercontent.com/assets/10233397/13002109/d64f7884-d1a6-11e5-8f14-5b7f990c8776.png)

**Comment by librehat** [comment]
As you can see the remote server closed the connection. It can be a wrong password or method.

**Comment by LiuWenJu** [comment]
My mobile phone can work,but my pc can't in the same server.I found this problem after I upgraded my chrome
