### ISSUE TITLE
建议增加HTTP(S)支持

### ISSUE THREAD

**Issue by StrollStars** [shadowsocks/shadowsocks-qt5#265]
有些软件只支持HTTP(S)，这样就需要通过第三方软件转换，希望能够支持。

**Comment by librehat** [comment]
早就支持了。

**Comment by StrollStars** [comment]
嗯，选项中有，但是Socks5和HTTP(S)同时只能开一个吧？

**Comment by librehat** [comment]
对的。

**Comment by StrollStars** [comment]
希望能够同时打开Socks5和HTTP(S)端口。

**Comment by librehat** [comment]
没精力加新功能了，而且这根本不算必要的。原生socks5在Linux平台没什么问题

**Comment by StrollStars** [comment]
好的，还是谢谢你。我用的是Win平台，也不知为什么一些软件会不支持Socks。
