### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by shenxs** [shadowsocks/shadowsocks-qt5#268]
系统:ubuntu,unity桌面环境,ssqt5版本2.6.1

感觉现在Application Indicator中可以操作的选项太少,只有显示/隐藏和退出这两项,

我经常遇到的场景是需要切换代理,每次都需要
点顶栏的icon---->restore--->选择断开连接----->选择我想要的代理--->点击连接--->关闭窗口
能否减少这些流程,给indicator更多的选项,类似windows下shadowsocks
点击icon-->选择我想要的代理--->ok

效果类似以下图片,这是一个显示网速的system-indicator,可以快速选择要显示的是wifi网速还是eth0的网速或者是所有的
![image](https://cloud.githubusercontent.com/assets/9768335/13142374/844b6522-d677-11e5-9474-25911b4127b5.png)

**Comment by librehat** [comment]
#228 直接选择你要的代理然后强制连接即可。

因为诸多不便，indicator的菜单是不会修改的。整个程序的设计和Windows版本是不一样的，ss-qt5是管理多个shadowsocks连接，而不是仅有的一个代理。
