### ISSUE TITLE
建议:连接服务器前自动关闭已经打开的同端口服务器

### ISSUE THREAD

**Issue by xwj1003** [shadowsocks/shadowsocks-qt5#269]
比如我已经连接一个服务器1.1.1.1:1080,后来我要重新连接2.2.2.2:1080,因为端口相同,必须要关闭1.1.1.1,比较麻烦,可否**自动关闭**后再连接2.2.2.2
不同的端口不需要关闭

**Comment by xwj1003** [comment]
如果我有100个服务器,你要找出那个已经连接的服务器,实在是够累的.

**Comment by librehat** [comment]
用 强制连接
