### ISSUE TITLE
Shadowsocks-Qt5一连接就直接闪退

### ISSUE THREAD

**Issue by RacingDawn** [shadowsocks/shadowsocks-qt5#270]
在fedora 21平台下，Shadowsocks-Qt5一连接某个节点就直接闪退，再运行Shadowsocks-Qt5时提示Failed to communicate with previously running instance of Shadowsocks-Qt5 (PID: 8684). It might already crashed.

**Comment by librehat** [comment]
某个节点？哪个节点啊？

P.S. Fedora 21已经EOL了

首先建议升级Fedora到22或23，然后安装debuginfo，在gdb下启动ss-qt5，崩溃后把backtrace的信息贴上来。

**Comment by RacingDawn** [comment]
谢谢，问题已解决。因为我之前在安装时没有sudo dnf update更新缓存，只是执行了sudo dnf copr enable librehat/shadowsocks和sudo dnf install shadowsocks-qt5，导致安装好的shadowsocks-qt5一连接节点直接闪退。将其卸载后，重新用上述三条命令安装后连接成功。。。。。

**Comment by librehat** [comment]
也不应该闪退的啊……不过问题“解决”了就好。

**Comment by chenyangguang** [comment]
（1）ss-qt5模式， 我也遇到了， ubuntu16.04下面， ss-qt5启动后直接闪退， 弹出显示很多行
7f90e86c2000-7f90e86d8000 r-xp 00003000 08:022 1576728  /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
7f90e86c2000-7f90e86d8000 r-xp 00003000 08:022 1576728  /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
7f90e86c2000-7f90e86d8000 r-xp 00003000 08:022 1576728  /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
7f90e86c2000-7f90e86d8000 r-xp 00003000 08:022 1576728  /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
.....这种格式的东西， 然后和上面的兄弟一样的先报一个Failed to communicate with previously running instance of Shadowsocks-Qt5（pid）, 然后ubuntu蓝色的crash标志就显示： The application Shadowsocks-Qt5 has closed unexpectedly. 挂了。


（2）我换成golang方式， 按照你的go里面的都配置好了。 shadowsocks-server 和shadowsocks-local进程也运行起来， SwitchySharp也配置了。 而且搜索 www.google.com 时 SwitchySharp 显示蓝色了， 但是等不上去了。 ps: 都是重装系统惹的。请问这个是什么情况？
