### ISSUE TITLE
fedora下影响botan更新

### ISSUE THREAD

**Issue by carlnerv** [shadowsocks/shadowsocks-qt5#273]
更新时报错：

依赖解析错误:

软件包：shadowsocks-qt5-2.6.1-1.fc23.x86_64 (@librehat-shadowsocks)
    需要：libbotan-1.10.so.0()(64bit)
    正在删除: botan-1.10.9-7.fc23.x86_64 (installed)
        libbotan-1.10.so.0()(64bit)
    更新，由: botan-1.10.12-1.fc23.x86_64 (updates)
       ~libbotan-1.10.so.1()(64bit)

**Comment by librehat** [comment]
Fixed by setting `AutoReq` to no in spec file. Please run `sudo dnf upgrade --refresh` now. :smiley:
