### ISSUE TITLE
centos7下无法启动

### ISSUE THREAD

**Issue by xykoflz** [shadowsocks/shadowsocks-qt5#274]
按照安装指引进行安装，安装过程正常，无报错
安装完成后发现无法启动，用终端启动报无法找到libbotan-1.10.so.0
```bash
[root@localhost bin]# ss-qt5
ss-qt5: error while loading shared libraries: libbotan-1.10.so.0: cannot open shared object file: No such file or directory
```
用rpm查看botan，发现libbotan-1.10.so.0确实不存在
```bash
[root@localhost bin]# rpm -ql botan
/usr/lib64/libbotan-1.10.so.1
/usr/lib64/libbotan-1.10.so.1.12
/usr/share/doc/botan-1.10.12
/usr/share/doc/botan-1.10.12/README.fedora
/usr/share/doc/botan-1.10.12/readme.txt
/usr/share/licenses/botan-1.10.12
/usr/share/licenses/botan-1.10.12/license.txt
```

**Comment by librehat** [comment]
蛋疼的依赖关系，尝试ln -s做个软链接到so.1吧

**Comment by librehat** [comment]
libQtShadowsocks on Copr got rebuilt. It's linked against `libbotan-1.10.so.1` now. `sudo yum upgrade` and it should be fixed

**Comment by xykoflz** [comment]
yeah, it fixed. thanks!

**Comment by zhugentan** [comment]
刚刚升级到shadowsocks-qt5.x86_64 2.6.1-2.fc23，
启动时报错：ss-qt5: error while loading shared libraries: libbotan-1.10.so.1: cannot open shared object file: No such file or directory

rpm查看botan：
rpm -ql botan
/usr/lib64/libbotan-1.10.so.0
/usr/lib64/libbotan-1.10.so.0.9
/usr/share/doc/botan
/usr/share/doc/botan/README.fedora
/usr/share/doc/botan/license.txt
/usr/share/doc/botan/readme.txt
怎么办呢？现在只能用shadowsocks-libev，但是没有GUI。。
b

**Comment by librehat** [comment]
你升级没有升级整个系统吗？`sudo dnf upgrade --refresh`

**Comment by zhugentan** [comment]
升级过了

**Comment by zhugentan** [comment]
升级过了

**Comment by librehat** [comment]
升级过了不可能是botan-1.10.9的
