### ISSUE TITLE
Feodra22 可以连接shadowsocks远程服务器，但是无法使用

### ISSUE THREAD

**Issue by zzt93** [shadowsocks/shadowsocks-qt5#275]
可以远程连接，也可检查延迟，但是就是没有流量。症状与这个[issue](https://github.com/shadowsocks/shadowsocks-qt5/issues/229)很像，但是log不一样。
日志显示

Initialising ciphers...
RC4-MD5 (RC4-MD5)  initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen at port 1080
Connecting www.google.com:443 from 127.0.0.1:54896
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54904
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54908
Connecting ssl.gstatic.com:443 from 127.0.0.1:54912
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54916
Remote socket debug: The remote host closed the connection
Connecting ssl.gstatic.com:443 from 127.0.0.1:54920
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54926
Remote socket debug: The remote host closed the connection
Connecting ssl.gstatic.com:443 from 127.0.0.1:54930
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting ssl.gstatic.com:443 from 127.0.0.1:54934
Connecting global.bing.com:80 from 127.0.0.1:54938
Connecting 1.perf.msedge.net:80 from 127.0.0.1:54940
Connecting 2.perf.msedge.net:80 from 127.0.0.1:54942
Connecting 6.perf.msedge.net:80 from 127.0.0.1:54950
Connecting 3.perf.msedge.net:80 from 127.0.0.1:54944
Connecting 5.perf.msedge.net:80 from 127.0.0.1:54948
Connecting a4.bing.com:80 from 127.0.0.1:54952
Connecting global.bing.com:80 from 127.0.0.1:54960
Connecting global.bing.com:80 from 127.0.0.1:54958
Connecting global.bing.com:443 from 127.0.0.1:54966
Connecting 4.perf.msedge.net:80 from 127.0.0.1:54946
Connecting global.bing.com:80 from 127.0.0.1:54956
Connecting a4.bing.com:80 from 127.0.0.1:54954
Connecting global.bing.com:80 from 127.0.0.1:54962
Connecting global.bing.com:80 from 127.0.0.1:54964
Connecting global.bing.com:443 from 127.0.0.1:54968
Connecting login.live.com:443 from 127.0.0.1:54974
Connecting login.live.com:443 from 127.0.0.1:54972
Connecting global.bing.com:443 from 127.0.0.1:54970
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting global.bing.com:80 from 127.0.0.1:55014
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting global.bing.com:80 from 127.0.0.1:55018
Remote socket debug: The remote host closed the connection
Connecting global.bing.com:80 from 127.0.0.1:55028
Remote socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Connecting ssl.gstatic.com:443 from 127.0.0.1:55038
Remote socket debug: The remote host closed the connection
Connecting ssl.gstatic.com:443 from 127.0.0.1:55042
Remote socket debug: The remote host closed the connection
Connecting ssl.gstatic.com:443 from 127.0.0.1:55048
Remote socket debug: The remote host closed the connection
Connecting ssl.gstatic.com:443 from 127.0.0.1:55052
Remote socket debug: The remote host closed the connection

改成http（s）也没有用：
Initialising ciphers...
RC4-MD5 (RC4-MD5) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
SOCKS5 port is 45706
Running as a HTTP proxy server
TCP server listen at port 1080
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 
Invalid URL: 

浏览器为chrome+SwitchyOmega（@FelisCatus）。但是，应该不是浏览器问题，因为firefox也不行。难道是Fedora的问题？

以下为chrome://net-internals/#proxy的初始内容
```
Proxy server: 127.0.0.1:1080
Bypass list: 
  127.0.0.1
  [::1]
  localhost
```
请问是什么原因呢？

**Comment by librehat** [comment]
Please check your password/encryption method, etc. Check logs in your server side. (client-side log is usually not very useful)

**Comment by zzt93** [comment]
A friend of mine use RC4 in the mac. Which encryption method should I use?

**Comment by zzt93** [comment]
Thank you very much. We changed the encryption method. And It works.

**Comment by librehat** [comment]
RC4 is deprecated and removed from `ss-qt5`. Good to know it works now. :)
