### ISSUE TITLE
建议:下面的列表框,每个类的宽度,默认值能否小一点?

### ISSUE THREAD

**Issue by xwj1003** [shadowsocks/shadowsocks-qt5#276]
列宽度太大了, 而且每次调整后无法保存,每次重新打开都要调整.

**Comment by librehat** [comment]
下个版本会保存好大小位置。已经推到master分支了，请等待下个版本

**Comment by xwj1003** [comment]
点击列排序这个设置也希望能保存. 每次打开默认是不排序的

**Comment by librehat** [comment]
这个没必要保存吧，打开点一下要排序的那列就好了……不过实现也不难，先mark在这里了#279

**Comment by xwj1003** [comment]
懒人推动科技发展. 呵呵
