### ISSUE TITLE
2.6.1版本在fedora23的包依赖错误问题

### ISSUE THREAD

**Issue by choleraehyq** [shadowsocks/shadowsocks-qt5#277]
系统fedora23，内核版本4.4.3
今天更新之后出现了包依赖问题。
首先是找不到libbotan-1.10.so.1动态库，此时我已经安装了botan-1.10.9这个包。必须更新到botan-1.10.12才能找到这个动态库。
之后提示找不到libQt5Widgets.so.5动态库，我手动安装了qwt-qt5之后才能正常运行。安装的qwt-qt5版本是6.1.2。

**Comment by librehat** [comment]
dnf upgrade --refresh 
昨晚解决了

**Comment by choleraehyq** [comment]
@librehat 
依赖问题仍然存在。安装的是2.6.1-2.fc23版本，运行ss-qt5会提示找不到libQt5Widgets.so.5动态库，需要手动安装qwt-qt5包。
另外，shadowsocks的图标找不到，显示的是默认图标。

fedora23，内核版本4.4.7，桌面是xfce4.

**Comment by librehat** [comment]
qwt根本是另一个东西啊……ss-qt5不依赖qwt

**Comment by 1dot75cm** [comment]
`libQt5Widgets.so.5` 需要安装 `qt5-qtbase-gui-5.6.0-9.fc23.x86_64`。

之前源里的包使用 Qt 5.5.1 编译，已更新 FZUG 源的 rpm 包（基于 Qt 5.6.0），请测试一下有无问题。 @choleraehyq

**Comment by choleraehyq** [comment]
@librehat  @1dot75cm 
我不是很熟悉qt5，当时随便翻了一下包列表看了一下描述就装了个qwt-qt5，恰好依赖qt5-qtbase-gui-5.6.0-9.fc23.x86_64所以碰巧问题解了……

FZUG 源的包没有问题了，但是 librehat/shadowsocks 这个 copr 源的包还是有问题。 wiki 里的安装指南用的是 copr 源。

**Comment by 1dot75cm** [comment]
@librehat  重新编译即可
@choleraehyq  感谢测试

**Comment by librehat** [comment]
谢谢，Fedora经常更新底层库神烦。。

**Comment by librehat** [comment]
把COPR源里的包重新编译了，应该没问题了。
