### ISSUE TITLE
使用 Google 搜索时报出异常流量预警 

### ISSUE THREAD

**Issue by snowjade** [shadowsocks/shadowsocks-qt5#280]
就像这个一样：
![3dc110a6-dd36-11e4-96bf-a94920c41fd7](https://cloud.githubusercontent.com/assets/11959369/13658209/f05a420e-e6af-11e5-83ed-d8601e2b4611.png)
如图，通过 shadowsocks 使用 Google 搜索时出现流量异常预警，必须手动输入验证码才可以完成搜索，有遇到这个问题的吗？而且这个ip我觉得应该只有我一个人用。（我购买了vps，然后装了shadowsocks，帐号密码没有告诉过别人，应该只有我在用吧。）有什么解决办法么？
相关问题:https://github.com/shadowsocks/shadowsocks-qt5/issues/74#issuecomment-187517701

**Comment by shixy91** [comment]
digitalocean的很多ip被google限制，换个vps厂商

**Comment by snowjade** [comment]
我用的不是digitalocean，是alpharacks，一年3刀的。

**Comment by GYXie** [comment]
我有遇到同样的问题，不知道有什么解决方案？

**Comment by maqic** [comment]
@snowjade 一个月3刀吧

**Comment by snowjade** [comment]
@maqic  一年3刀，但是我没有用了，速度太不稳定。
