### ISSUE TITLE
ubuntu 经常自动奔溃

### ISSUE THREAD

**Issue by whatwewant** [shadowsocks/shadowsocks-qt5#281]
而且端口被占用不报错而是奔溃

**Comment by whatwewant** [comment]
version 2.6.1

**Comment by librehat** [comment]
是崩溃，不是奔溃。 请按照说明把复现步骤写清楚。

**Comment by hetykai** [comment]
奔溃。。。楼主是来搞siao的么。。。

**Comment by whatwewant** [comment]
@librehat 
内网多人连接 不知道什么时候就会崩溃 见图
https://ooo.0o0.ooo/2016/03/27/56f8b044c61ba.png
https://ooo.0o0.ooo/2016/03/27/56f8b044dbe44.png

**Comment by librehat** [comment]
I won't receive error reports from Ubuntu. Please run `ss-qt5` from Terminal, and paste the error messages.

**Comment by losywee** [comment]
我这里很正常，从来没崩溃

**Comment by librehat** [comment]
Closed until more info available
