### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by catcat520** [shadowsocks/shadowsocks-qt5#282]
能否增加一个功能，定时(自定义间隔)读取 一个 网络上的 http://www.test.com/ss.json 文件
然后根据里面的信息 连接 ss 服务器 并运行

**Comment by librehat** [comment]
抱歉这个功能并不能融合到目前ss-qt5的框架里，没有办法兼容目前的设计。

你可以下载json文件然后手动导入再连接。
