### ISSUE TITLE
centos 7 安装后无法打开

### ISSUE THREAD

**Issue by foreverxyz** [shadowsocks/shadowsocks-qt5#283]
安装过程没有报错，安装完成后打开没反应，ss-qt5报错：ss-qt5: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
麻烦给看下怎么回事

**Comment by librehat** [comment]
不应该的，你确定你有安装 qt5-qtbase ？ 依赖关系没有破？`yum deplist shadowsocks-qt5`

**Comment by foreverxyz** [comment]
已安装qt5-qtbase,依赖关系应该也正常：
[root@192 桌面]# yum deplist shadowsocks-qt5
已加载插件：fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.yun-idc.com
 * epel: mirrors.opencas.cn
 * extras: mirrors.pubyun.com
 * updates: mirrors.sina.cn
软件包：shadowsocks-qt5.x86_64 2.6.1-2.el7.centos
   依赖：botan
   provider: botan.x86_64 1.10.12-1.el7
   依赖：libQtShadowsocks >= 1.8.0
   provider: libQtShadowsocks.x86_64 1.8.4-2.el7.centos
   依赖：libappindicator
   provider: libappindicator.x86_64 12.10.0-10.el7
   依赖：qrencode-libs
   provider: qrencode-libs.x86_64 3.4.1-3.el7
   provider: qrencode-libs.i686 3.4.1-3.el7
   依赖：qt5-qtbase
   provider: qt5-qtbase.x86_64 5.5.1-11.el7
   依赖：zbar
   provider: zbar.x86_64 0.10-21.el7.centos

**Comment by IanHua** [comment]
一样的问题，LZ解决了吗？

**Comment by 1223745302** [comment]
我也是打不开，有人解决了吗？正常安装了。在程序里也能看到，但是点击后只是在任务栏出现一个程序标题，然后就自动退出了。

**Comment by cnlinjie** [comment]
@1223745302   突然弹了邮件，可能是关注了，进来看看~
有安装qt环境么？没有的话先安装个~

**Comment by 1223745302** [comment]
好像是没有安装qt环境.....
我正在找资料安装qt.....

**Comment by IanHua** [comment]
我后来放弃了QT5，改用命令行来打开客户端
首先
pip install shadowsocks
然后
按照[这里](https://wiki.archlinux.org/index.php/Shadowsocks_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))的配置和客户端打开命令sslocal操作
最后
在chrome上安装SwitchyOmega，配好shadowsocks的本地IP和端口就可以了

**Comment by cnlinjie** [comment]
@IanHua  也是个不错的方式，QT 环境太操蛋~

**Comment by 1223745302** [comment]
@cnlinjie 我在安装Qt 5开发环境.....

**Comment by foreverxyz** [comment]
@IanHua 同样也在使用sslocal, qt 安装后死活用不了，最近在考虑刷路由器固件加载ss，直接连上就行

**Comment by 1223745302** [comment]
@IanHua 如果是Firefox装什么插件啊？

**Comment by IanHua** [comment]
@1223745302 找个代理Proxy插件应该都可以

**Comment by 1223745302** [comment]
@IanHua 谢谢，我找找看看

**Comment by 1223745302** [comment]
@IanHua 已经pip 了shadowsocks，但是没有相关文件夹怎么破.....

**Comment by IanHua** [comment]
随便找一个地方创建一个config.json就可以了，直接sslocal

**Comment by BDomne** [comment]
可以试试 yum install qt5-qtbase-devel

**Comment by librehat** [comment]
这和devel包有什么关系？

**Comment by BDomne** [comment]
无意中搜到的，试了下，按正常步骤装好，再装上devel，ss-qt5就起来了

**Comment by waterCold** [comment]
shadowsocks-qt 5 无法启动hk。
注：hk是我买的服务器节点的配置文件

**Comment by librehat** [comment]
你得检查你的配置，而且什么错误信息呢？

**Comment by waterCold** [comment]
已解决，是端口被其他进程占用

**Comment by houbaron** [comment]
yum install qt5-qtbase-devel亲测可破！谢谢！

**Comment by DonaldDai** [comment]
@lanHua 用命令行的方法一定要配置Chrome吗？我也成功安装了，结果还是不能翻墙

**Comment by DonaldDai** [comment]
@houbaron @BDomne qt5，我配置完了之后连接正常，测试延迟也有反应，但是就是翻不了墙，是浏览器的原因吗？我用的是默认火狐

**Comment by liangzai-cool** [comment]
1. yum install qt5-qtbase-devel
2. 把代理类型设置为https，配置火狐http代理，并选中 `为所有协议使用相同代理` 复选框

**Comment by huzhifeng** [comment]
`libQt5Widgets.so.5`是由包`qt5-qtbase-gui`所提供，所以安装`qt5-qtbase-gui`即可解决问题
```
[huzhifeng@CentOS72 ~]$ yum provides libQt5Widgets.so.5
qt5-qtbase-gui-5.6.1-10.el7.i686 : Qt5 GUI-related libraries
Repo        : base
Matched from:
Provides    : libQt5Widgets.so.5
[huzhifeng@CentOS72 ~]$ sudo yum install qt5-qtbase-gui
[huzhifeng@CentOS72 ~]$ rpm -ql qt5-qtbase-gui | grep "libQt5Widgets.so.5"
/usr/lib64/libQt5Widgets.so.5
/usr/lib64/libQt5Widgets.so.5.6
/usr/lib64/libQt5Widgets.so.5.6.1
[huzhifeng@CentOS72 ~]$
```

**Comment by BingBlog** [comment]
@DonaldDai  服务起来了，但是ping不同www.google.com。端口查看，如下：
```
[root@localhost ~]# lsof -i:1080
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ss-qt5  12550 root   17u  IPv4  51595      0t0  TCP localhost:socks (LISTEN)
ss-qt5  12550 root   18u  IPv4  51596      0t0  UDP localhost:socks 

```
你找到问题了么？

**Comment by ykelvis** [comment]
ping没走你的socks端口，ping不到正常。
`curl --proxy socks5://127.0.0.1:1080 ip.cn` 这样看。

**Comment by BingBlog** [comment]
@ykelvis 搞好了。。谢谢！这个原理是通过本地进行的代理么，我在浏览器中配置了代理就就可以了。
