### ISSUE TITLE
Win7 连接两个服务器sandboxie必崩溃bug

### ISSUE THREAD

**Issue by catcat520** [shadowsocks/shadowsocks-qt5#285]
打开沙盘运行ss，先连接ss-a 然后用火狐上网，再连接ss-b 然后用chrome 上网，

重复2,3次这个动作，半分钟崩溃

**Comment by librehat** [comment]
Don't open two instances!

**Comment by catcat520** [comment]
是 win7的啊，况且你也设定了 两个进程不能同时运行，怎么同时打开两个界面呢

我的意思是 在一个界面里面连接两个 ss

**Comment by librehat** [comment]
2.6.1?

**Comment by catcat520** [comment]
是 2.61 的，在 sandboxie 测试的 经常崩溃

**Comment by catcat520** [comment]
看了一下 #205 有反馈 win7 下切换 ss 会崩溃
我这个是 同时连接两个 ss 会崩溃，或许是同一个bug导致的

**Comment by librehat** [comment]
如果不用沙箱会崩溃吗？我自己电脑上无法重现目前汇报的这些崩溃问题

**Comment by catcat520** [comment]
不用沙盘没有测试过，由于特殊原因，所以要用到沙盘

**Comment by librehat** [comment]
见 #205 应该最新版本已经修复
