### ISSUE TITLE
“从  gui-config 导入连接”不能够更新已有的连接而是出现重复

### ISSUE THREAD

**Issue by er1iang** [shadowsocks/shadowsocks-qt5#287]
“从  gui-config 导入连接” 这个功能应当能够对相同的线路（服务器和端口都相同）进行更新或者保留，从实用角度上来说，应当在这种情况更新本地配置或者提示自由选择保留本地配置或文件配置。

另外 #200 对自动化脚本确实很有用, 我的线路更新脚本每次只能提取出线路,然后还是需要从界面中进行导入, 并删除重复的线路，很不方便。

很感谢你做的工作，可惜对 C++ 这一块不熟, 没法贡献代码了

**Comment by librehat** [comment]
更新是不可能的，因为配置可以重名，没有唯一标识符。

**Comment by lliuz** [comment]
@librehat 感谢您的贡献，的确没有唯一的key，但是否能够添加多选删除的功能，现在删除配置只能一个个删...
