### ISSUE TITLE
CentOS 7安装后无法打开

### ISSUE THREAD

**Issue by 1223745302** [shadowsocks/shadowsocks-qt5#288]
按照指南安装后在程序列表里有程序了。但是打不开，点击程序icon后只是在任务栏出现一个标题而已。然后就退出了。 上不了图？#283

**Comment by cnlinjie** [comment]
使用命令行启动看看，有错误的话在命令行会有信息，~

**Comment by 1223745302** [comment]
额，在终端里怎么启动啊？

**Comment by cnlinjie** [comment]
打开终端，输入：`ss-qt5 `
我这边的是这么启动的~

**Comment by 1223745302** [comment]
ss-qt5: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
这样的.....

**Comment by cnlinjie** [comment]
http://stackoverflow.com/questions/21244105/qt-project-release-ubuntu-error-while-loading-shared-libraries-libqt5widgets

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
谢谢。看得不太懂，还在慢慢研究。谢谢你的帮助
下载不下来。貌似我没有添加相关的源

**Comment by 1223745302** [comment]
Loading mirror speeds from cached hostfile
 * base: mirrors.btte.net
 * elrepo: ftp.yz.yamagata-u.ac.jp
 * epel: mirrors.neusoft.edu.cn
 * extras: mirrors.sina.cn
 * updates: mirrors.sina.cn
没有可用软件包 libqt5。
错误：无须任何处理

**Comment by cnlinjie** [comment]
我直接安装了：dnf install qt-devel

**Comment by cnlinjie** [comment]
我直接安装了：dnf install qt-devel

**Comment by cnlinjie** [comment]
不行就用pip方式安装吧，上个issue有个回复的，那个方式也不错

**Comment by 1223745302** [comment]
@cnlinjie dnf: 未找到命令.....
我也想pip啊，但是我是火狐啊，没有ss下载不了谷歌浏览器....

**Comment by cnlinjie** [comment]
你用yum ，我的是dnf 管理器~
`yun install qt-devel` 试试

**Comment by 1223745302** [comment]
在线安装Qt开发环境，结果才2%就报错下载不下来....哭哭

**Comment by cnlinjie** [comment]
...报了什么错误...

**Comment by 1223745302** [comment]
忘了.....好像是权限不够还是什么.....可是我是放在/home/Qt目录下的啊，不存在权限不够啊。
qt-devel安装完了。SS还是大不开....

**Comment by cnlinjie** [comment]
安装肯定是用root安装，要不然没权限。
安装了还是打不开，提示啥。。。

**Comment by 1223745302** [comment]
命令行的话还是那个提示，直接点击icon的话也还是只在任务栏出现一下....

**Comment by 1223745302** [comment]
我肯定有给权限啊。先chmod u+x给权限，然后在终端里进root，./运行啊

**Comment by cnlinjie** [comment]
好奇怪。你再：`yum install qt `呢？
实在不行，先用pip安装吧，不一定要chrome的，firefox+插件也可以

**Comment by 1223745302** [comment]
qt-4.8.5-11.el7.x86_64 已安装并且是最新版本
虽然Qt开发环境安装没有成功，但是好像也是可以用诶，Qt Designer也可以用诶。

**Comment by 1223745302** [comment]
pip不了......
要疯了...
我还是卸载Qt开发环境再试试吧。
诶，开发环境和Qt环境不是两个东西吧。

**Comment by cnlinjie** [comment]
QT 开发的程序，是依赖QT环境，理论上QT的开发环境就带了QT的运行环境~~
pip 是python的东西，你也需要先安装个pip，
Linux折腾就是这样，不过也可以会学到蛮多东西的~，遇到不懂就查~，渐渐的就懂了~

**Comment by 1223745302** [comment]
@cnlinjie对啊，对啊。今晚学了好多东西呢。

**Comment by 1223745302** [comment]
@cnlinjie 你有 XMPP什么的帐号吗？在Empathy聊方便点啊。

**Comment by librehat** [comment]
你这个问题应该是和 #283 重复的

终端下执行 ```ldd `which ss-qt5` ``` 显示什么？

**Comment by 1223745302** [comment]
@librehat 显示这些
ldd `which ss-qt5`
	linux-vdso.so.1 =>  (0x00007ffc355b3000)
	libqrencode.so.3 => /lib64/libqrencode.so.3 (0x00007facc61a0000)
	libQtShadowsocks.so.1 => /lib64/libQtShadowsocks.so.1 (0x00007facc5f64000)
	libbotan-1.10.so.1 => /lib64/libbotan-1.10.so.1 (0x00007facc5a74000)
	libzbar.so.0 => /lib64/libzbar.so.0 (0x00007facc583c000)
	libappindicator.so.1 => /lib64/libappindicator.so.1 (0x00007facc562f000)
	libdbusmenu-glib.so.4 => /lib64/libdbusmenu-glib.so.4 (0x00007facc5412000)
	libgtk-x11-2.0.so.0 => /lib64/libgtk-x11-2.0.so.0 (0x00007facc4d8e000)
	libgdk-x11-2.0.so.0 => /lib64/libgdk-x11-2.0.so.0 (0x00007facc4acd000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007facc48a6000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007facc4530000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007facc431b000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007facc410d000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007facc3ee7000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007facc3bc0000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007facc3974000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007facc3738000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007facc34e8000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007facc31b0000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007facc2f0a000)
	libQt5Widgets.so.5 => not found
	libQt5Gui.so.5 => not found
	libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007facc2dab000)
	libQt5DBus.so.5 => /lib64/libQt5DBus.so.5 (0x00007facc2d29000)
	libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007facc2839000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007facc25a2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007facc2386000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007facc207d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007facc1d7b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007facc1b65000)
	libc.so.6 => /lib64/libc.so.6 (0x00007facc17a3000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007facc1593000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007facc11ab000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007facc0fa6000)
	librt.so.1 => /lib64/librt.so.1 (0x00007facc0d9e000)
	libz.so.1 => /lib64/libz.so.1 (0x00007facc0b88000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007facc097f000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007facc0763000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007facc0425000)
	libXv.so.1 => /lib64/libXv.so.1 (0x00007facc021f000)
	libv4l2.so.0 => /lib64/libv4l2.so.0 (0x00007facc0011000)
	libindicator.so.7 => /lib64/libindicator.so.7 (0x00007facbfe03000)
	libdbusmenu-gtk.so.4 => /lib64/libdbusmenu-gtk.so.4 (0x00007facbfbee000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007facbf9ea000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007facbf7e3000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007facbf5d9000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007facbf3d6000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007facbf1c6000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007facbefbb000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007facbedb0000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007facbebad000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007facbe9a9000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007facbe797000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007facbe58f000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007facbe369000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007facbe14f000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007facbdf4d000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007facbdcf3000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007facbdac8000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007facbd81a000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00007facbd5f9000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007facbd3f5000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007facbd1ea000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007facbcfc8000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007facbcd9d000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007facbcb30000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007facbc8e8000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007facbc4e8000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007facbc16f000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007facbab9b000)
	libpcre16.so.0 => /lib64/libpcre16.so.0 (0x00007facba942000)
	/lib64/ld-linux-x86-64.so.2 (0x00007facc63c4000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00007facba714000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007facba512000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007facba2f7000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007facba0f2000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007facb9eef000)
	libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00007facb9ceb000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00007facb9add000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00007facb98d5000)
	libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00007facb96d0000)
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007facb94c9000)
	libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00007facb92c6000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007facb90bf000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007facb8eb2000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007facb8cac000)
	libv4lconvert.so.0 => /lib64/libv4lconvert.so.0 (0x00007facb8a33000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007facb87d1000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007facb85ac000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007facb8390000)
	libgbm.so.1 => /lib64/libgbm.so.1 (0x00007facb8183000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007facb7f7f000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007facb7d32000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007facb7a4d000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007facb7849000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007facb7616000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007facb73c1000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007facb71b1000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007facb6fad000)

**Comment by 1223745302** [comment]
@cnlinjie 我又安装了一遍Qt开发环境，是在2%到3%的时候报错一个什么有东西下载不下来。not found。

**Comment by librehat** [comment]
你Qt5不是yum安装的吗？系统明显没有找到qt的相关库。

**Comment by 1223745302** [comment]
我是在网上找的教程，去官网下的安装包安装的

**Comment by librehat** [comment]
请使用yum安装……网上搜来的中文教程害人

**Comment by 1223745302** [comment]
@librehat yum怎么装？

**Comment by librehat** [comment]
Please check fedoraproject or CentOS wiki.

**Comment by Valentine23v** [comment]
诚心求教最后如何解决 我也出现了这样的问题 @1223745302

**Comment by huzhifeng** [comment]
@Valentine23v 
`libQt5Widgets.so.5`是由包`qt5-qtbase-gui`所提供，所以安装`qt5-qtbase-gui`即可解决问题
```
[huzhifeng@CentOS72 ~]$ yum provides libQt5Widgets.so.5
qt5-qtbase-gui-5.6.1-10.el7.i686 : Qt5 GUI-related libraries
Repo        : base
Matched from:
Provides    : libQt5Widgets.so.5
[huzhifeng@CentOS72 ~]$ sudo yum install qt5-qtbase-gui
[huzhifeng@CentOS72 ~]$ rpm -ql qt5-qtbase-gui | grep "libQt5Widgets.so.5"
/usr/lib64/libQt5Widgets.so.5
/usr/lib64/libQt5Widgets.so.5.6
/usr/lib64/libQt5Widgets.so.5.6.1
[huzhifeng@CentOS72 ~]$
```
