### ISSUE TITLE
Kali Linux rolling 突然无法启动　打开报错

### ISSUE THREAD

**Issue by Zhiwei1996** [shadowsocks/shadowsocks-qt5#290]
点击桌面启动器打开弹窗报错，闪退；命令行打开，报错大堆信息 
`root@zhiwei:~# ss-qt5 

(process:4459): Gtk-CRITICAL **: IA__gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:4459): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:4459): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:4459): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:4459): GLib-GObject-WARNING **: value "TRUE" of type 'gboolean' is invalid or out of range for property 'visible' of type 'gboolean'

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:4459): GLib-GObject-WARNING **: /build/glib2.0-2.46.2/./gobject/gsignal.c:2516: signal 'child-added' is invalid for instance '0x1b1d150' of type 'GtkMenu'

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:4459): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:4459): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:4459): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:4459): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:4459): Gtk-WARNING **: Screen for GtkWindow not set; you must always set
a screen for a GtkWindow before using the window

(process:4459): Gdk-CRITICAL **: IA__gdk_screen_get_display: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): Gdk-CRITICAL **: IA__gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(process:4459): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:4459): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:4459): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:4459): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:4459): Gdk-CRITICAL **: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): Gdk-CRITICAL **: IA__gdk_screen_get_display: assertion 'GDK_IS_SCREEN (screen)' failed

(process:4459): Gdk-CRITICAL **: IA__gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed

(process:4459): Gdk-CRITICAL **: IA__gdk_screen_get_number: assertion 'GDK_IS_SCREEN (screen)' failed
段错误
root@zhiwei:~# 
`

**Comment by Zhiwei1996** [comment]
补充：之前刚一直能够正常使用，今天突然就崩了
　　　安装是通过git clone，dpkg-buildpackage -uc -us -b得到deb包然后安装
依赖包都安装完全了，其中libshadowsocks-dev没法apt-get安装，同样git clone然后dpkg-buildpackage -uc -us -b得到deb包安装的

**Comment by Zhiwei1996** [comment]
学生新手，希望能够解惑，必应不到有用的信息

**Comment by librehat** [comment]
Please don't compile the `master` code. Download and compile released tarball please.

**Comment by Zhiwei1996** [comment]
Thank you very much, but I have tried to download V2.6.1 released and 2.6.0, and it still cannot work as expected, it crashed as  before,  errors are same
I am sorry that I have bad English , maybe you can understand my words
I don't know which country the people you're


Sent using CloudMagic Email<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.3.8&pv=5.1&source=email_footer_2>
On Tue, Mar 29, 2016 at 8:20 PM, Symeon Huang <notifications@github.com<mailto:notifications@github.com>> wrote:


Please don't compile the master code. Download and compile released tarball please.
