### ISSUE TITLE
安装完了配置好了 还是不能上google

### ISSUE THREAD

**Issue by ggggss** [shadowsocks/shadowsocks-qt5#291]
服务器地址用的hkpt1.yingsu.wang  服务器端口xxxx  密码xxxx  aes-256-cfb  本地地址127.0.0.1 本地端口1080  服务类型https  比win7下的客户端多了 本地地址 服务类型 显示已经连接 有延迟   打开浏览器依旧不能google

**Comment by librehat** [comment]
Did you configure your browser?
