### ISSUE TITLE
 sudo apt-get update fail.

### ISSUE THREAD

**Issue by stanyung** [shadowsocks/shadowsocks-qt5#293]
W: Failed to fetch bzip2:/var/lib/apt/lists/partial/ppa.launchpad.net_hzwhuang_ss-qt5_ubuntu_dists_trusty_main_binary-amd64_Packages  Hash Sum mismatch

W: Failed to fetch bzip2:/var/lib/apt/lists/partial/ppa.launchpad.net_hzwhuang_ss-qt5_ubuntu_dists_trusty_main_binary-i386_Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by librehat** [comment]
Potentially your network issues. Clean the cache and try it again.

Or try to use proxy for apt-get in case your network is hijacked
