### ISSUE TITLE
archlinux 无法安装

### ISSUE THREAD

**Issue by gengmu** [shadowsocks/shadowsocks-qt5#294]
: 进行安装吗？ [Y/n] 
:: 正在获取软件包......
 libdbusmenu-glib-16...    62.6 KiB   137K/s 00:00 [----------------------] 100%
 libdbusmenu-gtk2-16...    35.2 KiB  0.00B/s 00:00 [----------------------] 100%
 libindicator-gtk2-1...    27.0 KiB  8.79M/s 00:00 [----------------------] 100%
 libappindicator-act...    32.0 KiB  0.00B/s 00:00 [----------------------] 100%
(11/11) 正在检查密钥环里的密钥                     [----------------------] 100%
(11/11) 正在检查软件包完整性                       [----------------------] 100%
错误：libdbusmenu-glib: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is unknown trust
:: 文件 /var/cache/pacman/pkg/libdbusmenu-glib-16.04.0-1-x86_64.pkg.tar.xz 已损坏 (无效或已损坏的软件包 (PGP 签名)).
打算删除吗？ [Y/n] y
错误：libdbusmenu-gtk2: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is unknown trust
:: 文件 /var/cache/pacman/pkg/libdbusmenu-gtk2-16.04.0-1-x86_64.pkg.tar.xz 已损坏 (无效或已损坏的软件包 (PGP 签名)).
打算删除吗？ [Y/n] y
错误：libindicator-gtk2: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is unknown trust
:: 文件 /var/cache/pacman/pkg/libindicator-gtk2-12.10.1-6-x86_64.pkg.tar.xz 已损坏 (无效或已损坏的软件包 (PGP 签名)).
打算删除吗？ [Y/n] n
错误：libappindicator-activate-gtk2: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is unknown trust
:: 文件 /var/cache/pacman/pkg/libappindicator-activate-gtk2-12.10.0-5-x86_64.pkg.tar.xz 已损坏 (无效或已损坏的软件包 (PGP 签名)).
打算删除吗？ [Y/n] n
错误：无法提交处理 (无效或已损坏的软件包)
发生错误，没有软件包被更新。
==> 重新构建 shadowsocks-qt5 ?[y/N]
==> ---------------------------
==>

**Comment by ykelvis** [comment]
你需要archlinuxcn的keyring。
`pacman -S archlinuxcn-keyring`
