### ISSUE TITLE
compile shadowsocks-qt5 error 

### ISSUE THREAD

**Issue by banyudu** [shadowsocks/shadowsocks-qt5#301]
Error message is:

     shadowsocks-qt5/src/ssvalidator.cpp:6: error: 'getSupportedMethodList' is not a member of 'QSS::Cipher'
     QList<QByteArray> methodBA = QSS::Cipher::getSupportedMethodList();
                                  ^

Maybe libqtshadowsocks(v1.8.4) is outdated for shadowsocks-qt5 master branch.

**Comment by librehat** [comment]
Yeah, the master branch uses unreleased API

**Comment by banyudu** [comment]
Thanks
