### ISSUE TITLE
fedora 24 包依赖出错

### ISSUE THREAD

**Issue by nextair** [shadowsocks/shadowsocks-qt5#304]
[zyl@ZYL-PC ~]$ sudo dnf install shadowsocks-qt5
上次元数据过期检查：0:00:16 前，执行于 Sun May  1 18:40:48 2016。
错误：nothing provides libbotan-1.10.so.0()(64bit) needed by shadowsocks-qt5-2.6.1-1.fc24.x86_64
(尝试添加 '--allowerasing' 到命令行来代替冲突的软件包)
[zyl@ZYL-PC ~]$

**Comment by librehat** [comment]
Fedora 24 is not supported at this moment (wait for stable release since Fedora tends to change libraries quite frequently)

**Comment by nextair** [comment]
Thanks

**Comment by personalAccountV** [comment]
Fedora 24 released today, is any plan to support Fedora 24?
Thanks.

**Comment by librehat** [comment]
Will do ASAP.
