### ISSUE TITLE
ss-qt5 ubuntu1404 firefox 不能访问youtube

### ISSUE THREAD

**Issue by luoyanghero** [shadowsocks/shadowsocks-qt5#305]
1.按照教程https://aitanlu.com/ubuntu-shadowsocks-ke-hu-duan-pei-zhi.html
安装了ss-qt5.配置好自己的vps（在win7下已经测试是能用的），显示connected。查看ss-qt5 log：
Initialising ciphers...
AES-256/CFB (AES-256-CFB) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen at port 1080
没有发现异常。
2.使用firefox打开www.youtube.com，不能打开。
ping www.youtube.com 也没有反应。
3.更改firefox network setting,尝试以下3种模式，都不能打开youtube，能打开baidu。
No Proxy
Auto-detect proxy settings from this network 
Use system proxy settings

**Comment by librehat** [comment]
自己看wiki，Firefox的代理根本就没有设。

**Comment by luoyanghero** [comment]
你是说设置127.0.0.1/1080.我也试过，不行
