### ISSUE TITLE
ubuntu16.04 Crash when connection? 

### ISSUE THREAD

**Issue by YuanHang0** [shadowsocks/shadowsocks-qt5#311]
log:

*** Error in `ss-qt5': free(): invalid next size (fast): 0x0000000001ff4680 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7f32755d3725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7f32755dbf4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f32755dfabc]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x110)[0x7f3276172ec0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7f3276a3605c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x256)[0x7f3276a3b516]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb)[0x7f327614362b]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x2c6)[0x7f3276145a26]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2dc673)[0x7f3276199673]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7f3272a41127]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4a380)[0x7f3272a41380]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f3272a4142c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f3276199a7f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x10a)[0x7f3276140dea]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c)[0x7f3276148e8c]
ss-qt5[0x413749]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f327557c830]
ss-qt5[0x414529]
======= Memory map: ========
00400000-00474000 r-xp 00000000 08:02 1974173                            /usr/bin/ss-qt5
00674000-00676000 r--p 00074000 08:02 1974173                            /usr/bin/ss-qt5
00676000-00678000 rw-p 00076000 08:02 1974173                            /usr/bin/ss-qt5
01c87000-025c0000 rw-p 00000000 00:00 0                                  [heap]
7f3214000000-7f3214021000 rw-p 00000000 00:00 0 
7f3214021000-7f3218000000 ---p 00000000 00:00 0 
7f3218000000-7f3218021000 rw-p 00000000 00:00 0 
7f3218021000-7f321c000000 ---p 00000000 00:00 0 
7f321c000000-7f321c021000 rw-p 00000000 00:00 0 
7f321c021000-7f3220000000 ---p 00000000 00:00 0 
7f3224000000-7f3224021000 rw-p 00000000 00:00 0 
7f3224021000-7f3228000000 ---p 00000000 00:00 0 
7f3228000000-7f3228021000 rw-p 00000000 00:00 0 
7f3228021000-7f322c000000 ---p 00000000 00:00 0 
7f322c000000-7f322c021000 rw-p 00000000 00:00 0 
7f322c021000-7f3230000000 ---p 00000000 00:00 0 
7f3230000000-7f3230021000 rw-p 00000000 00:00 0 
7f3230021000-7f3234000000 ---p 00000000 00:00 0 
7f3234000000-7f3234021000 rw-p 00000000 00:00 0 
7f3234021000-7f3238000000 ---p 00000000 00:00 0 
7f3238000000-7f3238021000 rw-p 00000000 00:00 0 
7f3238021000-7f323c000000 ---p 00000000 00:00 0 
7f323dffc000-7f323dffd000 ---p 00000000 00:00 0 
7f323dffd000-7f323e7fd000 rw-p 00000000 00:00 0 
7f323e7fd000-7f323e7fe000 ---p 00000000 00:00 0 
7f323e7fe000-7f323effe000 rw-p 00000000 00:00 0 
7f323effe000-7f323efff000 ---p 00000000 00:00 0 
7f323efff000-7f323f7ff000 rw-p 00000000 00:00 0 
7f323f7ff000-7f323f800000 ---p 00000000 00:00 0 
7f323f800000-7f3240000000 rw-p 00000000 00:00 0 
7f3240000000-7f3240021000 rw-p 00000000 00:00 0 
7f3240021000-7f3244000000 ---p 00000000 00:00 0 
7f3244166000-7f324416b000 r-xp 00000000 08:02 2888264                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f324416b000-7f324436b000 ---p 00005000 08:02 2888264                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f324436b000-7f324436c000 r--p 00005000 08:02 2888264                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f324436c000-7f324436d000 rw-p 00006000 08:02 2888264                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f324436d000-7f324436e000 ---p 00000000 00:00 0 
7f324436e000-7f3244b6e000 rw-p 00000000 00:00 0 
7f3244b6e000-7f3244b6f000 ---p 00000000 00:00 0 
7f3244b6f000-7f324536f000 rw-p 00000000 00:00 0 
7f324536f000-7f3245370000 ---p 00000000 00:00 0 
7f3245370000-7f3245b70000 rw-p 00000000 00:00 0 
7f3245b70000-7f3245b71000 ---p 00000000 00:00 0 
7f3245b71000-7f3246371000 rw-p 00000000 00:00 0 
7f3246371000-7f3247671000 r-xp 00000000 08:02 1969186                    /usr/lib/nvidia-361/libnvidia-glcore.so.361.42
7f3247671000-7f3247691000 rwxp 01300000 08:02 1969186                    /usr/lib/nvidia-361/libnvidia-glcore.so.361.42
7f3247691000-7f3247a20000 r-xp 01320000 08:02 1969186                    /usr/lib/nvidia-361/libnvidia-glcore.so.361.42
7f3247a20000-7f3247c1f000 ---p 016af000 08:02 1969186                    /usr/lib/nvidia-361/libnvidia-glcore.so.361.42
7f3247c1f000-7f3247fec000 rw-p 016ae000 08:02 1969186                    /usr/lib/nvidia-361/libnvidia-glcore.so.361.42
7f3247fec000-7f3248000000 rw-p 00000000 00:00 0 
7f3248000000-7f3248022000 rw-p 00000000 00:00 0 
7f3248022000-7f324c000000 ---p 00000000 00:00 0 
7f324c151000-7f324c153000 r-xp 00000000 08:02 2888272                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f324c153000-7f324c352000 ---p 00002000 08:02 2888272                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f324c352000-7f324c353000 r--p 00001000 08:02 2888272                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f324c353000-7f324c354000 rw-p 00002000 08:02 2888272                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f324c354000-7f324c35f000 r-xp 00000000 08:02 2888266                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f324c35f000-7f324c55e000 ---p 0000b000 08:02 2888266                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f324c55e000-7f324c55f000 r--p 0000a000 08:02 2888266                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f324c55f000-7f324c560000 rw-p 0000b000 08:02 2888266                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f324c560000-7f324c566000 rw-p 00000000 00:00 0 
7f324c566000-7f324c567000 ---p 00000000 00:00 0 
7f324c567000-7f324cd67000 rw-p 00000000 00:00 0 
7f324cd67000-7f324cdc7000 rw-s 00000000 00:05 8716300                    /SYSV00000000 (deleted)
7f324cdc7000-7f324cea8000 rw-s 00000000 00:05 8683531                    /SYSV00000000 (deleted)
7f324cea8000-7f324cf54000 r--p 00000000 08:02 3277391                    /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
7f324cf54000-7f324cf57000 r-xp 00000000 08:02 1969189                    /usr/lib/nvidia-361/tls/libnvidia-tls.so.361.42
7f324cf57000-7f324d157000 ---p 00003000 08:02 1969189                    /usr/lib/nvidia-361/tls/libnvidia-tls.so.361.42
7f324d157000-7f324d158000 rw-p 00003000 08:02 1969189                    /usr/lib/nvidia-361/tls/libnvidia-tls.so.361.42
7f324d158000-7f324d21e000 r-xp 00000000 08:02 1969182                    /usr/lib/nvidia-361/libGLX_nvidia.so.361.42
7f324d21e000-7f324d251000 rwxp 000c6000 08:02 1969182                    /usr/lib/nvidia-361/libGLX_nvidia.so.361.42
7f324d251000-7f324d264000 r-xp 000f9000 08:02 1969182                    /usr/lib/nvidia-361/libGLX_nvidia.so.361.42
7f324d264000-7f324d463000 ---p 0010c000 08:02 1969182                    /usr/lib/nvidia-361/libGLX_nvidia.so.361.42
7f324d463000-7f324d48c000 rw-p 0010b000 08:02 1969182                    /usr/lib/nvidia-361/libGLX_nvidia.so.361.42
7f324d48c000-7f324d593000 rw-p 00000000 00:00 0 
7f324d59b000-7f324d5eb000 rw-s 00000000 00:05 8781837                    /SYSV00000000 (deleted)
7f324d5eb000-7f324d63d000 r--p 00000000 08:02 3277519                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf
7f324d63d000-7f324d694000 r--p 00000000 08:02 3277526                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-R.ttf
7f324d694000-7f324d6e7000 r-xp 00000000 08:02 1974437                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f324d6e7000-7f324d6e9000 r--p 00052000 08:02 1974437                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f324d6e9000-7f324d6eb000 rw-p 00054000 08:02 1974437                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f324d6eb000-7f324d6ec000 ---p 00000000 00:00 0 
7f324d6ec000-7f324deec000 rw-p 00000000 00:00 0 
7f324deec000-7f324deff000 r-xp 00000000 08:02 1974881                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7f324deff000-7f324e0fe000 ---p 00013000 08:02 1974881                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7f324e0fe000-7f324e0ff000 r--p 00012000 08:02 1974881                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7f324e0ff000-7f324e100000 rw-p 00013000 08:02 1974881                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7f324e100000-7f324e10b000 r-xp 00000000 08:02 1974879                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7f324e10b000-7f324e30b000 ---p 0000b000 08:02 1974879                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7f324e30b000-7f324e30c000 r--p 0000b000 08:02 1974879                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7f324e30c000-7f324e30d000 rw-p 0000c000 08:02 1974879                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7f324e30d000-7f324e314000 r-xp 00000000 08:02 2228316                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7f324e314000-7f324e513000 ---p 00007000 08:02 2228316                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7f324e513000-7f324e514000 r--p 00006000 08:02 2228316                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7f324e514000-7f324e515000 rw-p 00007000 08:02 2228316                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7f324e515000-7f324e569000 r--p 00000000 08:02 3277394                    /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
7f324e569000-7f324e59b000 r-xp 00000000 08:02 1975152                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f324e59b000-7f324e79a000 ---p 00032000 08:02 1975152                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f324e79a000-7f324e79b000 r--p 00031000 08:02 1975152                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f324e79b000-7f324e79c000 rw-p 00032000 08:02 1975152                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f324e79c000-7f324e7d0000 r-xp 00000000 08:02 1975362                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f324e7d0000-7f324e9cf000 ---p 00034000 08:02 1975362                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f324e9cf000-7f324e9d1000 r--p 00033000 08:02 1975362                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f324e9d1000-7f324e9d2000 rw-p 00035000 08:02 1975362                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f324e9d2000-7f324e9e3000 r-xp 00000000 08:02 1966568                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f324e9e3000-7f324ebe3000 ---p 00011000 08:02 1966568                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f324ebe3000-7f324ebe4000 r--p 00011000 08:02 1966568                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f324ebe4000-7f324ebe5000 rw-p 00012000 08:02 1966568                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f324ebe5000-7f324ec16000 r-xp 00000000 08:02 1975194                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f324ec16000-7f324ee16000 ---p 00031000 08:02 1975194                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f324ee16000-7f324ee17000 r--p 00031000 08:02 1975194                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f324ee17000-7f324ee18000 rw-p 00032000 08:02 1975194                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f324ee18000-7f324ee72000 r-xp 00000000 08:02 1975422                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f324ee72000-7f324f071000 ---p 0005a000 08:02 1975422                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f324f071000-7f324f07b000 r--p 00059000 08:02 1975422                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f324f07b000-7f324f07d000 rw-p 00063000 08:02 1975422                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f324f07d000-7f324f082000 r-xp 00000000 08:02 1973461                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7f324f082000-7f324f282000 ---p 00005000 08:02 1973461                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7f324f282000-7f324f283000 r--p 00005000 08:02 1973461                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7f324f283000-7f324f284000 rw-p 00006000 08:02 1973461                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7f324f284000-7f324f286000 r-xp 00000000 08:02 2888348                    /lib/x86_64-linux-gnu/libutil-2.23.so
7f324f286000-7f324f485000 ---p 00002000 08:02 2888348                    /lib/x86_64-linux-gnu/libutil-2.23.so
7f324f485000-7f324f486000 r--p 00001000 08:02 2888348                    /lib/x86_64-linux-gnu/libutil-2.23.so
7f324f486000-7f324f487000 rw-p 00002000 08:02 2888348                    /lib/x86_64-linux-gnu/libutil-2.23.so
7f324f487000-7f324f497000 r-xp 00000000 08:02 1974617                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7f324f497000-7f324f696000 ---p 00010000 08:02 1974617                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7f324f696000-7f324f697000 r--p 0000f000 08:02 1974617                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7f324f697000-7f324f698000 rw-p 00010000 08:02 1974617                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7f324f698000-7f324f6a3000 r-xp 00000000 08:02 1974619                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7f324f6a3000-7f324f8a2000 ---p 0000b000 08:02 1974619                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7f324f8a2000-7f324f8a3000 r--p 0000a000 08:02 1974619                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7f324f8a3000-7f324f8a4000 rw-p 0000b000 08:02 1974619                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7f324f8a4000-7f324f8a7000 r-xp 00000000 08:02 1974623                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7f324f8a7000-7f324faa6000 ---p 00003000 08:02 1974623                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7f324faa6000-7f324faa7000 r--p 00002000 08:02 1974623                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7f324faa7000-7f324faa8000 rw-p 00003000 08:02 1974623                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7f324faa8000-7f324fbcc000 r-xp 00000000 08:02 1975034                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f324fbcc000-7f324fdcb000 ---p 00124000 08:02 1975034                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f324fdcb000-7f324fdd6000 r--p 00123000 08:02 1975034                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f324fdd6000-7f324fdd8000 rw-p 0012e000 08:02 1975034                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f324fdd8000-7f324fdd9000 rw-p 00000000 00:00 0 
7f324fdd9000-7f324fdfe000 r-xp 00000000 08:02 1974757                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7f324fdfe000-7f324fffe000 ---p 00025000 08:02 1974757                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7f324fffe000-7f324ffff000 r--p 00025000 08:02 1974757                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7f324ffff000-7f3250000000 rw-p 00026000 08:02 1974757                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7f3250000000-7f3250022000 rw-p 00000000 00:00 0 
7f3250022000-7f3254000000 ---p 00000000 00:00 0 
7f3254000000-7f3254022000 rw-p 00000000 00:00 0 
7f3254022000-7f3258000000 ---p 00000000 00:00 0 
7f3258000000-7f3258021000 rw-p 00000000 00:00 0 
7f3258021000-7f325c000000 ---p 00000000 00:00 0 
7f325c048000-7f325c051000 r-xp 00000000 08:02 2360572                    /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
7f325c051000-7f325c052000 r--p 00008000 08:02 2360572                    /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
7f325c052000-7f325c053000 rw-p 00009000 08:02 2360572                    /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
7f325c053000-7f325c0aa000 r--p 00000000 08:02 3277526                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-R.ttf
7f325c0aa000-7f325c0ab000 r-xp 00000000 08:02 1975111                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7f325c0ab000-7f325c2aa000 ---p 00001000 08:02 1975111                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7f325c2aa000-7f325c2ab000 r--p 00000000 08:02 1975111                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7f325c2ab000-7f325c2ac000 rw-p 00001000 08:02 1975111                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7f325c2ac000-7f325c2b7000 r-xp 00000000 08:02 2888310                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f325c2b7000-7f325c4b6000 ---p 0000b000 08:02 2888310                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f325c4b6000-7f325c4b7000 r--p 0000a000 08:02 2888310                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f325c4b7000-7f325c4b8000 rw-p 0000b000 08:02 2888310                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f325c4b8000-7f325c668000 r-xp 00000000 08:02 1975889                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f325c668000-7f325c867000 ---p 001b0000 08:02 1975889                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f325c867000-7f325c86f000 r--p 001af000 08:02 1975889                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f325c86f000-7f325c871000 rw-p 001b7000 08:02 1975889                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f325c871000-7f325c872000 rw-p 00000000 00:00 0 
7f325c872000-7f325c8cd000 r-xp 00000000 08:02 1973462                    /usr/lib/x86_64-linux-gnu/libORBit-2.so.0.1.0
7f325c8cd000-7f325cacd000 ---p 0005b000 08:02 1973462                    /usr/lib/x86_64-linux-gnu/libORBit-2.so.0.1.0
7f325cacd000-7f325cadc000 r--p 0005b000 08:02 1973462                    /usr/lib/x86_64-linux-gnu/libORBit-2.so.0.1.0
7f325cadc000-7f325cadf000 rw-p 0006a000 08:02 1973462                    /usr/lib/x86_64-linux-gnu/libORBit-2.so.0.1.0
7f325cadf000-7f325caf5000 r-xp 00000000 08:02 1973498                    /usr/lib/x86_64-linux-gnu/libbonobo-activation.so.4.0.0
7f325caf5000-7f325ccf5000 ---p 00016000 08:02 1973498                    /usr/lib/x86_64-linux-gnu/libbonobo-activation.so.4.0.0
7f325ccf5000-7f325ccf7000 r--p 00016000 08:02 1973498                    /usr/lib/x86_64-linux-gnu/libbonobo-activation.so.4.0.0
7f325ccf7000-7f325ccf9000 rw-p 00018000 08:02 1973498                    /usr/lib/x86_64-linux-gnu/libbonobo-activation.so.4.0.0
7f325ccf9000-7f325cd59000 r-xp 00000000 08:02 1973497                    /usr/lib/x86_64-linux-gnu/libbonobo-2.so.0.0.0
7f325cd59000-7f325cf59000 ---p 00060000 08:02 1973497                    /usr/lib/x86_64-linux-gnu/libbonobo-2.so.0.0.0
7f325cf59000-7f325cf5e000 r--p 00060000 08:02 1973497                    /usr/lib/x86_64-linux-gnu/libbonobo-2.so.0.0.0
7f325cf5e000-7f325cf69000 rw-p 00065000 08:02 1973497                    /usr/lib/x86_64-linux-gnu/libbonobo-2.so.0.0.0
7f325cf69000-7f325cf8c000 r-xp 00000000 08:02 1975024                    /usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0.2.0
7f325cf8c000-7f325d18c000 ---p 00023000 08:02 1975024                    /usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0.2.0
7f325d18c000-7f325d18e000 r--p 00023000 08:02 1975024                    /usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0.2.0
7f325d18e000-7f325d18f000 rw-p 00025000 08:02 1975024                    /usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0.2.0
7f325d18f000-7f325d1bd000 r-xp 00000000 08:02 1974954                    /usr/lib/x86_64-linux-gnu/libgconf-2.so.4.1.5
7f325d1bd000-7f325d3bc000 ---p 0002e000 08:02 1974954                    /usr/lib/x86_64-linux-gnu/libgconf-2.so.4.1.5
7f325d3bc000-7f325d3bd000 r--p 0002d000 08:02 1974954                    /usr/lib/x86_64-linux-gnu/libgconf-2.so.4.1.5
7f325d3bd000-7f325d3be000 rw-p 0002e000 08:02 1974954                    /usr/lib/x86_64-linux-gnu/libgconf-2.so.4.1.5
7f325d3be000-7f325d422000 r-xp 00000000 08:02 1974190                    /usr/lib/x86_64-linux-gnu/libgnomevfs-2.so.0.2400.4
7f325d422000-7f325d621000 ---p 00064000 08:02 1974190                    /usr/lib/x86_64-linux-gnu/libgnomevfs-2.so.0.2400.4
7f325d621000-7f325d624000 r--p 00063000 08:02 1974190                    /usr/lib/x86_64-linux-gnu/libgnomevfs-2.so.0.2400.4
7f325d624000-7f325d626000 rw-p 00066000 08:02 1974190                    /usr/lib/x86_64-linux-gnu/libgnomevfs-2.so.0.2400.4
7f325d626000-7f325d627000 rw-p 00000000 00:00 0 
7f325d627000-7f325d63d000 r-xp 00000000 08:02 1974192                    /usr/lib/x86_64-linux-gnu/libgnome-2.so.0.3200.1
7f325d63d000-7f325d83c000 ---p 00016000 08:02 1974192                    /usr/lib/x86_64-linux-gnu/libgnome-2.so.0.3200.1
7f325d83c000-7f325d83d000 r--p 00015000 08:02 1974192                    /usr/lib/x86_64-linux-gnu/libgnome-2.so.0.3200.1
7f325d83d000-7f325d83e000 rw-p 00016000 08:02 1974192                    /usr/lib/x86_64-linux-gnu/libgnome-2.so.0.3200.1
7f325d83e000-7f325d856000 r-xp 00000000 08:02 1974587                    /usr/lib/x86_64-linux-gnu/libart_lgpl_2.so.2.3.21
7f325d856000-7f325da55000 ---p 00018000 08:02 1974587                    /usr/lib/x86_64-linux-gnu/libart_lgpl_2.so.2.3.21
7f325da55000-7f325da56000 r--p 00017000 08:02 1974587                    /usr/lib/x86_64-linux-gnu/libart_lgpl_2.so.2.3.21
7f325da56000-7f325da57000 rw-p 00018000 08:02 1974587                    /usr/lib/x86_64-linux-gnu/libart_lgpl_2.so.2.3.21
7f325da57000-7f325da8a000 r-xp 00000000 08:02 1973725                    /usr/lib/x86_64-linux-gnu/libgnomecanvas-2.so.0.3000.3
7f325da8a000-7f325dc8a000 ---p 00033000 08:02 1973725                    /usr/lib/x86_64-linux-gnu/libgnomecanvas-2.so.0.3000.3
7f325dc8a000-7f325dc8b000 r--p 00033000 08:02 1973725                    /usr/lib/x86_64-linux-gnu/libgnomecanvas-2.so.0.3000.3
7f325dc8b000-7f325dc8c000 rw-p 00034000 08:02 1973725                    /usr/lib/x86_64-linux-gnu/libgnomecanvas-2.so.0.3000.3
7f325dc8c000-7f325dcf6000 r-xp 00000000 08:02 1974204                    /usr/lib/x86_64-linux-gnu/libbonoboui-2.so.0.0.0
7f325dcf6000-7f325def6000 ---p 0006a000 08:02 1974204                    /usr/lib/x86_64-linux-gnu/libbonoboui-2.so.0.0.0
7f325def6000-7f325def7000 r--p 0006a000 08:02 1974204                    /usr/lib/x86_64-linux-gnu/libbonoboui-2.so.0.0.0
7f325def7000-7f325defa000 rw-p 0006b000 08:02 1974204                    /usr/lib/x86_64-linux-gnu/libbonoboui-2.so.0.0.0
7f325defa000-7f325defb000 rw-p 00000000 00:00 0 
7f325defb000-7f325df93000 r-xp 00000000 08:02 1974206                    /usr/lib/x86_64-linux-gnu/libgnomeui-2.so.0.2400.5
7f325df93000-7f325e192000 ---p 00098000 08:02 1974206                    /usr/lib/x86_64-linux-gnu/libgnomeui-2.so.0.2400.5
7f325e192000-7f325e195000 r--p 00097000 08:02 1974206                    /usr/lib/x86_64-linux-gnu/libgnomeui-2.so.0.2400.5
7f325e195000-7f325e197000 rw-p 0009a000 08:02 1974206                    /usr/lib/x86_64-linux-gnu/libgnomeui-2.so.0.2400.5
7f325e197000-7f325e198000 rw-p 00000000 00:00 0 
7f325e19c000-7f325e1a1000 r-xp 00000000 08:02 2360576                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f325e1a1000-7f325e1a2000 r--p 00004000 08:02 2360576                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f325e1a2000-7f325e1a3000 rw-p 00005000 08:02 2360576                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f325e1a3000-7f325e1ad000 r-xp 00000000 08:02 2360575                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so[1]    3805 abort (core dumped)  ss-qt5

**Comment by LeoZeda** [comment]
I also have this problem, how to solve it

**Comment by librehat** [comment]
Consolidated to #312

**Comment by LeoZeda** [comment]
It solved.  Consolidated to #312

1.  remove the libqtshadowsocks and shadowsocks-qt5.
2.  install libqtshadowsocks_1.8.4-1~ubuntu16.04.1_amd64.deb( https://code.launchpad.net/~hzwhuang/+archive/ubuntu/ss-qt5/+build/8839723 )
3. reinstall shadowsocks-qt5
