### ISSUE TITLE
希望早点修复ss-qt5因为升级软件导致的闪退

### ISSUE THREAD

**Issue by wzsx150** [shadowsocks/shadowsocks-qt5#316]
大神你好，你制作的这个图形界面的ss确实非常好用，很不错，简单小巧，功能强大！！我用的是Linux mint 17.3

为大神点赞

因为升级软件导致的闪退崩溃，希望大神能够尽快修复更新新版本

感谢了！！

**Comment by librehat** [comment]
WIP
