### ISSUE TITLE
segmentation fault crash

### ISSUE THREAD

**Issue by zhoueh** [shadowsocks/shadowsocks-qt5#318]
The cause is I set up two different entry using same port,
and toggle "connect when start up" in one of them, it crashes directly.  
Now I cant use it at all as it crashes at the very beginning.
Reinstall didn't work. newest client and libqtshadowsocks.  

Could you please tell me where the config file which stored entry info is located? 
I guess maybe I should delete it and restart. 

Thank you in advanced. Good job!

![](http://ww1.sinaimg.cn/large/a6b04788gw1f3y7n1gvtqj20lv0e0n07.jpg)

**Comment by zhoueh** [comment]
By removing the `config.ini`, problem solved.
but still can't use `Test Latency` button, once clicked, it will crash.

**Comment by wjs876046992** [comment]
where is the file `config.ini`
