### ISSUE TITLE
连接后闪退，图标消失！

### ISSUE THREAD

**Issue by yeqibin** [shadowsocks/shadowsocks-qt5#319]
Ubuntu 16.04 64bit 系统 通过ppa安装，终端输入ss-qt5后可以设置，但一点击连接即发生错误退出，以下是错误信息：

*** Error in `ss-qt5': free(): invalid next size (fast): 0x000000000360f730 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7eff9f6ab725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7eff9f6b3f4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7eff9f6b7abc]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x110)[0x7effa024aec0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7effa0b8c05c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x256)[0x7effa0b91516]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb)[0x7effa021b62b]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x2c6)[0x7effa021da26]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2dc673)[0x7effa0271673]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7eff9cb19127]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4a380)[0x7eff9cb19380]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7eff9cb1942c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7effa0271a7f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x10a)[0x7effa0218dea]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c)[0x7effa0220e8c]
ss-qt5[0x413749]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7eff9f654830]
ss-qt5[0x414529]
======= Memory map: ========
00400000-00474000 r-xp 00000000 08:07 3809733                            /usr/bin/ss-qt5
00674000-00676000 r--p 00074000 08:07 3809733                            /usr/bin/ss-qt5
00676000-00678000 rw-p 00076000 08:07 3809733                            /usr/bin/ss-qt5
02458000-03af2000 rw-p 00000000 00:00 0                                  [heap]
7eff44000000-7eff44021000 rw-p 00000000 00:00 0 
7eff44021000-7eff48000000 ---p 00000000 00:00 0 
7eff4c000000-7eff4c021000 rw-p 00000000 00:00 0 
7eff4c021000-7eff50000000 ---p 00000000 00:00 0 
7eff50000000-7eff50021000 rw-p 00000000 00:00 0 
7eff50021000-7eff54000000 ---p 00000000 00:00 0 
7eff54000000-7eff54021000 rw-p 00000000 00:00 0 
7eff54021000-7eff58000000 ---p 00000000 00:00 0 
7eff58aaa000-7eff58aab000 ---p 00000000 00:00 0 
7eff58aab000-7eff592ab000 rw-p 00000000 00:00 0 
7eff5c000000-7eff5c021000 rw-p 00000000 00:00 0 
7eff5c021000-7eff60000000 ---p 00000000 00:00 0 
7eff60aaa000-7eff60aab000 ---p 00000000 00:00 0 
7eff60aab000-7eff612ab000 rw-p 00000000 00:00 0 
7eff612ab000-7eff612ac000 ---p 00000000 00:00 0 
7eff612ac000-7eff61aac000 rw-p 00000000 00:00 0 
7eff61aac000-7eff61aad000 ---p 00000000 00:00 0 
7eff61aad000-7eff622ad000 rw-p 00000000 00:00 0 
7eff622ad000-7eff622b2000 r-xp 00000000 08:07 1837084                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7eff622b2000-7eff624b2000 ---p 00005000 08:07 1837084                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7eff624b2000-7eff624b3000 r--p 00005000 08:07 1837084                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7eff624b3000-7eff624b4000 rw-p 00006000 08:07 1837084                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7eff624b4000-7eff6925a000 r--p 00000000 08:07 396697                     /usr/share/fonts/opentype/noto/NotoSansCJK.ttc
7eff6925a000-7eff70000000 r--p 00000000 08:07 396697                     /usr/share/fonts/opentype/noto/NotoSansCJK.ttc
7eff70000000-7eff70025000 rw-p 00000000 00:00 0 
7eff70025000-7eff74000000 ---p 00000000 00:00 0 
7eff7412f000-7eff74131000 r-xp 00000000 08:07 1836954                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7eff74131000-7eff74330000 ---p 00002000 08:07 1836954                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7eff74330000-7eff74331000 r--p 00001000 08:07 1836954                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7eff74331000-7eff74332000 rw-p 00002000 08:07 1836954                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7eff74332000-7eff7433d000 r-xp 00000000 08:07 1837072                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7eff7433d000-7eff7453c000 ---p 0000b000 08:07 1837072                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7eff7453c000-7eff7453d000 r--p 0000a000 08:07 1837072                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7eff7453d000-7eff7453e000 rw-p 0000b000 08:07 1837072                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7eff7453e000-7eff74544000 rw-p 00000000 00:00 0 
7eff74544000-7eff746a8000 rw-s 00000000 00:05 17760298                   /SYSV00000000 (deleted)
7eff746a8000-7eff746af000 r--s 00000000 08:07 3932218                    /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7eff746af000-7eff746cb000 r--p 00000000 08:07 4729333                    /usr/share/icons/gnome/icon-theme.cache
7eff746cb000-7eff746d9000 r--p 00000000 08:07 4719686                    /usr/share/icons/hicolor/icon-theme.cache
7eff746d9000-7eff7470c000 r--p 00000000 08:07 4733644                    /usr/share/icons/Humanity/icon-theme.cache
7eff7470c000-7eff7471a000 r--p 00000000 08:07 4729400                    /usr/share/icons/ubuntu-mono-dark/icon-theme.cache
7eff7471a000-7eff7471e000 r-xp 00000000 08:07 1839154                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7eff7471e000-7eff7491d000 ---p 00004000 08:07 1839154                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7eff7491d000-7eff7491e000 r--p 00003000 08:07 1839154                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7eff7491e000-7eff7491f000 rw-p 00004000 08:07 1839154                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7eff7491f000-7eff74926000 r-xp 00000000 08:07 1835469                    /lib/x86_64-linux-gnu/libacl.so.1.1.0
7eff74926000-7eff74b25000 ---p 00007000 08:07 1835469                    /lib/x86_64-linux-gnu/libacl.so.1.1.0
7eff74b25000-7eff74b26000 r--p 00006000 08:07 1835469                    /lib/x86_64-linux-gnu/libacl.so.1.1.0
7eff74b26000-7eff74b27000 rw-p 00007000 08:07 1835469                    /lib/x86_64-linux-gnu/libacl.so.1.1.0
7eff74b27000-7eff74b34000 r-xp 00000000 08:07 3815397                    /usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/modules/libfile.so
7eff74b34000-7eff74d33000 ---p 0000d000 08:07 3815397                    /usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/modules/libfile.so
7eff74d33000-7eff74d34000 r--p 0000c000 08:07 3815397                    /usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/modules/libfile.so
7eff74d34000-7eff74d35000 rw-p 0000d000 08:07 3815397                    /usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/modules/libfile.so
7eff74d35000-7eff74d62000 rw-s 00000000 00:05 17170473                   /SYSV00000000 (deleted)
7eff74d62000-7eff74db8000 rw-s 00000000 00:05 17104936                   /SYSV00000000 (deleted)
7eff74db8000-7eff74e38000 rw-s 00000000 00:05 17006629                   /SYSV00000000 (deleted)
7eff74e38000-7eff74e98000 rw-s 00000000 00:05 16973860                   /SYSV00000000 (deleted)
7eff74f79000-7eff74fd0000 r--p 00000000 08:07 4472959                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-R.ttf
7eff74fd0000-7eff75024000 r--p 00000000 08:07 4472975                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-M.ttf
7eff75024000-7eff75077000 r-xp 00000000 08:07 3822605                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7eff75077000-7eff75079000 r--p 00052000 08:07 3822605                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7eff75079000-7eff7507b000 rw-p 00054000 08:07 3822605                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7eff7507b000-7eff7507c000 ---p 00000000 00:00 0 
7eff7507c000-7eff7587c000 rw-p 00000000 00:00 0 
7eff7587c000-7eff758b2000 r-xp 00000000 08:07 3806798                    /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
7eff758b2000-7eff75ab2000 ---p 00036000 08:07 3806798                    /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
7eff75ab2000-7eff75ab7000 r--p 00036000 08:07 3806798                    /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
7eff75ab7000-7eff75ab8000 rw-p 0003b000 08:07 3806798                    /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
7eff75ab8000-7eff75ae8000 r-xp 00000000 08:07 4068265                    /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
7eff75ae8000-7eff75ce7000 ---p 00030000 08:07 4068265                    /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
7eff75ce7000-7eff75ce8000 r--p 0002f000 08:07 4068265                    /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
7eff75ce8000-7eff75ce9000 rw-p 00030000 08:07 4068265                    /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
7eff75ce9000-7eff75cea000 rw-p 00000000 00:00 0 
7eff75cea000-7eff75cfd000 r-xp 00000000 08:07 3803204                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7eff75cfd000-7eff75efc000 ---p 00013000 08:07 3803204                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7eff75efc000-7eff75efd000 r--p 00012000 08:07 3803204                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7eff75efd000-7eff75efe000 rw-p 00013000 08:07 3803204                    /usr/lib/x86_64-linux-gnu/libfcitx-utils.so.0.1
7eff75efe000-7eff75f09000 r-xp 00000000 08:07 3801492                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7eff75f09000-7eff76109000 ---p 0000b000 08:07 3801492                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7eff76109000-7eff7610a000 r--p 0000b000 08:07 3801492                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7eff7610a000-7eff7610b000 rw-p 0000c000 08:07 3801492                    /usr/lib/x86_64-linux-gnu/libfcitx-gclient.so.0.1
7eff7610b000-7eff76112000 r-xp 00000000 08:07 4066530                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7eff76112000-7eff76311000 ---p 00007000 08:07 4066530                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7eff76311000-7eff76312000 r--p 00006000 08:07 4066530                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7eff76312000-7eff76313000 rw-p 00007000 08:07 4066530                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so
7eff76313000-7eff76367000 r--p 00000000 08:08 6030214                    /home/yqb/.fonts/DejaVuSans/DejaVuSansMono.ttf
7eff76367000-7eff76399000 r-xp 00000000 08:07 3803963                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7eff76399000-7eff76598000 ---p 00032000 08:07 3803963                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7eff76598000-7eff76599000 r--p 00031000 08:07 3803963                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7eff76599000-7eff7659a000 rw-p 00032000 08:07 3803963                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7eff7659a000-7eff765ce000 r-xp 00000000 08:07 3804014                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7eff765ce000-7eff767cd000 ---p 00034000 08:07 3804014                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7eff767cd000-7eff767cf000 r--p 00033000 08:07 3804014                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7eff767cf000-7eff767d0000 rw-p 00035000 08:07 3804014                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7eff767d0000-7eff767e1000 r-xp 00000000 08:07 3805402                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7eff767e1000-7eff769e1000 ---p 00011000 08:07 3805402                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7eff769e1000-7eff769e2000 r--p 00011000 08:07 3805402                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7eff769e2000-7eff769e3000 rw-p 00012000 08:07 3805402                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7eff769e3000-7eff76a14000 r-xp 00000000 08:07 3801403                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7eff76a14000-7eff76c14000 ---p 00031000 08:07 3801403                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7eff76c14000-7eff76c15000 r--p 00031000 08:07 3801403                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7eff76c15000-7eff76c16000 rw-p 00032000 08:07 3801403                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7eff76c16000-7eff76c70000 r-xp 00000000 08:07 3801134                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7eff76c70000-7eff76e6f000 ---p 0005a000 08:07 3801134                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7eff76e6f000-7eff76e79000 r--p 00059000 08:07 3801134                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7eff76e79000-7eff76e7b000 rw-p 00063000 08:07 3801134                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7eff76e7b000-7eff76e80000 r-xp 00000000 08:07 3803438                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7eff76e80000-7eff77080000 ---p 00005000 08:07 3803438                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7eff77080000-7eff77081000 r--p 00005000 08:07 3803438                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7eff77081000-7eff77082000 rw-p 00006000 08:07 3803438                    /usr/lib/x86_64-linux-gnu/libORBitCosNaming-2.so.0.1.0
7eff77082000-7eff77084000 r-xp 00000000 08:07 1837080                    /lib/x86_64-linux-gnu/libutil-2.23.so
7eff77084000-7eff77283000 ---p 00002000 08:07 1837080                    /lib/x86_64-linux-gnu/libutil-2.23.so
7eff77283000-7eff77284000 r--p 00001000 08:07 1837080                    /lib/x86_64-linux-gnu/libutil-2.23.so
7eff77284000-7eff77285000 rw-p 00002000 08:07 1837080                    /lib/x86_64-linux-gnu/libutil-2.23.so
7eff77285000-7eff77295000 r-xp 00000000 08:07 3812848                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7eff77295000-7eff77494000 ---p 00010000 08:07 3812848                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7eff77494000-7eff77495000 r--p 0000f000 08:07 3812848                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7eff77495000-7eff77496000 rw-p 00010000 08:07 3812848                    /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
7eff77496000-7eff774a1000 r-xp 00000000 08:07 3812846                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7eff774a1000-7eff776a0000 ---p 0000b000 08:07 3812846                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7eff776a0000-7eff776a1000 r--p 0000a000 08:07 3812846                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7eff776a1000-7eff776a2000 rw-p 0000b000 08:07 3812846                    /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
7eff776a2000-7eff776a5000 r-xp 00000000 08:07 3801361                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7eff776a5000-7eff778a4000 ---p 00003000 08:07 3801361                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7eff778a4000-7eff778a5000 r--p 00002000 08:07 3801361                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7eff778a5000-7eff778a6000 rw-p 00003000 08:07 3801361                    /usr/lib/x86_64-linux-gnu/libavahi-glib.so.1.0.2
7eff778a6000-7eff779ca000 r-xp 00000000 08:07 3804026                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7eff779ca000-7eff77bc9000 ---p 00124000 08:07 3804026                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7eff77bc9000-7eff77bd4000 r--p 00123000 08:07 3804026                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7eff77bd4000-7eff77bd6000 rw-p 0012e000 08:07 3804026                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7eff77bd6000-7eff77bd7000 rw-p 00000000 00:00 0 
7eff77bd7000-7eff77bfc000 r-xp 00000000 08:07 3804201                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7eff77bfc000-7eff77dfc000 ---p 00025000 08:07 3804201                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7eff77dfc000-7eff77dfd000 r--p 00025000 08:07 3804201                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7eff77dfd000-7eff77dfe000 rw-p 00026000 08:07 3804201                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3
7eff77dfe000-7eff77dff000 r-xp 00000000 08:07 3806849                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7eff77dff000-7eff77ffe000 ---p 00001000 08:07 3806849                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7eff77ffe000-7eff77fff000 r--p 00000000 08:07 3806849                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7eff77fff000-7eff78000000 rw-p 00001000 08:07 3806849                    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.0
7eff78000000-7eff78021000 rw-p 00000000 00:00 0 
7eff78021000-7eff7c000000 ---p 00000000 00:00 0 
7eff7c000000-7eff7c022000 rw-p 00000000 00:00 0 
7eff7c022000-7eff80000000 ---p 00000000 00:00 0 
7eff80000000-7eff80021000 rw-p 00000000 00:00 0 
7eff80021000-7eff84000000 ---p 00000000 00:00 0 
7eff84000000-7eff84009000 r--p 00000000 08:07 4720965                    /usr/share/icons/Adwaita/icon-theme.cache
7eff84009000-7eff8402c000 r--s 00000000 08:07 4065366                    /usr/share/mime/mime.cache
7eff8402c000-7eff84039000 rw-s 00000000 00:05 17072167                   /SYSV00000000 (deleted)
7eff84039000-7eff8404e000 rw-s 00000000 00:05 17039398                   /SYSV00000000 (deleted)
7eff8404e000-7eff840a2000 r--p 00000000 08:07 4472975                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-M.ttf
7eff840a2000-7eff840ad000 r-xp 00000000 08:07 1839165                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7eff840ad000-7eff842ac000 ---p 0000b000 08:07 1839165                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7eff842ac000-7eff842ad000 r--p 0000a000 08:07 1839165                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7eff842ad000-7eff842ae000 rw-p 0000b000 08:07 1839165                    /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7eff842ae000-7eff8445e000 r-xp 00000000 08:07 3805123                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7eff8445e000-7eff8465d000 ---p 001b0000 08:07 3805123                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7eff8465d000-7eff84665000 r--p 001af000 08:07 3805123                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7eff84665000-7eff84667000 rw-p 001b7000 08:07 3805123                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3Aborted

**Comment by yeqibin** [comment]
重新输入ss-qt5后弹出error窗口：
Failed to communicate with previously running instance of Shadowsocks-Qt5 . It might already crashed.

**Comment by kingwpf** [comment]
我的也是哎，以前用的好好的啊，今天不能用了。。。。

**Comment by hocgin** [comment]
Me too

**Comment by Engine-Treasure** [comment]
Me too

**Comment by librehat** [comment]
#312
