### ISSUE TITLE
按延迟排序的时候，建议把超时的放到最后

### ISSUE THREAD

**Issue by chrisxvin** [shadowsocks/shadowsocks-qt5#322]
这样看起来更加直观。
现在的排序结果是把超时的都放在最前面了。

**Comment by librehat** [comment]
It sorts by latency (while the timeout one has a special negative value). :sob: I don't think I can easily make this change without breaking compatibility with old config. Sorry but I'll mark this as a "won't fix"

**Comment by Cheedoong** [comment]
One possible walk-around: adding `latency` it with INT_MAX if it is negative.

**Comment by librehat** [comment]
There are other negative values (error, for example)

**Comment by Slept-Warrior** [comment]
能不能在测试延迟回调之后更新控件的函数里判断 如果失败/超时则掉到队尾 什么的？

EN:How about some code in widget refresh after callback from "latency test", like "if it's error/timeout then send that row to bottom" or sth?
