### ISSUE TITLE
OS X installation instructions

### ISSUE THREAD

**Issue by pjrobertson** [shadowsocks/shadowsocks-qt5#324]
Can you please add the following markdown to a wiki page, I think it would be useful for the future (building on OS X)

------------

## OS X Build Requirements

* Xcode & Command Line Tools
* [Homebrew](https://brew.sh)

**Setup (run the following in Terminal):**

```
brew update
brew install qt5 libqrencode zbar botan
# link qmake
ln -s /usr/local/opt/qt5/bin/qmake /usr/local/bin/qmake
```

**Build & Install libQtShadowsocks**

Download the libQtShadowsocks code and build it using qmake with the following commands:

```
git clone https://github.com/shadowsocks/libQtShadowsocks.git 
cd libQtShadowsocks
qmake INSTALL_PREFIX=/usr/local
make all
make install
```

**Build shadowsocks-qt5**

Download the shadowsocks-qt5 source and build as normal using `qmake` then `make`
To create an Xcode project, use `qmake -spec macx-xcode`

**Comment by librehat** [comment]
I'll add OS X section. But please don't suggest people to use code from `master` branch as it's unstable and might includes API breaks.

**Comment by librehat** [comment]
https://github.com/shadowsocks/libQtShadowsocks/wiki/Compiling#building-on-mac-os-x

https://github.com/shadowsocks/shadowsocks-qt5/wiki/Compiling#mac-os-x
