### ISSUE TITLE
ss-qt5 needs an newer version of Qt5 than I have

### ISSUE THREAD

**Issue by umikachen** [shadowsocks/shadowsocks-qt5#327]
Hi, I updated ss-qt5 and libQtShadowsocks.so yesterday, and it seems the updates depend on Qt5.6 which is not available by the updating command 'sudo dnf update'(it says everything is in its newest version).

I'm using fedora23 x64. Can I update Qt without install it from source code? or can I downgrade the ss-qt5 using dnf?

Thanks in advance.

`ss-qt5: /lib64/libQt5Network.so.5: no version information available (required by ss-qt5)
ss-qt5: /lib64/libQt5DBus.so.5: no version information available (required by ss-qt5)
ss-qt5: /lib64/libQt5Gui.so.5: no version information available (required by ss-qt5)
ss-qt5: /lib64/libQt5Widgets.so.5: no version information available (required by ss-qt5)
ss-qt5: /lib64/libQt5Core.so.5: no version information available (required by ss-qt5)
ss-qt5: /lib64/libQt5Core.so.5: no version information available (required by ss-qt5)
ss-qt5: /lib64/libQt5Network.so.5: no version information available (required by /lib64/libQtShadowsocks.so.1)
ss-qt5: /lib64/libQt5Core.so.5: no version information available (required by /lib64/libQtShadowsocks.so.1)
ss-qt5: /lib64/libQt5Core.so.5: no version information available (required by /lib64/libQtShadowsocks.so.1)
ss-qt5: relocation error: /lib64/libQtShadowsocks.so.1: symbol qt_version_tag, version Qt_5.6 not defined in file libQt5Core.so.5 with link time reference
`

**Comment by librehat** [comment]
Qt 5.6 is released for Fedora 23 for a couple of weeks.

Try `sudo dnf upgrade --refresh`
