### ISSUE TITLE
想用扫描屏幕上的二维码来添加节点，可每次都是未找到二维码

### ISSUE THREAD

**Issue by lpssph** [shadowsocks/shadowsocks-qt5#328]
扫描屏幕上的二维码功能有问题吧，2.6.1和2.7都是这样的，不能使用。

 操作系统： win10 x64

注： shadowsocks-windows 3.0版本没这个问题.

**Comment by librehat** [comment]
试试用捕获器窗口扫

**Comment by lpssph** [comment]
捕获器窗口功能很好用，其他客户端扫不出来的用捕获器也能扫出来~
只是没有直接扫描屏幕来的轻便^_^

**Comment by librehat** [comment]
这个是zbar的问题，我也没办法解决。扫屏幕确实方便
