### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by PythonFu** [shadowsocks/shadowsocks-qt5#331]
界面给人焕然一新的感觉。

1、列表框每项宽度不能记忆，重启后又恢复。。强迫症不显示完全不能忍。
2、当已连接时，断开连接按钮应该常亮。。
3、当已连接一个节点时，不断开直接连接另外一个节点程序会报错然后崩溃

**Comment by librehat** [comment]
请忘记Shadowsocks-Windows的逻辑，ss-qt5的设计理念是不一样的。你可以同时连接多个shadowsocks（不同的本地端口）。连接和断开都是对应每个列表里面的连接，不是全局状态。

**Comment by PythonFu** [comment]
哦哦。那第一条应该可以改进下吧。。连接多个是自动负载均衡？

**Comment by librehat** [comment]
不是。
第一个已经有open的issue

**Comment by librehat** [comment]
第一个应该已经实现了的，你运行的是最新版本？
