### ISSUE TITLE
fedora 24编译安装 启动服务后连不上，防火墙已关闭

### ISSUE THREAD

**Issue by ant-sir** [shadowsocks/shadowsocks-qt5#334]
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 9999
Connecting www.google.com:443 from 127.0.0.1:47738
Connecting www.google.com:443 from 127.0.0.1:47742
Connecting www.baidu.com:80 from 127.0.0.1:47744
Connecting suggestion.baidu.com:80 from 127.0.0.1:47750
Connecting suggestion.baidu.com:80 from 127.0.0.1:47748
Connecting suggestion.baidu.com:80 from 127.0.0.1:47754
Connecting www.baidu.com:80 from 127.0.0.1:47758
Connecting www.baidu.com:80 from 127.0.0.1:47762
Connecting suggestion.baidu.com:80 from 127.0.0.1:47752
Connecting www.zgxiangxin.com:80 from 127.0.0.1:47766
Connecting suggestion.baidu.com:80 from 127.0.0.1:47756
Connecting ss1.bdstatic.com:443 from 127.0.0.1:47770
Connecting www.baidu.com:80 from 127.0.0.1:47760
Connecting ss1.bdstatic.com:443 from 127.0.0.1:47774
Connecting www.zgxiangxin.com:80 from 127.0.0.1:47764
Connecting www.zgxiangxin.com:80 from 127.0.0.1:47768
Connecting ss1.bdstatic.com:443 from 127.0.0.1:47772
Connecting www.google.com:443 from 127.0.0.1:47806
Connecting www.google.com:443 from 127.0.0.1:47810
Connecting www.google.com:443 from 127.0.0.1:47814
Connecting www.google.com:443 from 127.0.0.1:47818
Connecting www.google.com:80 from 127.0.0.1:47824
Connecting www.google.com:80 from 127.0.0.1:47822
Connecting clients4.google.com:443 from 127.0.0.1:47830
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 9999
Connecting clients2.google.com:80 from 127.0.0.1:47842
Connecting googleads.g.doubleclick.net:80 from 127.0.0.1:47846
Connecting googleads.g.doubleclick.net:80 from 127.0.0.1:47850
Connecting www.google.com:443 from 127.0.0.1:47854
Internet connectivity test failed. Please check the connection's profile and your firewall settings.

**Comment by librehat** [comment]
极有可能配置有误。

**Comment by nextair** [comment]
这样的配置文件，win上使用shadowsocks-csharp是可以的，没有任任问题，

但qt连接上后还是上不了google。

{
	"configs" : [
		{
			"remarks" : "",
			"server" : "xxxxxx",
			"server_port" : 8080,
			"password" : "xxxxx",
			"method" : "aes-256-cfb",
			"obfs" : "http_simple",
			"obfsparam" : "",
			"remarks_base64" : "",
			"tcp_over_udp" : false,
			"udp_over_tcp" : false,
			"protocol" : "verify_simple",
			"obfs_udp" : false,
			"enable" : true,
			"id" : "xx-xx-xx-xx-xx-xx-xx-xx-xx-xx...."
		}
	],
	"index" : 1,
	"random" : false,
	"global" : true,
	"enabled" : false,
	"shareOverLan" : true,
	"isDefault" : false,
	"localPort" : 8080,
	"pacUrl" : null,
	"useOnlinePac" : false,
	"reconnectTimes" : 0,
	"randomAlgorithm" : 0,
	"TTL" : 0,
	"proxyEnable" : false,
	"proxyType" : 0,
	"proxyHost" : "",
	"proxyPort" : 0,
	"proxyAuthUser" : "",
	"proxyAuthPass" : "",
	"autoban" : false
}

**Comment by librehat** [comment]
你使用的不是shadowsocks-windows吧？有些配置项看起来很奇怪。如果是SSR，ss-qt5不支持

**Comment by ant-sir** [comment]
对的，是SSR。如果要让ss-qt5支持，是要修改服务端吗？还是只改一下我上面配置文件的参数就可以

**Comment by ant-sir** [comment]
谢谢你的回答。是我搞混了。
