### ISSUE TITLE
Hello, I can't delete the first numeral 8 from the input field of server port.

### ISSUE THREAD

**Issue by lixiaodongsql** [shadowsocks/shadowsocks-qt5#335]
Hello, after I ran shadowsocks Qt 5 Windows 32 bits version 2.7.0 on Windows XP Service Pack 3, I clicked the connection menu on the editor of connection. And then I clicked sub-menu " Add ", I chose manual configuration. The default server port is 8388. I can delete 388 from the input field of server port. But I can't delete the first numeral 8 from the input field of server port. Could you please help me solve this problem. Thank you very much for your help. I really appreciate it.

**Comment by librehat** [comment]
Select the number and replace it, you can't clear that input field because of the validator.
