### ISSUE TITLE
ubuntu kylin 14.04  ss-qt5 Proxy SwitchySharp 最近每天都是一段时间占用cpu 100%

### ISSUE THREAD

**Issue by chenyangguang** [shadowsocks/shadowsocks-qt5#338]
系统ubuntu Kylin 14.04, 使用ss-qt5, 如果一直开proxy switchySharp插件的话, 这个进程会占用全部cpu. 元芳, 你怎么看?切换各个节点, 也是一样. Google Chome版本为Version 50.0.2661.102 (64-bit)

**Comment by librehat** [comment]
哪个进程？Chrome?

**Comment by chenyangguang** [comment]
对，top 查看时， 占用100%的进程是chrome， 但是kill掉这个进程之后， 发现只是Proxy SwitchySharp插件禁止了。而且有的时候还表现的不一样。
（1）比如有时候kill掉这个进程之后。 插件Proxy SwitchySharp插件禁止了， 接着翻不出去了。
（2）而有时候， 这个占比最高的进程kill掉之后， google+等还是可以继续浏览。
嗯～， 表示也是醉了（懵圈了）。这个系统开机只有ss-qt5这个代理服务, 也没有启动命令行 sslocal 模式。更没有没有开机启动这个服务。每次手动启动的。

**Comment by librehat** [comment]
占用CPU的不是ss-qt5，请汇报给Proxy SwitchySharp项目。
