### ISSUE TITLE
Unable to upload files with OTA enabled

### ISSUE THREAD

**Issue by yyssxx** [shadowsocks/shadowsocks-qt5#339]
感谢作者辛勤付出，ubuntu下使用中发现 shadowsocks-qt5只要勾选一次验证，（网页浏览，或视频都正常）唯独谷歌云端硬盘网页版就无法上传文件，关闭一次验证后正常，windows下用qt5试，问题依旧，又用shadowsocks 原版客户端试了下，无论是否勾选一次验证，均可上传。

**Comment by librehat** [comment]
同样的浏览器？

**Comment by yyssxx** [comment]
测试时Ubuntu下用的是chromium, win用chrome，没有其他浏览器。

**Comment by yyssxx** [comment]
服务端是shadowsocks-go1.1.5,支持OTA

**Comment by librehat** [comment]
这个问题感觉很诡异，你试试libev版客户端在Ubuntu下没问题？

**Comment by yyssxx** [comment]
使用libev版客户端命令行 -A 开启OTA，上传大文件没有问题。

**Comment by msxcms** [comment]
同样有此问题，发生在hangout传图的时候
报错为
Remote socket error: Unable to write

**Comment by librehat** [comment]
Issue will be tracked in shadowsocks/libQtShadowsocks#98

**Comment by librehat** [comment]
Fixed
