### ISSUE TITLE
qt-5无法登陆TCP server listen failed

### ISSUE THREAD

**Issue by Tangtry** [shadowsocks/shadowsocks-qt5#341]
linux新手，用的element os，配置shadowsocks qt-5的时候不能连接，log如下
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen failed.
不知是什么原因？
望大神请教～

**Comment by librehat** [comment]
检查本地端口是否被占用。

**Comment by Tangtry** [comment]
谢谢啦，之前确实不知道被什么占用了端口，重启就好了

**Comment by yaochx** [comment]
try this to find the port conflict
```
lsof -i | grep 1080
```

**Comment by my-vina** [comment]
1080端口被占用，心累！谢谢了。
