### ISSUE TITLE
Ubuntu 环境下可以跟服务器链接，但是无法访问google, youtube 等国外(https?)网站

### ISSUE THREAD

**Issue by QingfengYang** [shadowsocks/shadowsocks-qt5#342]
1. 同样的账号、配置用shadowsocks .net客户端是可以工作的，可以访问google，youtube等所有网站。
2. 在同一个局域网内，DNS配置同样，用shadowsocks-qt5则有以下问题
 a）shadowsocks-qt5显示可以跟服务器建立链接
 b）firefox配置socket5链接到shadowsocks-qt5可以访问baidu.com国内网站
 c）无法访问google等站点

qt5 日志：
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen at port 1080
Connecting 52.89.222.161:443 from 127.0.0.1:56490
Connecting 117.18.237.29:80 from 127.0.0.1:56494
Connecting 52.40.123.99:443 from 127.0.0.1:56498
Connecting 52.40.123.99:443 from 127.0.0.1:56502
Connecting 120.196.0.5:80 from 127.0.0.1:56510
Remote socket error: Connection timed out
Connecting 120.196.0.5:80 from 127.0.0.1:56542
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Remote socket error: Connection timed out
Connecting 120.196.0.5:80 from 127.0.0.1:56556
Remote socket error: Connection timed out
Connecting 120.196.0.5:80 from 127.0.0.1:56576

===================================================

是不是加密写法有问题，以上链接中显示跟服务器使用了部分80端口

**Comment by librehat** [comment]
80端口是目标服务器（不是shadowsocks服务器）

检查你的DNS配置

**Comment by theseawolves** [comment]
@librehat 你好 ，一样的问题，请教 DNS如何配置。或者能给出一个完整配置不？我是小白。。

**Comment by theseawolves** [comment]
还是有点不一样

1. 系统自动代理
2. file:///home/autoproxy.pac 
3. shadowsocks .net 帐号
4. 能连接上 ，延迟72毫秒 二维码信息：ss://YWVzLTI1Ni1jZmI6MjQzNzEyMDhASlAzLklTUy5URjo0NDM=

`
{
"server": "JP3.ISS.TF",
"server_port": 443,
"local_address": "127.0.0.1",
"local_port": 1080,
"password": "24371208",
"method": "aes-256-cfb",
"fast_open": true,
"workers": 1
}
`

> a）shadowsocks-qt5显示可以跟服务器建立链接 b）firefox配置socket5链接到shadowsocks-qt5可以访问baidu.com国内网站 c）无法访问google等站点

5. 日志 貌似都没有走代理？
```
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 1080
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 1080
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 1080
```

**Comment by theseawolves** [comment]
sorry 我把代理类型设置为 https ，就可以了 非常感谢
