### ISSUE TITLE
libbotan库能不能通过dnf安装

### ISSUE THREAD

**Issue by kuffz** [shadowsocks/shadowsocks-qt5#343]
在fedora 24 x64下面试了很多方法，都没有办法通过dnf安装botan库，是不是这条路走不通？
一定要下载rpm安装么？

**Comment by librehat** [comment]
I'm upgrading to F24 now. Will check soon.

**Comment by librehat** [comment]
`sudo dnf install botan` not libbotan

**Comment by kuffz** [comment]
thanks :)
