### ISSUE TITLE
Distribute as flatpak

### ISSUE THREAD

**Issue by librehat** [shadowsocks/shadowsocks-qt5#345]
Flatpak (formerly known as xdg-app) is a distribution-agnostic package format on Linux. This enables us to support potentially more Linux distributions without diving into their own self-host package system. 

However, Flatpak is not stable and mature enough to be used in production. Especially the Qt/KDE runtime is still WIP. This issue is open as a future plan. :)

**Comment by librehat** [comment]
Flatpak is not mature and widely supported yet. No resources for this

**Comment by jacknlliu** [comment]
I think it's time to reopen this issue, please see [flathub](https://flathub.org/apps/).

**Comment by librehat** [comment]
@jacknlliu The second point still stands, I don't have time for `flatpak` but any PRs are welcomed

**Comment by wsgalaxy** [comment]
@librehat Well , I would like to add a PR to flathub for shadowsocks-qt5, I think it is time to switch to flatpak for linux desktop applications.
我很乐意将shadowsocks-qt5打包发布到flathub
