### ISSUE TITLE
ss-qt5 can not set up 

### ISSUE THREAD

**Issue by fivestrong** [shadowsocks/shadowsocks-qt5#346]
I use archlinux for my desktop .today when i update the system with pacman -Syyu,after this ss-qt5 can not be set up anymore.And it came out errors like this
➜  ~ ss-qt5 
ss-qt5: /usr/lib/libQt5Core.so.5: version `Qt_5.7' not found (required by ss-qt5)
ss-qt5: /usr/lib/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/lib/libQtShadowsocks.so.1)

How can i fixed this problem?
And ibqtshadowsocks 1.9.0-2 has been installed.

➜  ~ yaourt shadowsocks
1 community/shadowsocks 2.8.2.20160112-1
    A lightweight tunnel proxy
2 community/shadowsocks-libev 2.4.7-1
    A lightweight secured socks5 proxy for embedded devices and low end boxes
3 archlinuxcn/libqtshadowsocks 1.9.0-2 [installed]
    A lightweight library for shadowsocks.
4 archlinuxcn/shadowsocks-qt5 2.7.0-2 [installed]
    A fast, reliable and cross-platform GUI fronted for Shadowsocks.
5 aur/libqtshadowsocks 1.9.0-2 [installed] (10) (1.34)
    A lightweight library for shadowsocks.
6 aur/shadowsocks-libev-ipv6first 2.4.6-1 (0) (0.00)
    A lightweight secured socks5 proxy for embedded devices and low end boxes (Server resolve 
    IPv6 first)
7 aur/shadowsocks-qt5 2.7.0-2 [installed] (14) (1.41)
    A fast, reliable and cross-platform GUI fronted for Shadowsocks.

**Comment by librehat** [comment]
Ask arch Linux maintainer

**Comment by ykelvis** [comment]
try `pacman -Syu` and then reboot.
