### ISSUE TITLE
在ubuntu14.04上运行，过一段时间会导致整个系统卡死

### ISSUE THREAD

**Issue by pngfi** [shadowsocks/shadowsocks-qt5#349]
我使用ubuntu 14.04, 按照教程的安装方法安装，之后使用二维码捕捉器从网站上捕捉到二维码，然后选中节点，点击connet，不久系统就会卡死。任何操作都没有用，只能强制重启。试过很多次，都会卡死。但是只运行，不点击connect就没有事。

**Comment by librehat** [comment]
听起来太魔幻了……

**Comment by zaimuhuoche** [comment]
也同样有遇到 。。。

**Comment by tmacww** [comment]
一样的遇到了，怎么解决的？

**Comment by pngfi** [comment]
在ubuntu16.04 上运行良好

**Comment by ShomyLiu** [comment]
同样遇到， 连接的时候，整个系统直接卡死， `ctrl + alt + f几`都进不去终端， 只能断电重启

**Comment by imesong** [comment]
我也遇到了同样的问题，之前用12.04 没有遇到过类似的问题。卡死的时候硬盘狂转，我的电脑配置 8G内存＋120ssd

**Comment by librehat** [comment]
12.04根本就不能运行ss-qt5

**Comment by yinzishao** [comment]
测试延迟的时候系统直接卡死，ubuntu14.04

**Comment by aqing1987** [comment]
ubuntu 16.04 下已经完成编译安装，但使用http://www.ishadowsocks.org/ 给的地址可以已经连接上，但web 还是连不上google，求破

**Comment by XiZepu** [comment]
![ss](http://7xoile.com1.z0.glb.clouddn.com/ss.png)

Ubuntu 14.04 出现这样

**Comment by cathemlin** [comment]
ubuntu 16.04 出现现实connected 但是网页google上不去

**Comment by liuxyc** [comment]
是不是有内存泄露

**Comment by imesong** [comment]
@cathemlin 我升级到16.04之后，一直没弄好呢

**Comment by yinzishao** [comment]
我的解决办法，不用客户端，直接用sslocal命令配置。

**Comment by jinfagang** [comment]
弱弱的问一句，ubuntu下怎么编译安装ss-qt5？clone了源码..and then？

**Comment by ShomyLiu** [comment]
14.04我没发现系统卡死的解决方法， 于是我就安装了16.04，用的很好 在2016年12月26日 09:32 ，JinTian写道： 弱弱的问一句，ubuntu下怎么编译安装ss-qt5？clone了源码..and then？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by visdark** [comment]
希望出一份详尽的Ubuntu安装使用教程 .  
安装完毕后 界面提示 已连接, 但是 google 还是未能打开.

**Comment by ShomyLiu** [comment]
font{
        line-height: 1.5;
    }


    如果延迟正常的话，ss在Ubuntu没有全局代理， 浏览器上网需要用插件修改代理就可以了。终端使用代理的话，我用的是 proxychains这个小软件



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    






    
        在2016年12月28日 14:48，
                
                        visdark
                        <notifications@github.com>
                    写道：
                
        
    


希望出一份详尽的Ubuntu安装使用教程 .
安装完毕后 界面提示 已连接, 但是 google 还是未能打开.

**Comment by district10** [comment]
自己笔记一下安装过程吧

**0. 我的环境*

```
$ uname -a
Linux win10 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue       
Ubuntu 16.04.1 LTS \n \l

$ uname -a
Linux win10 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ qmake -v
QMake version 3.0
Using Qt version 5.7.1 in /opt/Qt5.7.1/5.7/gcc_64/lib
```

**1. Qt5**

下载 <http://mirrors.ustc.edu.cn/qtproject/official_releases/qt/5.7/5.7.1/qt-opensource-linux-x64-5.7.1.run>（这是 USTC 的镜像），`chmod +x <这个 run 文件>`，再运行 `sudo ./<这个 run 文件>`。

**2. 确定你的 qmake 正确配置了**

qmake 会影响头文件的 include，uic/moc 的运行，etc。我之前总是安装失败就是
因为 qmake 的路径是 anaconda 里面那个。如果正确配置好了 qmake，应该是
这样的：

```
$ qmake -v
QMake version 3.0
Using Qt version 5.7.1 in /opt/Qt5.7.1/5.7/gcc_64/lib
```

**3. 安装依赖**

可以直接参考 repo 里面的 `.travis.yml` 文件。

```
sudo add-apt-repository ppa:hzwhuang/ss-qt5 -y && sudo apt-get -qq update
sudo apt-get install qt5-qmake qt5-default qtbase5-dev libbotan1.10-dev gcc-4.8 libqrencode-dev libzbar-dev libappindicator-dev libqtshadowsocks-dev
sudo apt-get install libbotan1.10-dev
sudo apt-get install libzbar-dev libzbarqt-dev
sudo apt-get install libappindicator-dev
```

（可能有问题，这是我命令历史里面的记录。）

**4. 编译**

```
mkdir build
cd build
qmake ..
make
```

然后就有了 `ss-qt5`。

**Comment by ShomyLiu** [comment]
font{
        line-height: 1.5;
    }


    如果是Ubuntu16.04版本及以上的话，直接加源安装没有问题，主要是14.04会卡死---



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    






    
        在2017年01月10日 12:56，
                
                        TANG ZhiXiong
                        <notifications@github.com>
                    写道：
                
        
    


自己笔记一下安装过程吧
*0. 我的环境
$ uname -a
Linux win10 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue        
Ubuntu 16.04.1 LTS \n \l

$ uname -a
Linux win10 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ qmake -v
QMake version 3.0
Using Qt version 5.7.1 in /opt/Qt5.7.1/5.7/gcc_64/lib

1. Qt5
下载 http://mirrors.ustc.edu.cn/qtproject/official_releases/qt/5.7/5.7.1/qt-opensource-linux-x64-5.7.1.run（这是 USTC 的镜像），chmod +x <这个 run 文件>，再运行 sudo ./<这个 run 文件>。
2. 确定你的 qmake 正确配置了
qmake 会影响头文件的 include，uic/moc 的运行，etc。我之前总是安装失败就是
因为 qmake 的路径是 anaconda 里面那个。如果正确配置好了 qmake，应该是
这样的：
$ qmake -v
QMake version 3.0
Using Qt version 5.7.1 in /opt/Qt5.7.1/5.7/gcc_64/lib

3. 安装依赖
可以直接参考 repo 里面的 .travis.yml 文件。
sudo add-apt-repository ppa:hzwhuang/ss-qt5 -y && sudo apt-get -qq update
sudo apt-get install qt5-qmake qt5-default qtbase5-dev libbotan1.10-dev gcc-4.8 libqrencode-dev libzbar-dev libappindicator-dev libqtshadowsocks-dev
sudo apt-get install libbotan1.10-dev
sudo apt-get install libzbar-dev libzbarqt-dev
sudo apt-get install libappindicator-dev

（可能有问题，这是我命令历史里面的记录。）
4. 编译
mkdir build
cd build
qmake ..
make

然后就有了 ss-qt5。

**Comment by wujiachen987** [comment]
我ubuntu下16.04 成功安装ss-Qt5 但是，识别二维码之后显示已链接，但是仍然不能访问外网

**Comment by librehat** [comment]
无法重现。版本迭代更新好几次了，如果依然出现此问题请另开新issue
