### ISSUE TITLE
在基于xUbuntu16.04的系统上似乎不能运行

### ISSUE THREAD

**Issue by JerryLiao26** [shadowsocks/shadowsocks-qt5#350]
每次打开都会闪退，升级系统前在14.04上是可以运行的

**Comment by JerryLiao26** [comment]
可能也是libbotan的问题，卸载后重新安装libqtshadowsocks时提示不能安装libbotan

**Comment by librehat** [comment]
卸载重新用apt安装，把结果贴出来看看？

**Comment by JerryLiao26** [comment]
@librehat 
![image](https://cloud.githubusercontent.com/assets/8209341/16573283/ac6720b6-42a4-11e6-90e1-26b17ad9246a.png)

**Comment by librehat** [comment]
What do you get if you run `apt-cache search libbotan`?

**Comment by JerryLiao26** [comment]
@librehat It would be two results
![image](https://cloud.githubusercontent.com/assets/8209341/16720049/c16188e8-4764-11e6-82c0-ecc34e2941da.png)

**Comment by librehat** [comment]
Ubuntu神奇的依赖关系觉得libbotan-1.10-1和libbotan-1.10-0不一样…………我也是醉了。在新版本发布之前，只能自行编译了。或者忽略依赖关系强行安装。
