### ISSUE TITLE
在ubuntu14.04上连接补上

### ISSUE THREAD

**Issue by richardweiu** [shadowsocks/shadowsocks-qt5#352]
账号没有问题，可以连接上，而且我的手机可以登录上，但是电脑没有办法，用的shadowsocks-qt5，chrome

This site can’t be reached

www.google.com.hk took too long to respond.
Try:
Reloading the page
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

**Comment by librehat** [comment]
Logs in ss-qt5?

**Comment by fengxuanyang** [comment]
我也有同样的问题   
账号没有问题，可以连接上， 但是不能翻墙

**Comment by luohy15** [comment]
我也是这个问题,登录上了,latency也正常,但是不能用,是不是要在chrome里进行一些设置?

**Comment by librehat** [comment]
@luohy15 https://github.com/shadowsocks/shadowsocks-qt5/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E7%9A%84%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE

**Comment by fengxuanyang** [comment]
我的已解决，是因为浏览器代理问题
