### ISSUE TITLE
希望可以自定义流量显示单位

### ISSUE THREAD

**Issue by ragnaroks** [shadowsocks/shadowsocks-qt5#353]
默认好像是自动换算,但是希望能自定义为M或K

**Comment by librehat** [comment]
呃，自动换算难道不好么……为何会希望固定单位？排序并不受影响的我记得

**Comment by ragnaroks** [comment]
目前看来好像在G级上,10G和10.99999G显示出来是一摸一样的,我这边的ss服务是按字节算钱的...

**Comment by ragnaroks** [comment]
1Mbyte/2元,但是每天有免费50M,所以希望能看到比较精准的流量单位,以便控制支出

这个确实很贵,但是是CN2独立专线,我联通接上后玩国内网游ping没有高于15ms的

**Comment by librehat** [comment]
现在的实现确实有点蠢，没有小数位。增加两位小数如何？ 💭

**Comment by ragnaroks** [comment]
可以

**Comment by librehat** [comment]
还没修复呢，别关

**Comment by nanpuyue** [comment]
啥，按字节算钱，我真的没听错？
