### ISSUE TITLE
电脑进入屏幕保护程序一段时间后唤醒会导致客户端一并执行测试延迟的命令

### ISSUE THREAD

**Issue by fujita-nozomi** [shadowsocks/shadowsocks-qt5#355]
不知道是不是这样 反正我开着这个玩意儿 连接SS服务器 然后放置了一大段时间
之后回来发现电脑变卡了 怎么查也查不出什么 然后发现QT5客户端不停的发送测试延迟的命令
我怀疑有可能是休眠时无法执行 然后等到休眠后一并执行的后果（堆积太多）

please fix it

**Comment by librehat** [comment]
客户端根本没有timer loop去测试延迟。
