### ISSUE TITLE
两天没用,SS连接服务器提示,无法启动XX

### ISSUE THREAD

**Issue by kelln** [shadowsocks/shadowsocks-qt5#357]
测试服务器延迟正常，点击连接，提示无法启动连接，
报错日志如下提示
TCP server listen failed

**Comment by paulpig** [comment]
你解决了这个问题了吗？

**Comment by paulpig** [comment]
这个问题好像我也遇到啦，将1080端口的进程关闭。重新启动shadowsocks-qt5就可以啦。

**Comment by librehat** [comment]
检查自己的本地端口
