### ISSUE TITLE
Freeze while export configs

### ISSUE THREAD

**Issue by xxxifan** [shadowsocks/shadowsocks-qt5#360]
when click export as gui-config.json or save QR code as image file, the whole application going to freeze and operate failed.

**Comment by librehat** [comment]
CNR. What is your OS?

**Comment by xxxifan** [comment]
archlinux with gnome 3

**Comment by librehat** [comment]
CNR. Fedora 24 with GNOME 3.

**Comment by lyerox** [comment]
why closed?

**Comment by xxxifan** [comment]
I don't know, all three of my PCs having this issue(GNOME 3 + Archlinux)
