### ISSUE TITLE
希望能在右键菜单里多添加一些功能

### ISSUE THREAD

**Issue by ZenFX** [shadowsocks/shadowsocks-qt5#364]
您好，现在版本的右键菜单只有一个恢复和退出功能，希望能在右键菜单里多添加一些功能，比如切换服务器、查看日志什么的，这样就不用每次都打开主界面进行操作了。

**Comment by ky0ncheng** [comment]
希望加入對 fast-open 的支持

**Comment by librehat** [comment]
这个问题之前说明过，为了兼容不同的桌面环境，托盘图标的功能是非常有限的
