### ISSUE TITLE
ubuntu 16 连接上无法使用

### ISSUE THREAD

**Issue by jackigal** [shadowsocks/shadowsocks-qt5#365]
连接上了， 浏览器的代理也设置了， 端口是对的， 和本地服务器类型也是一致的， 但是访问还是不行， 怎么解？
日志是这样的：
Connecting google.com:80 from 127.0.0.1:57822
Connecting music.163.com:80 from 127.0.0.1:57828
Connecting wp.mail.qq.com:443 from 127.0.0.1:57834
Connecting www.google-analytics.com:443 from 127.0.0.1:57844
Connecting api.github.com:443 from 127.0.0.1:57846

**Comment by librehat** [comment]
开debug选项再看看日志？

**Comment by LeviHsia** [comment]
同样问题，ubuntu 1604

我的debug模式下日志如下：

Listen UDP socket state changed to QAbstractSocket::ClosingState 
Listen UDP socket state changed to QAbstractSocket::UnconnectedState 
Stopped.
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen at port 1080

**Comment by sumset** [comment]
软件： shadowsocks-qt5  chrome 浏览器。
问题：同一楼一样连接不上。反复确认，反复修改http, sock5等均无效。
解决：加密方式 ( Encryption Method )之后一行， One-time authentication 不要勾选。不要勾选。不要勾选。（好像默认就是不勾选的）。不要勾选，其他正常配置。搞定。
感谢：感谢二楼开debug选项，我顺手就把 One-time authentication 去掉勾选，搞定。

**Comment by aqing1987** [comment]
xp 下只要配置主机就可以上网 firefox 不用配置就可以上
ubuntu 16.04 下配置了主机，firefox 配置不配置都上不了

debug info
=============================================
Stopped.
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen at port 1080
Connecting 93.46.8.89:80 from 127.0.0.1:56384
=============================================

ubuntu16.04 下就是用不了哇 One-time authentication 不要勾选也不行。

**Comment by librehat** [comment]
Windows客户端会设置系统代理，请自己检查代理设置是否正确。

**Comment by dengxixi** [comment]
@sumset 怎么开debug选项。。。。

**Comment by isofun** [comment]
@librehat 怎么开debug。。。代理我检查过了啊

**Comment by LogicJake** [comment]
神了，我把One-time authentication去掉就完事了
