### ISSUE TITLE
wiki installation改进建议

### ISSUE THREAD

**Issue by choldrim** [shadowsocks/shadowsocks-qt5#370]
>可以尝试安装Ubuntu PPA源的deb包，如果不行，请自行编译（dpkg-buildpackage -uc -us -b），在上级目录中将会生成shadowsocks-qt5的deb包，通过sudo dpkg -i来安装。

>注意：你可能需要安装好的依赖关系：sudo apt-get install qt5-qmake qtbase5-dev libqrencode-dev libqtshadowsocks-dev libappindicator-dev libzbar-dev libbotan1.10-dev

可否补充两点：
1. 因为debian没有`add-apt-repository`命令，想手动添加源到列表不知道源的具体dist、components是什么，如果能补充直接的源地址会更好一些吧
 `deb http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu vivid main`
2. 依赖安装可以添加个指引建议，如：https://packages.debian.org/jessie/libbotan-1.10-0

**Comment by librehat** [comment]
不同Debian版本对应的Ubuntu也不一样吧，这些在网上Google一下就找到了，没必要在项目wiki里加上太多非项目相关的内容。维护起来也是个麻烦
