### ISSUE TITLE
ubuntu16.04 关闭了防火墙后还是显示防火墙没有关闭

### ISSUE THREAD

**Issue by MarkWh1te** [shadowsocks/shadowsocks-qt5#372]
ss log:
Internet connectivity test failed. Please check the connection's profile and your firewall settings.

(env) mark@redqueen:~/personal$ sudo iptables -L
[sudo] password for mark: 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination  

(env) mark@redqueen:~/personal$ sudo ufw status verbose
Status: inactive

**Comment by librehat** [comment]
不一定是防火墙，这个也同时检查密码和加密方式，你可能配置有误。
