### ISSUE TITLE
linux版本打开就闪退，系统也没有托盘

### ISSUE THREAD

**Issue by ColeHou** [shadowsocks/shadowsocks-qt5#377]
不好意思，不是很会用github，就是打开闪退，然后托盘也没有图标，系统是galliumOS，基于xubuntu16.04。
无法与先前运行的Shadowsocks-Qt5实例（PID: 4634）通讯。可能已经崩溃了。

~$ apt-cache search libbotan
libbotan-1.10-1 - multiplatform crypto library
libbotan1.10-dev - multiplatform crypto library (development

~$ echo $XDG_CURRENT_DESKTOP
XFCE

**Comment by TiSongWen** [comment]
我用的是 ubuntu ，暂时没有出现这个问题。

**Comment by guoyan1983** [comment]
@TiSongWen @ColeHou 用ubuntu，同样崩溃。

**Comment by jp1017** [comment]
>Linux jp-INST 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

我的ubuntu16.04，,不崩溃，但是无法上网，chrome设置了ss上网了，还有别的配置吗？win10正常使用的

**Comment by jp1017** [comment]
接上一条，无心插柳，哈哈 :smile: 上面的 https://github.com/shadowsocks/shadowsocks-qt5/issues/63 正好解决了我的问题，之前设置的时https，设置为socket5就ok了，感谢！

世界很大，感谢有你！

**Comment by librehat** [comment]
@ColeHou 从终端启动 `ss-qt5` 有什么错误信息吗？

**Comment by wjs876046992** [comment]
I have the same problem because of i config a sever use `aes-256-cfb`.
