### ISSUE TITLE
GUI can't display 'delete' button properly

### ISSUE THREAD

**Issue by weehowe-z** [shadowsocks/shadowsocks-qt5#380]
Hi, `delete` button doesn't display properly on my laptop like the following image.

- Distribution `archlinux  4.7.2-1-ARCH`
- Desktop `gnome3`

![s](http://o6nrk1z84.bkt.clouddn.com/ssqt5-bug.jpg)

**Comment by librehat** [comment]
It's very likely your icon theme's problem. Try using different icon theme (with more complete set)
