### ISSUE TITLE
连接正常，代理也设置了可还是翻不了墙

### ISSUE THREAD

**Issue by clayclayclay** [shadowsocks/shadowsocks-qt5#386]

**Comment by clayclayclay** [comment]
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
日志上还报了这个错，可我设置的就是SOCKS5

**Comment by librehat** [comment]
这个报错指的是你用的浏览器（或者被代理的软件）选用的代理方式不是SOCKS5，注意如果可以填HTTP都要留空，只留SOCKS5，搞不清楚的话你把代理类型换成HTTP得了

**Comment by salamander-mh** [comment]
我也碰到了这个问题，把代理方式都改成https就好了
