### ISSUE TITLE
"Local Address" and "Local Port" are left empty by default for items imported from json

### ISSUE THREAD

**Issue by Karia-algo** [shadowsocks/shadowsocks-qt5#387]
"The connection's profile is invalid" is prompted. Connection can not be established.
Would be better to set 127.0.0.1:1080 as default or be able to customize.
Really annoying to set each connection respectively : )

**Comment by librehat** [comment]
What kind of json config? Is it from shadowsocks-libev or shadowsocks for windows?

**Comment by Karia-algo** [comment]
@librehat It's downloaded from my ss provider, like this (I mask something) :
<pre>
{
    "configs": [
        {
            "server": "xxx.xxx.net",
            "server_port": "11111",
            "local_port": 1080,
            "password": "xxxxxxxxxxxxxxx",
            "method": "aes-256-cfb"
        },
        {
            "server": "xxx.xxx.net",
            "server_port": "11111",
            "local_port": 1080,
            "password": "xxxxxxxxxxxxxxx",
            "method": "aes-256-cfb"
        }
    ],
    "localPort": 1080,
    "index": 0,
    "global": false,
    "enabled": true,
    "isDefault": false
}
</pre>

So this file varies between different implementations? This is the only gui-config.json file provided by my ss provider and it notes that this is for "Windows Client". 
I ignore it because they share the same filename "gui-config.json".

**Comment by librehat** [comment]
Yes this is for "Shadowsocks for Windows" (C#). I'll take a look later

**Comment by Karia-algo** [comment]
Solved
