### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by onedou** [shadowsocks/shadowsocks-qt5#390]
make[1]: Entering directory '/home/big/shadowsocks-qt5'
install -m 755 -p /home/big/shadowsocks-qt5/shadowsocks-qt5.desktop /home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/share/applications/
strip /home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/share/applications/shadowsocks-qt5.desktop
strip:/home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/share/applications/shadowsocks-qt5.desktop: 不可识别的文件格式
Makefile:689: recipe for target 'install_desktop' failed
make[1]: [install_desktop] Error 1 (ignored)
install -m 755 -p /home/big/shadowsocks-qt5/src/icons/shadowsocks-qt5.png /home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/share/icons/hicolor/512x512/apps/
strip /home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/share/icons/hicolor/512x512/apps/shadowsocks-qt5.png
strip:/home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/share/icons/hicolor/512x512/apps/shadowsocks-qt5.png: 不可识别的文件格式
Makefile:699: recipe for target 'install_ssicon' failed
make[1]: [install_ssicon] Error 1 (ignored)
install -m 755 -p "ss-qt5" "/home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/bin/ss-qt5"
strip "/home/big/shadowsocks-qt5/debian/shadowsocks-qt5/usr/bin/ss-qt5"
make[1]: Leaving directory '/home/big/shadowsocks-qt5'
   dh_installdocs -O--parallel
/home/big/shadowsocks-qt5/debian/docs: 1: /home/big/shadowsocks-qt5/debian/docs: README.md: not found
dh_installdocs: problem reading debian/docs:
debian/rules:6: recipe for target 'binary' failed
make: **\* [binary] Error 127
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

**Comment by librehat** [comment]
什么系统环境？

**Comment by onedou** [comment]
debian 8 虚拟机 @librehat

**Comment by librehat** [comment]
估计你没有安装xdg-desktop， libpng什么的，看起来是一些桌面环境的组件缺失。
