### ISSUE TITLE
Ubuntu16 loacal socks5

### ISSUE THREAD

**Issue by UchihaJay** [shadowsocks/shadowsocks-qt5#397]
https is ok

 log:
`Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Local socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Listen UDP socket state changed to QAbstractSocket::ClosingState 
Listen UDP socket state changed to QAbstractSocket::UnconnectedState 
Stopped.
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen at port 1080
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.`

**Comment by librehat** [comment]
Your application must set proxy type to SOCKS5 and leave HTTP(S) proxy blank

**Comment by shenmijiabing** [comment]
haha. thanks, I solve this problem. Leave HTTP(S) proxy blank and change browser to chrome. It works well now.
