### ISSUE TITLE
CentOS6.8 yum 安装shadowsocks-qt5 缺少依赖

### ISSUE THREAD

**Issue by EternityYali** [shadowsocks/shadowsocks-qt5#399]
系统已配置相应系统版本的epel-6，仍然无法找到依赖。
error：Package: shadowsocks-qt5-0.6.0-5-el6.x86_64(librehat-shadowsocks)
                 Requires: libshadowsocks.so.l()(64bit)

**Comment by librehat** [comment]
It doesn't support RHEL 6
