### ISSUE TITLE
Ubuntu 16.04启动之后无法使用

### ISSUE THREAD

**Issue by GoingMyWay** [shadowsocks/shadowsocks-qt5#402]
我在Windows下可以使用，但是在Ubuntu 16.04下连接了VPN之后发现无法翻墙？是不是shadowsocks-qt5不支持ubuntu 16.04?

**Comment by jp1017** [comment]
我的16.04, 正常使用啊，socks5模式

**Comment by shadowmaner** [comment]
我的跟你也是一样16.04。测试正常，但是打不开google。

**Comment by alonepig** [comment]
火狐的配置选择手动设置代理，并勾选远程DNS。
