### ISSUE TITLE
An invalid socket connection was rejected,Please make sure the connection type is SOCKS5

### ISSUE THREAD

**Issue by 1194117884** [shadowsocks/shadowsocks-qt5#404]
Ubuntu 16.04LTS
shadowsocks-Qt5
Network proxy in Ubuntu system

issues:
    An invalid socket connection was rejected,Please make sure the connection type is SOCKS5!
see the image!

![screenshot from 2016-11-11 14-52-57](https://cloud.githubusercontent.com/assets/12094568/20207606/6ae6c526-a823-11e6-8c19-de10641e7a08.png)

**Comment by 1194117884** [comment]
it work well when i change to HTTPS !

**Comment by librehat** [comment]
The browser has a different proxy settings.

**Comment by 1194117884** [comment]
That's it! when i change to Chromium,it can be working!  so ,what i need is to find the setting of firefox,tks alot.
