### ISSUE TITLE
ubuntu无法从源下载安装

### ISSUE THREAD

**Issue by zhoudayang** [shadowsocks/shadowsocks-qt5#405]
如题

**Comment by rjf611** [comment]
Me too

**Comment by feerung** [comment]
add-apt-repository ppa:hzwhuang/ss-qt5
无法添加 PPA：“"Error reading https://launchpad.net/api/1.0/~hzwhuang/+archive/ss-qt5: (7, 'Failed to connect to launchpad.net port 443: \\xe8\\xbf\\x9e\\xe6\\x8e\\xa5\\xe8\\xb6\\x85\\xe6\\x97\\xb6')"”。

**Comment by twiceyuan** [comment]
我是添加可以，update 就出错了

**Comment by sndnvaps** [comment]
我是手动安装的，到源地址上面下载相应的三个deb文件，再安装。

**Comment by librehat** [comment]
Seems like China network issue
