### ISSUE TITLE
Unable to upload large files with ota enabled

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-qt5#409]
Server:
debian 8 with shadowsocks-libev v2.5.6 with OTA compatibility mode (accept both OTA or NON-OTA traffic)

Client:
fedora 24 with Shadowsocks-Qt5
if OTA enabled, uploading files larger than approximately 1MB will fail while browsing/downloading are normal.
Disabling enable OTA will fix this.

**Comment by librehat** [comment]
I'll take a look when I have more free time. Duplicates #339
