### ISSUE TITLE
CentOs6.8无法完成安装

### ISSUE THREAD

**Issue by BambooOs** [shadowsocks/shadowsocks-qt5#413]
在安装的过程中出现了如下的错误信息：
Error: Package: shadowsocks-qt5-0.6.0-5.el6.i686 (librehat-shadowsocks)
Requires: libshadowsocks.so.1
使用的操作系统是CentOs6.8，已经安装了图形化界面，相关源都已经按照提示完成，在最后安装的时候出现了以上的问题。

**Comment by sndnvaps** [comment]
你需要安装这个 libshadowsocks

**Comment by librehat** [comment]
RHEL/CentOS 6 not supported
