### ISSUE TITLE
为什么我安装、添加都成功了，但是用Firefox还是上不了google？

### ISSUE THREAD

**Issue by Jiedy** [shadowsocks/shadowsocks-qt5#414]
就按照Wiki那里的来的啊，一步一步很顺利，但是到了浏览器就跟没用ss一样的，是哪里还需要设置吗？
(这个ss地址我的手机，pc上面都可以正常使用的)
![jieping](https://cloud.githubusercontent.com/assets/17180935/20721209/057b7578-b69d-11e6-9b8f-6a27f769bd2c.png)

**Comment by sndnvaps** [comment]
firefox上面需要用类似proxy的 插件才行啊。。 
设置走代理

**Comment by Jiedy** [comment]
@sndnvaps 嗯  好的 谢谢
