### ISSUE TITLE
Qt5显示链接成功但是却无法打开google

### ISSUE THREAD

**Issue by ForgetV** [shadowsocks/shadowsocks-qt5#415]
Ubuntu 16.04 LTS 上安装qt5安装成功，能够打开，配置端口，可以可测速，但是连接成功之后浏览器无法打开google，求助

**Comment by ForgetV** [comment]
![2016-12-07 00-35-49](https://cloud.githubusercontent.com/assets/12705926/20934203/531616bc-bc15-11e6-9442-8da3a9f64d96.png)

**Comment by ForgetV** [comment]
提示连接了，但是就是无法打开google

**Comment by marvelAgent** [comment]
遇到同样的问题，我的是centos511下，请问你解决了没?

**Comment by librehat** [comment]
Set proxy in browser
