### ISSUE TITLE
延迟测试的报错提示框刷屏

### ISSUE THREAD

**Issue by sausager** [shadowsocks/shadowsocks-qt5#416]
按照文档指示安装完毕后，连上SS帐号一旦点击延迟测试，1-2分钟内就会被“延迟测试错误”的提示框刷屏，消退之后就没事了，这是BUG吗？完全不懂是怎麼一回事。
Debain 8.5
Shadowsocks-Qt5 Version 2.7.0
Using libQtShadowsocks 1.9.0
Using Botan 1.10.8

还有libqtshadowsocks-dev在Debain下需要单独编译安装，希望文档里把libqtshadowsocks-dev的安装事项单独说明一下。

**Comment by librehat** [comment]
说明你的连接十有八九无法使用。
