### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by UnsGentoals** [shadowsocks/shadowsocks-qt5#419]
QThread[11121]: segfault at 7f23ffdd5af0 ip 00007f23ffdd5af0 sp 00007f23d583c438 error 15 in libstdc++.so.6.0.19[7f23ffdd3000+8000]
3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by librehat** [comment]
Can you install debug info and run it with gdb?

**Comment by zixia** [comment]
I have the same issue, crash about twice a day.

```shell
[130789.747305] ss-qt5[5577]: segfault at c0000005 ip 00000000c0000005 sp 00007ffc188ec788 error 14 in ss-qt5[5591d0605000+77000]
```

**Comment by UnsGentoals** [comment]
just update your system ,will fix this.
:)
