### ISSUE TITLE
开发者能编译一个2.8.0的Windows版吗？谢谢

### ISSUE THREAD

**Issue by redfrog999** [shadowsocks/shadowsocks-qt5#422]
如题，一直用SS-QT5，麻烦编译一个Windows版，非常感谢。

**Comment by librehat** [comment]
I'll do so when I have more spare time

**Comment by redfrog999** [comment]
好的，感謝你的付出。

**Comment by weehowe-z** [comment]
@redfrog999
Windows还有一个csharp的版本也可以用吧。
[https://github.com/shadowsocks/shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows)

**Comment by testcaoy7** [comment]
@librehat Please add the latest Obfs feature to ss-qt5 and release 2.9.0 ^_^

**Comment by abcfy2** [comment]
@weehowe-z 
那个C#版本对.net的版本要求比较高，win10自带的.net是4.5的，都不满足最低依赖。

**Comment by sndnvaps** [comment]
难道是用 .net 4.6

**Comment by abcfy2** [comment]
对的，windows版本用的是.net 4.6.2，比win10预装的.net版本都高，使用上就不是特别方便，不如qt版本开箱即用

**Comment by librehat** [comment]
@testcaoy7 I have many things to tend to, so I won't be able to implement obfs in Qt implementation anytime soon.

**Comment by sndnvaps** [comment]
it's better to use <strong>Travis-ci.org</strong> to release the app
http://stackoverflow.com/questions/28174883/travis-ci-deploy-jar-to-github-master
https://docs.travis-ci.com/user/deployment/releases/

**Comment by librehat** [comment]
The building process is very bad on Windows at this moment. We probably need to get rid of zbar before the automation.

**Comment by librehat** [comment]
I've uploaded pre-built binary for 64-bit Windows. 32-bit Windows is dropped from target platform from now on.
