### ISSUE TITLE
Listen UDP port failed in QtCreatorVC5.7 Win10 

### ISSUE THREAD

**Issue by jefferyship** [shadowsocks/shadowsocks-qt5#425]
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
open socket:[127.0.0.1:1080]
is http proxy:
false
Listen local tcp port successful.
Listen local udp port failed

 listen_ret = tcpServer->listen(
                    getLocalAddr(),
                    profile.http_proxy ? 0 : profile.local_port);
        if (listen_ret) {
            emit info("Listen local tcp port successful.");
            listen_ret = udpRelay->listen(getLocalAddr(), profile.local_port);
            if(listen_ret){
                emit info("Listen local udp port successful");
            }else{
                emit info("Listen local udp port failed");
            }

**Comment by jefferyship** [comment]
shadowsocks-qt5-2.8.0
libQtShadowsocks-1.10.0

**Comment by jefferyship** [comment]
bool UdpRelay::listen(const QHostAddress& addr, quint16 port)
{
    qDebug()<<"listen udp port 7755 new ";
    QUdpSocket *listenSocketNew;
    listenSocketNew = new QUdpSocket();
    bool rt=  listenSocketNew->bind(7755);
    qDebug()<<"listen udp port 7755 bind end"<<rt;
    listenSocketNew->close();
    return true;
}

listen udp port 7755
listen udp port 7755 new 
listen udp port 7755 bind end false
Listen UDP port result: false

**Comment by librehat** [comment]
Your port might has been used already.
You probably want to set flags for `BindMode` in `bind()`: http://doc.qt.io/qt-5/qabstractsocket.html#BindFlag-enum
