### ISSUE TITLE
ss-qt5 crashed after  a while and there is no /tmp/qic_** file at all!

### ISSUE THREAD

**Issue by jinfagang** [shadowsocks/shadowsocks-qt5#426]
README.md has a statement of this problem, but I cannot find expected file as it says, and when I type ss-qt5 to run it again, it says another progress already running, so how can I fix this problem avoid restart my Ubuntu16.04 system?

**Comment by librehat** [comment]
You can just run it again after it complains about the existing process. It should remove the `qic_*` file automatically on the second run
