### ISSUE TITLE
使用普通用启动就卡死，debian 系统，需要授予什么权限，

### ISSUE THREAD

**Issue by xingxing9688** [shadowsocks/shadowsocks-qt5#431]
我之前使用debian 也是普通用户，但是权限是一样的是ok的额，现在使用这个用普通用户启动就卡死是什么原因，需要修改那些权限

**Comment by librehat** [comment]
Try removing `.config/shadowsocks-qt5` ? (make a backup)

**Comment by xingxing9688** [comment]
谢谢，我已经把root 用户下的配置cp 到普通用户下修改属主解决了。谢谢！
