### ISSUE TITLE
请问有计划支援Shadowsocks-libev的obfs混淆吗？

### ISSUE THREAD

**Issue by XiDeAssassin** [shadowsocks/shadowsocks-qt5#433]

**Comment by librehat** [comment]
Pull requests to libQtShadowsocks are welcome. I don't have much time recently but otherwise I'll be glad to add support for it.

**Comment by librehat** [comment]
As for the new draft, it seems we're going to have a plugin system, which no longer changes the core protocol. Hence, this request is no longer valid. I'll keep watching the new proposals.
