### ISSUE TITLE
ss-qt5 crashes with Botan::Exception with Botan-2.0

### ISSUE THREAD

**Issue by Hacksign** [shadowsocks/shadowsocks-qt5#435]
```
terminate called after throwing an instance of 'Botan::Exception'
  what():  False assertion 'The nonce is fresh for this message' (expression m_fresh_nonce) in get @src/lib/filters/cipher_filter.cpp:49
fish: 'ss-qt5' terminated by signal SIGABRT (Abort)
```
This exception happens as long as any traffic go throw ss-qt5 listening port, with any type of proxy (socks5 or http).

**Comment by librehat** [comment]
https://github.com/shadowsocks/libQtShadowsocks/issues/104

**Comment by shilkazx** [comment]
Same fault occurred after update shadowsocks and botan(from 1.10 to 1.11) on Archlinux x64.

**Comment by Hacksign** [comment]
The dependency of Botan-1.11 has been changed to Botan-1.10 on Archlinux. Arch user can remove shadowsocks-qt5 and install it again. Just for everyone information.

**Comment by librehat** [comment]
It has been fixed now. You need botan-2 >= 2.2.0

**Comment by shilkazx** [comment]
Good job guys! But I have migrated to CLI alternative several month ago.
Thanks  for you reply and bug fix.

Best wishes,
