### ISSUE TITLE
更新 wiki

### ISSUE THREAD

**Issue by ykelvis** [shadowsocks/shadowsocks-qt5#436]
shadowsocks-qt5 / libqtshadowsocks 都已经进了 Arch 官方源，wiki 可以更新一下啦

https://www.archlinux.org/packages/community/x86_64/shadowsocks-qt5/

**Comment by Hacksign** [comment]
别更新, 目前community源里面的ss-qt5的以来有问题, Botan在使用aes-256-cfb的算法时会崩溃, 导致ss-qt5无法使用.

**Comment by ykelvis** [comment]
🌚然而aur和archcn都已经删了，不更新也并不会有任何帮助。

**Comment by JackWzh** [comment]
话说为什么aur删了。。重装系统发现没有源了。。

**Comment by librehat** [comment]
@Hacksign It seems Arch is using unstable Botan 1.11, which is not tested.

**Comment by ykelvis** [comment]
@JackWzh aur包进community的时候会直接被TU删掉

**Comment by xxxifan** [comment]
昨天手贱更新了，怪不得一开就崩溃。命令行提示Could not find any algorithm named "RC2/CFB"

**Comment by librehat** [comment]
Wiki page updated
