### ISSUE TITLE
I can't setting my chrome proxy..ubuntu16.04

### ISSUE THREAD

**Issue by X1n9** [shadowsocks/shadowsocks-qt5#445]
![image](https://cloud.githubusercontent.com/assets/21193133/22619128/7012ca5c-eb28-11e6-9253-fa4ec8d290b2.png)
OW

**Comment by librehat** [comment]
Google and help yourself

**Comment by smileqingyuan** [comment]
你解决了吗？我的也是连接正确但翻不了墙

**Comment by li-zhenyu** [comment]
搞笑吗，不能翻墙还怎么google，拽英文了不起哦
