### ISSUE TITLE
connect and cant reach google

### ISSUE THREAD

**Issue by ljxu** [shadowsocks/shadowsocks-qt5#446]
![miaoss](https://cloud.githubusercontent.com/assets/13727729/22623731/ae5c2a52-eb9f-11e6-88d7-d5c3dbd0c4ae.png)
![miaossset](https://cloud.githubusercontent.com/assets/13727729/22623735/b59c09c2-eb9f-11e6-9168-0ec9b2d89634.png)

**Comment by librehat** [comment]
Please set your browser's proxy

**Comment by Nesh108** [comment]
@librehat Sorry to reply to this but I have the exact same problem.

My servers work fine (I have many different devices connected to them) but I can't seem to be able to connect my browsers.

If I ping `google` everything works but neither Firefox not Chrome work.

For FF, I just use the Network preferences tab and set a manual SOCK5 proxy to `localhost` with post `1080`, where the local server is serving. For Chrome, I am using `Proxy SwitchyOmega`, same settings, still nothing.

I tried serving it as HTTP(S) and SOCKS but nothing changed.

What do you think I am doing wrong?
