### ISSUE TITLE
Support SIP004 (AEAD Ciphers)

### ISSUE THREAD

**Issue by r0ks** [shadowsocks/shadowsocks-qt5#448]
Hi, thank you for your great job! 
[shadowsocks/shadowsocks-org#30](https://github.com/shadowsocks/shadowsocks-org/issues/30)
It seems that the latest ss-libev had deprecated OTA and enabled new stream ciphers (AEAD ciphers), although it's still unstable and being developed, it might be better than OTA. 
Can you please tell me if there is any plan for supporting it within ss-qt5?
Thank you so much! I use ss-qt5 both on my win10 and ubuntu, it's an excellent client!

**Comment by librehat** [comment]
There is an outstanding regression bug in Botan-2 that needs to be fixed first.

I will start implementing AEAD once it's more stabilised. However, it will require Botan-2 (most Linux distributions today still pack Botan-1.10), so it's unlikely you'll be able to use it on Linux (maybe with some luck, later this year)

**Comment by beterhans** [comment]
Please add AEAD ciphers
I like this QT version since it can run out of the box no extra runtime is needed.

**Comment by librehat** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v3.0.0alpha
