### ISSUE TITLE
b70bb7e162aa8a1603ddfab2910f37e12d170650这条提交修改的单一实例的行为

### ISSUE THREAD

**Issue by vonhezhou** [shadowsocks/shadowsocks-qt5#451]
b70bb7e162aa8a1603ddfab2910f37e12d170650这条merge，将原来的全系统单一实例的行为修改为，针对单用户单一实例。如果是修改前后行为不一致。而按照ss的行为而言，应当是全系统单一实例。
另外，如果是要实现单用户单一实例的话，使用QLockFile会好一点

**Comment by librehat** [comment]
@x1596357 Hey, do you have time to send another pull request to change the behaviour of single instance implemented with QLocalSocket? As mentioned in this issue, we need a single instance mode that is for all users (system-wide), not just for current user session.

**Comment by librehat** [comment]
OK, I spared a bit time finishing that.
