### ISSUE TITLE
Where is the config file

### ISSUE THREAD

**Issue by wjs876046992** [shadowsocks/shadowsocks-qt5#454]
I have configured one server (aes-256-cfb) and set connected on startup, it will show **Segmentation fault (core dumped)** and **failed to start xxxx(server)** . So, how can i reconfig the server

**Comment by librehat** [comment]
What is your operating system?

**Comment by librehat** [comment]
It's either with your executable, or in `$HOME/.config/shadowsocks-qt5`

**Comment by wjs876046992** [comment]
@librehat Yes, I have found it. However, why error `egmentation fault (core dumped)` occured where I set `aes-256-cfb` encryption?

**Comment by librehat** [comment]
You're using Botan-2. Please check the open issue.
