### ISSUE TITLE
Any plans to make it work system-wide like all other clients?

### ISSUE THREAD

**Issue by tapir** [shadowsocks/shadowsocks-qt5#461]
shadowsocks-win, Mac and Android clients, they all work the same way. I connect to the server and every application goes through the proxy automatically without changing the proxy settings per application.

but in linux, with shadowsocks-qt5 client, it doesn't do that. I have to change every apps' settings to 127.0.0.1:1080 to allow traffic go through shadowsocks.

any plans to make it work automtacilly without changing app settings?

**Comment by librehat** [comment]
Nope

**Comment by tapir** [comment]
If it's not too much to ask, why?

**Comment by librehat** [comment]
OS is different, there is no easy way to set system-wide proxy in Linux

**Comment by tapir** [comment]
http://proxychains.sourceforge.net/howto.html

this application can. maybe it can be integrated?

**Comment by librehat** [comment]
If you've had an application to do the work, why should we bundle it? Just use two applications, or write a script

**Comment by tapir** [comment]
You dont have to do anything. It seems like you misunderstand the concept
of github issues. it was a fearure request. if you don't want to, simply
dont do it.
