### ISSUE TITLE
Ubuntu Unity 桌面情况下如何设置开机启动

### ISSUE THREAD

**Issue by kbyyd24** [shadowsocks/shadowsocks-qt5#462]
我的系统是`Ubuntu 16.04.2`, 桌面环境是`Unity`, 我在`Unity Tweak Tool`里面没有找到设置开机启动的地方.
在`Dash`里面找到了`Startup Applications`这个东西, 可以用来设置开机启动程序.

然而需要我找到相应的命令才能设置, 而我在`/usr/bin`目录下面没有找到`shadowsocks`, 使用
```console
whereis shadowsocks
```
也没有找到任何信息.

请问我要到哪里才能找到启动的命令呢?

**Comment by librehat** [comment]
ss-qt5

**Comment by kbyyd24** [comment]
找到了, thx
