### ISSUE TITLE
Ubuntu 连接了，浏览器打不开Google

### ISSUE THREAD

**Issue by jinfagang** [shadowsocks/shadowsocks-qt5#463]
设置了浏览器代理也打不开，本地代理为 `127.0.0.1` , 端口为 `1080`，Firefox和Chrome设置了都不开为啥，我miss了什么东西么

**Comment by librehat** [comment]
Double check your browser's settings

**Comment by TorvaldsDB** [comment]
please do like this step by step ... 
[linux-ubuntu使用shadowsocks客户端配置(内付SwitchyOmega)](https://aitanlu.com/ubuntu-shadowsocks-ke-hu-duan-pei-zhi.html)
