### ISSUE TITLE
请问Ubuntu 的源不能用了吗？

### ISSUE THREAD

**Issue by huyanshan** [shadowsocks/shadowsocks-qt5#465]
W: Failed to fetch http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu/dists/trusty/main/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu/dists/trusty/main/i18n/Translation-en  Hash Sum mismatch

**Comment by librehat** [comment]
Use proxy to access PPA

**Comment by EasonD3** [comment]
@librehat , could you be more specific?
