### ISSUE TITLE
ss-qt5: symbol lookup error: /lib64/libQtShadowsocks.so.1: undefined symbol: 

### ISSUE THREAD

**Issue by wibin86** [shadowsocks/shadowsocks-qt5#466]
system:fedora23
when i run ss-qt5,show error:
ss-qt5: symbol lookup error: /lib64/libQtShadowsocks.so.1: undefined symbol: _ZN5Botan10get_cipherERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_10Cipher_DirE

it was normal before  i used dnf update
please tell what's the problem,how to fix it?

**Comment by librehat** [comment]
Probably because of some updates of botan. I just triggered a rebuild of libQtShadowsocks. Try to re-install shadowsocks-qt5 and libQtShadowsocks from the copr

**Comment by wibin86** [comment]
Thank you!
I have try remove and install shadowsocks-qt5 again used by copr, but ss-qt5 still not work and show the same error. The libQtShadowsocks version is libQtShadowsocks-1.10.0-1.fc23.x86_64.

**Comment by librehat** [comment]
Strange... I'll need to look into it when I have spare time (very busy recently)

**Comment by wibin86** [comment]
Thank you all the same.

**Comment by librehat** [comment]
Hey, do you still have this problem after system update?

**Comment by Cyber-SiKu** [comment]
ubuntu 16.04.2
as same after recently update

**Comment by zhufenggood** [comment]
ln works for me,    Ubuntu 16.04 after some system updates.
` sudo ln /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1  `

**Comment by Cyber-SiKu** [comment]
@zhufenggood 3q

**Comment by Cyber-SiKu** [comment]
3q，but do not know why Ubuntu do this.



Sent from my Mi phone
On zhufenggood <notifications@github.com>, Aug 4, 2017 11:06 wrote:

ln works for me, Ubuntu 16.04 after some system updates.
sudo ln /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1

**Comment by xxkason** [comment]
@zhufenggood thx, it works

**Comment by akalantari** [comment]
I had to make a symbol link of  `/usr/lib/libQtShadowsocks.so` in `/lib/` for ss-qt5 to read it. It works fine thou
