### ISSUE TITLE
Debian 8 打包错误

### ISSUE THREAD

**Issue by excalibur44** [shadowsocks/shadowsocks-qt5#470]
环境：
debian 8.6.0 amd64 (jessie)
libQtShadowsocks 1.10.0-1 amd64
libQtShadowsocks-dev 1.10.0-1 amd64

已经按照wiki安装了依赖（其中libqtshadowsocks-dev是单独下载编译安装的）：
> sudo apt-get install qt5-qmake qtbase5-dev libqrencode-dev libqtshadowsocks-dev libappindicator-dev libzbar-dev libbotan1.10-dev

但在编译时出现错误：

> dpkg-shlibdeps: error: no dependency information found for /usr/local/freetype/lib/libfreetype.so.6 (used by debian/shadowsocks-qt5/usr/bin/ss-qt5)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/shadowsocks-qt5.substvars debian/shadowsocks-qt5/usr/bin/ss-qt5 returned exit code 2
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

麻烦解决一下，谢谢！

**Comment by librehat** [comment]
I don't know what went wrong.... It's complaining about libfreetype

**Comment by ZKeLin** [comment]
how to solve this problem?

**Comment by librehat** [comment]
I didn't get this problem in my VM (Debian Jessie 8.9)
