### ISSUE TITLE
ss-qt5在linux中测试延迟全部显示错误

### ISSUE THREAD

**Issue by qw852654** [shadowsocks/shadowsocks-qt5#473]
系统：linuxmint，全部更新
ss-qt5版本：5.5.1
症状：测试某服务器延迟时，刚测试时显示正常，十秒内所有延迟都显示错误，系统防火墙没有开启
日志错误提示：Internet connectivity test failed. Please check the connection's profile and your firewall settings.注：服务器信息直接导入，在同一个WiFi下，手机连接相同服务器完全正常

**Comment by WantYKnow** [comment]
me too,你解决了吗？

**Comment by izuolan** [comment]
你可能使用了SSR帐号，这个软件只支持ss协议。

**Comment by hakale** [comment]
>  OS: Ubuntu 17.04 zesty
>  Kernel: x86_64 Linux 4.10.0-22-generic
同样的问题.之前一切正常,安装tlp之后发现此故障

**Comment by Cinux-Chosan** [comment]
我在 Centos 7上面安装 ss-qt5，然后也是一直能连接上，但是测试延迟闪了一下就显示错误。最后的操作：选择文件菜单 -》 导出为gui-config.json -》 然后随便改了一下，比如把 shareOverLan 改为 true -》从 gui-config.json 导入连接，然后连接和测试延迟都成功了，如果连接不上退出 ss-qt5重新连接就解决了。但是最后我把配置文件还原了，再导入，依然可以。但是最初的那一个还是连接不上，所以我就把它删了。虽然没测试，但是按道理导出来然后再导入就可以，如果不行也改改吧。再不行就可能是防火墙的问题了。

**Comment by GuaiYiHu** [comment]
现在有支持ssr协议的qt5客户端了吗

**Comment by ykelvis** [comment]
shadowsocks-qt5是ss的客户端，不兼容ssr， see #449

**Comment by Ronsandpi** [comment]
解决了吗

**Comment by mforgit** [comment]
my soulution: del all config in the shadowsocks-qt5, and install version for ubuntu 16.04 LTS and add configs manually. done!
It's ok also in ubuntu 18.04 (still install it for 16.04 version)

**Comment by MH-Lan** [comment]
我这里显示的节点延迟是有限的，但是链接后无法登录网络，这是什么原因呢？

**Comment by yinglang** [comment]
this is work for me, you can try:
rm ~/.config/shadowsocks-qt5 -rf
re-run ss-qt5
