### ISSUE TITLE
有50%可能性开机后无法连接到shadowsocks服务

### ISSUE THREAD

**Issue by stereoF** [shadowsocks/shadowsocks-qt5#475]
系统为Ubuntu 16.04 LTS。
一般电脑重启后，打开shadowsocks-qt5 有很大可能性连接任一连接时都会提示failed。这种情况一般必须再次重启电脑，重启后一般就好了。

**Comment by librehat** [comment]
Feng shui? It might be that your IP was blocked by GFW
