### ISSUE TITLE
Native menu bar not working after closing and restoring the window

### ISSUE THREAD

**Issue by leafpile** [shadowsocks/shadowsocks-qt5#477]
Also, the non-native menu bar doesn't respond to keyboard shortcuts (`alt + c`, etc.) after upgrading to 17.04

**Comment by librehat** [comment]
Native or non-native. Your title and description contradict each other

**Comment by leafpile** [comment]
Sorry, I meant native menu bar. I think the non-native one never responded to keyboard shortcuts. 
It would be nice to add shortcuts and the ability to customise them!

**Comment by librehat** [comment]
can't reproduce in Fedora
