### ISSUE TITLE
shadowsocks disconnects every 5-6 minutes

### ISSUE THREAD

**Issue by Archerious** [shadowsocks/shadowsocks-qt5#478]
**Affected:** My android phone running shadowsocks, PC running shadowsocks client from pip install shadowsocks (solus), and laptop running qt5 (archlinux).

**Problems:** Causes google video, youtube, ssh sessions, and really anything to experiance a disconnect every 5-6 minutes. This makes me have to refresh youtube when in 5-6 minutes into video, google video (really annoying), and reconnect to ssh on my phone in JuiceSSH as it keep disconnecting. Screenshot will be added once I can remove SS IP from it.

Shadowsocks Server- (config settings: port 8388, AES-128-CFB) is debian 8 on vps running shadowsocks-go. I use screen to perm keep it running and so I can reattach via "screen -rd <pidnumhere>" anytime I need to see progress.

Below is SS-QT5 google drive video disconnecting at 4:56 seconds, even though the video showed it had buffered much more. I then have to either keep refreshing every 5-6 minutes as I get further in videos, or I turn off shadowsocks (and on linux the tunnel) and see no issues  as I'm in US currently.

![screenshot from 2017-04-15 04-19-37](https://cloud.githubusercontent.com/assets/26941475/25062507/c579e802-21bc-11e7-9469-59b56e6a9ad2.png)

![shadowsocks qt5 google video issue got 4 min 56 seconds in before disconnect](https://cloud.githubusercontent.com/assets/26941475/25062474/4407c366-21bc-11e7-9ca5-3ebdbdaab5dd.png)

![Example of disconnects on android:](https://cloud.githubusercontent.com/assets/26941475/25062370/96dce1ae-21ba-11e7-9d5b-44368d040c4d.png)

**Comment by librehat** [comment]
It looks like your machine's problem if SSH also drops every a few mins

**Comment by librehat** [comment]
Close due to no updates

**Comment by murich** [comment]
My ssh drops after 1-3 minutes of inactivity under shadowsocks :(
