### ISSUE TITLE
Connected but can' access blocked website

### ISSUE THREAD

**Issue by Honpray** [shadowsocks/shadowsocks-qt5#479]
Hi, i'm using shadowsocks-qt5 on Ubuntu 16.04 LTS. Config file was imported from ss Windows which works great. Connection can be established and the latency is good but I still can't open webpage like Google and Youtube. I tired both socks and http. 
A friend using Ubuntu 14.04 has the same problem.
Any suggestion on this problem?

**Comment by Poppy7444** [comment]
i also has this issue . for help

**Comment by LXNCHINAA** [comment]
same problem

**Comment by iwarriorgit** [comment]
[possible solution](http://forum.ubuntu.com.cn/viewtopic.php?f=73&t=481393)
floor 3 @ taohunter : 如能ping通服务器，那么检查一下你的客户端配置，最容易出问题的就是加密类型是否与服务器端匹配，另外还有密码字段（这个客户端密码字段有bug，最好用tab键移动到密码字段，输入或粘贴密码后再tab键到下一字段，密码才会确保被正确输入，否则可能会导致密码字段为”空“）
I just solved my problem today. All u need to do is:
1. `floor 3, tab to past password`
2. `change system setting -> network -> network proxy -> `
          `a. method -> automatic`
          `b. Configuration -> your_pac_address eg:file:///home/username/gfwlist.pac`
3. `restart shadowsocks client`
I am a linux beginner,  don't know the reason, maybe there is really a bug when u type in ur password by hand. 
Anyway, shadowsocks team is great, thanks

**Comment by Honpray** [comment]
@LXNCHINAA @iwarriorgit Thank you! Mine works after I set up the system network proxy. But it works with HTTP but not with SOCKS. Don't really know why. I'm still learning about everything. Also a linux beginner.
`Anyway, shadowsocks team is great,`
Totally agree. Thanks!

**Comment by ryukinkou** [comment]
Same issue, I fixed this problem by changing web browser from Firefox to Chrome.

**Comment by librehat** [comment]
Read wiki please before you just open an issue
