### ISSUE TITLE
Error in RHEl 7.3

### ISSUE THREAD

**Issue by repuban** [shadowsocks/shadowsocks-qt5#481]
When I want to setup in RHEL7.3, there is no error in the process. After setup, when I click it, I can see it on the top menu, but it will disapper in few seconds.

**Comment by mickeydonkey** [comment]
same here, on centos 7 x86_64

**Comment by mickeydonkey** [comment]
`
$ ss-qt5
ss-qt5: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
`

**Comment by librehat** [comment]
I've added `qt5-qtbase-gui` as a dependency now. Try to update and it should be fixed
