### ISSUE TITLE
Server name sorting

### ISSUE THREAD

**Issue by madjxatw** [shadowsocks/shadowsocks-qt5#486]
When setting the server Name column in descending alphabetical order, there is a empty space at the top area, and all the column labels become invisible. The more server is added, the bigger the empty space becomes.
Environment: Debian 8 + Mate desktop 1.6 + Qt 5.7.1

![ss-qt5-0](https://cloud.githubusercontent.com/assets/6035833/25933443/61e94f70-3649-11e7-8bf7-8c9dc78b78f0.png)
![ss-qt5-1](https://cloud.githubusercontent.com/assets/6035833/25933445/6410b568-3649-11e7-9b3a-3f5be84e25c2.png)

**Comment by librehat** [comment]
#450
