### ISSUE TITLE
不支持Ubuntu17.04

### ISSUE THREAD

**Issue by shawzh** [shadowsocks/shadowsocks-qt5#490]
GUI界面显示链接成功，但是chrome打开google显示意外终止链接，日志里没有错误信息

**Comment by AmosXu** [comment]
我和你一样的问题，刚刚解决了，GUI连接成功后，然后系统设置->网络->网路代理，选择手动，然后在HTTP代理、HTTPS代理、Sockers主机都填上地址和端口，我的分别是127.0.0.1和1080

**Comment by shawzh** [comment]
问题解决！谢谢你

**Comment by ZJUGuoShuai** [comment]
@AmosXu 谢谢，问题解决了

**Comment by AmosXu** [comment]
@ZJUGuoShuai @shawzh 如果发现设置网络代理这种方式不是很好用，可以用chrome的插件Proxy SwitchyOmega，也可以解决问题

**Comment by igoodvegetablea** [comment]
@AmosXu 您好，我设置完手动，填写好代理和端口之后chromium一直提示正在等待代理隧道的响应，同时百度和谷歌均无法访问。请问是什么原因，该如何解决？

**Comment by Wolfrider** [comment]
只配置Socks Host项, 其他的全都是空. 在浏览器上Google可以访问, 但在Terminal上ping Google不行,不知可否配置全局代理?

**Comment by li-zhenyu** [comment]
@AmosXu 你解决了吗？

**Comment by AmosXu** [comment]
@li-zhenyu 你好我自己是没什么问题，怎么了，你出现问题了吗

**Comment by AmosXu** [comment]
@igoodvegetablea 你好意思 刚刚才看到你的咨询，你是否是shadowsocks的配置错误，现在问题解决了吗？

**Comment by ZonglinLiu** [comment]
我现在可以使用chrome访问google以及youtube，但是当我使用command直接pin www.google.com，www.youtube.com没有相应。我是使用的手动代理，SOCKS5 填写的127.0.0.1:1080. 我想使用全局代理.

**Comment by AmosXu** [comment]
@ZonglinLiu Shadowsocks它使用socks5协议，而终端很多工具目前只支持http和https等协议，对socks5协议支持不够好，你可以安装polipo试试，相关文章你可以看http://droidyue.com/blog/2016/04/04/set-shadowsocks-proxy-for-terminal/index.html

**Comment by yaochao** [comment]
@AmosXu 为什么要都把http、https、socks主机设置为127.0.0.1:1080呢，只设置socks主机就可以。应为它用的socks协议，而不是http协议。

**Comment by happyren** [comment]
请问GUI界面现实连接成功但是Latency一直是failure 然后无法连接是什么问题呢？本人使用ubuntu17.04 gnome在VMware上。是否是我的VMware配置问题？

**Comment by AmosXu** [comment]
@happyren 你有试过上面设置网络代理的方法吗

**Comment by happyren** [comment]
@AmosXu 尝试过，然后就完全失去网络连接了，我在考虑是否因为我的系统搭建成虚拟机，网络界面的设置上有问题。

**Comment by AmosXu** [comment]
@happyren 你这种问题我暂时没碰到过,无法给出解决方案,不好意思

**Comment by happyren** [comment]
@AmosXu 没问题，我把电脑装成linux再试试。

**Comment by xinyangmaojian** [comment]
> 我和你一样的问题，刚刚解决了，GUI连接成功后，然后系统设置->网络->网路代理，选择手动，然后在HTTP代理、HTTPS代理、Sockers主机都填上地址和端口，我的分别是127.0.0.1和1080

您好，"系统设置-网络-网络代理"这一步可以直接在命令行或者是环境变量中直接设置吗？因为我的是lubuntu18.04，未找到“系统设置-网络-网络代理”这个选项     所以目前链接上了但还是无法科学上网
