### ISSUE TITLE
opensuse的源

### ISSUE THREAD

**Issue by arloor** [shadowsocks/shadowsocks-qt5#491]
最近发现opensuse自己维护的shadowsocks-qt5源失效了。
请问能不能增加opensuse的支持啊。

**Comment by hcnhcn012** [comment]
老哥我之前也是opensuse，同样的问题，opensuse太注重稳定了，软件也少，对版权比较重视，所以像ss这种的估计不会在官方源中出现，现在第三方源一崩就gg，我现在换了fedora

**Comment by librehat** [comment]
You can volunteer to package this
