### ISSUE TITLE
Ubuntu16.04设置代理后不能上网

### ISSUE THREAD

**Issue by zyh001** [shadowsocks/shadowsocks-qt5#494]
软件运行正常，延迟测试也没问题，浏览器是FireFox，代理设置后不能上网

**Comment by Ikcarus** [comment]
fedora 也是这样，运行正常，延迟测试也没问题，连google.jp时一直进不了，最后连接超时，除了设置软件还有其他要求么？

**Comment by zyh001** [comment]
@Ikcarus I have solved the problem.Because, the domestic DNS pollution is very serious.Therefore, you need to be forwarded by the proxy for DNS forwarding.
