### ISSUE TITLE
Linuxmint 18.2 cinnamon桌面不显示托盘

### ISSUE THREAD

**Issue by abcfy2** [shadowsocks/shadowsocks-qt5#500]
看了下[FAQ](https://github.com/shadowsocks/shadowsocks-qt5/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%92%8C%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95#%E4%B8%8D%E6%98%BE%E7%A4%BA%E7%B3%BB%E7%BB%9F%E6%89%98%E7%9B%98%E5%9B%BE%E6%A0%87)，我的问题应该属于这种类型。

```bash
echo $XDG_CURRENT_DESKTOP 
X-Cinnamon
```

环境: Linuxmint 18.2, cinnamon桌面环境

**Comment by FantasyNJ** [comment]
Ubuntu gnome3.24 下也会出现这个问题

**Comment by librehat** [comment]
@FantasyNJ GNOME doesn't have system tray

**Comment by librehat** [comment]
@abcfy2  Can you please compile the latest `master` branch code and re-open this issue if that doesn't fix your problem?

**Comment by HougeLangley** [comment]
KDE正常

**Comment by abcfy2** [comment]
可以了，我从PPA更新了软件包，现在好了
