### ISSUE TITLE
添加fedora26的支持

### ISSUE THREAD

**Issue by yvangru** [shadowsocks/shadowsocks-qt5#501]
现在会显示
`同步仓库 'librehat-shadowsocks' 缓存失败，禁用。`

**Comment by mtawame** [comment]
same problem

**Comment by cg1937** [comment]
yes, same problem, please add it quickly, thank you

**Comment by zhanba** [comment]
Fedora 26: Failed to synchronize cache for repo 'librehat-shadowsocks', disabling.

**Comment by yvangru** [comment]
使用CLI版

**Comment by lyshengli** [comment]
same problem.

**Comment by librehat** [comment]
working on it

**Comment by librehat** [comment]
fixed
