### ISSUE TITLE
centos7无法打开GUI

### ISSUE THREAD

**Issue by haoyouab** [shadowsocks/shadowsocks-qt5#502]
如题，安装完之后，打不开，没有任何反映，有解决办法吗？

**Comment by zhuang00** [comment]
我系统也是Centos7，刚装也是打不开，我想可能没有安装qt5，你用root运行下面的命令再打开软件，应该可以打开软件，希望能帮到你
yum install qt5-qtbase-devel

**Comment by haoyouab** [comment]
已经解决了，issues下面有个redhat7遇到同样的问题，yum install qt5-qtbase-gui就行
