### ISSUE TITLE
Pre-built v2.9.0 crashes on Windows

### ISSUE THREAD

**Issue by StrollStars** [shadowsocks/shadowsocks-qt5#505]
操作系统：Win7
直接解压覆盖v2.8.0可执行文件，运行直接一堆窗口报错，最终退出。
删除配置文件，可以启动v2.9.0，添加服务器，保存退出后重新打开，连接服务器，再通过SS访问网页，程序报错退出。
只获得以下截图，暂时无法获得更多信息。
![01](https://user-images.githubusercontent.com/10942225/28524806-960181b0-70b4-11e7-898a-f0fc410df8a8.jpg)
PS：求v2.8.0的exe版本地址，releases中已失效。

**Comment by librehat** [comment]
Can't reproduce on my Windows 10 laptop

**Comment by librehat** [comment]
You can get 2.8.0 from here: https://www.dropbox.com/sh/nqo84eld4z3lwe4/AAAOk4uF84obVaBDQir0a8SLa?dl=0

**Comment by opera443399** [comment]
just running the app, wait for a while, the error occurred.
on win10 laptop

----
hard to upload image here, the same to: @StrollStars 's one.

**Comment by opera443399** [comment]
version: ss-qt5-v2.9.0-win64.7z

**Comment by qyin** [comment]
Same error occurred when run on a windows 10 laptop with version 2.9.0.
Version 2.8.0 works fine.

**Comment by librehat** [comment]
With active in use connection? Or just open it and wait?

**Comment by opera443399** [comment]
@librehat  run -> connected -> wait about 5s -> crashed

**Comment by RobinCodeX** [comment]
windows10也是，可以连接成功，然后测试延迟也没问题，在其他程序使用代理的时候就出现崩溃

![image](https://user-images.githubusercontent.com/8408783/28711674-f8987370-73ba-11e7-820d-952b3fee435b.png)

**Comment by StrollStars** [comment]
@RobinCodeX 我这里可能会出现超时

**Comment by librehat** [comment]
It was a build error (I mistakenly linked it with Botan-2 which is not supported yet)

**Comment by librehat** [comment]
I've re-built a new one for Windows and I've tested it on my laptop that there is no more crashes. Please download it from releases page (make sure you check the sha1sum that your download is legitimate)
