### ISSUE TITLE
上国内网站OK，上国外网站就ERROR（ERROR while addressing abroad webs）

### ISSUE THREAD

**Issue by silrep2** [shadowsocks/shadowsocks-qt5#506]
连上Shadowsocks，浏览器火狐，网络设置为127.0.0.1:1080 socks v5
访问百度等国内网址能够正常运行，使用百度查询ip也是海外ip。
但是一旦访问youtube或者google，没有反应，log信息为
“An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.”
我确认无论是shadowsocks qt还是firefox setting我使用的都是 SOCKS5。
请问问题出在哪里

After connecting SS, I can visit webs such like Baidu using my abroad ip. However, I cannot visit google and others successfully. The log info is 
“An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.”
I confirmed I was using SOCKS5 both on shadowsocks qt and firefox setting. 
Can anyone help me. Thanks

**Comment by librehat** [comment]
检查你的浏览器设定，日志写的很清楚了，代理类型填错
