### ISSUE TITLE
使用新加密测速报错

### ISSUE THREAD

**Issue by isfangwei** [shadowsocks/shadowsocks-qt5#510]
你好，使用chacha20-ietf-poly1305进行测速，会报错，具体见图，谢谢。
![bug](https://user-images.githubusercontent.com/28683299/28890575-1ccbd21c-77fa-11e7-90e9-468075f4bbff.PNG)

**Comment by librehat** [comment]
根本不支持，你怎么用的？

**Comment by isfangwei** [comment]
我是用shadowsocks-windows代理，那本版本支持新协议，然后用qt-5测延迟。
