### ISSUE TITLE
ubuntu ss-qt5 无法启动缺少lib

### ISSUE THREAD

**Issue by Cyber-SiKu** [shadowsocks/shadowsocks-qt5#511]
ss-qt5: error while loading shared libraries: libQtShadowsocks.so.1: cannot open shared object file: No such file or directory
apt install  libqtshadowsocks  libqtshadowsocks-dev仍无效

ubunut 16.04  4.10.0-30-generic
更新完成以后出现的这种情况

**Comment by imwls** [comment]
the same issue!

**Comment by Cyber-SiKu** [comment]
@imwls I guess that the new lib rename itself I try to find it but failure.but if you need ss-qt5 you can make it by yourself.

**Comment by Cyber-SiKu** [comment]
@imwls you can do this 
cp /usr/lib/libQtShadowsocks.so /usr/liblibQtShadowsocks.so.1
it work

**Comment by mhf-air** [comment]
same issue after upgrade

**Comment by Cyber-SiKu** [comment]
@mhf-air 
you can do this
cp /usr/lib/libQtShadowsocks.so /usr/liblibQtShadowsocks.so.1
or make a link
it work

**Comment by mhf-air** [comment]
@Cyber-SiKu 
it works, thanks

**Comment by jingw222** [comment]
Unfortunately `cp /usr/lib/libQtShadowsocks.so /usr/liblibQtShadowsocks.so.1` does not work for me. Launching it through the GUI simply flashes for a second and exit itself. What went wrong here? BTW I also did an upgrade of my Ubuntu 16.04 hours ago.

**Comment by fengdy** [comment]
cp /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1

**Comment by jingw222** [comment]
Great help! Appreciate it very much. But I have no idea why we need to do this after the system upgrade.

**Comment by zhufenggood** [comment]
ln works for me,    Ubuntu 16.04 after some system updates.
` sudo ln /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1  `

**Comment by Cyber-SiKu** [comment]
@jingw222 ss-qt5 use libQtShadowsocks.so.1.New OS rename it to libQtShadowsocks.so.So when start it it couldn't find the lib.

**Comment by chen-ni** [comment]
A big thanks! Well 
`sudo ln /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1` 
works for me, but 
`cp /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1` does not.

**Comment by Cyber-SiKu** [comment]
@chen-ni 
but in my system it works,but I use ln finally.
you do ``` cp /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1``` whit root or not ?

**Comment by chen-ni** [comment]
@Cyber-SiKu Ah you got it.. I forgot to add `sudo` ;) but why didn't I notice it...

**Comment by likilli** [comment]
So happy. After I use this order. My Shadowsocks-qt5 works. Thank you !

**Comment by librehat** [comment]
#512

**Comment by Cyber-SiKu** [comment]
@librehat thanks
