### ISSUE TITLE
Shadowsocks-Qt5 can't startup

### ISSUE THREAD

**Issue by wusc972** [shadowsocks/shadowsocks-qt5#513]
I can't startup Shadowsocks-Qt5 in Ubuntu 16.04.3, its same after i reinstall the system!

**Comment by kubejenkis** [comment]
I have the same problem! And it doesnt work after reinstall. Only update ubuntu today.

**Comment by liyuanye** [comment]
升级ubuntu系统后也打不开，一直在转圈，然后就没反应了

**Comment by leogao1991** [comment]
After updating system，the client is gone...

**Comment by kubejenkis** [comment]
@leogao1991 what's its name?  help me, crying......

**Comment by imagainstzy** [comment]
I also have the same problem,in the last version of linux mint.

**Comment by leogao1991** [comment]
@kubejenkis U try to search Shadowsocks on Chrome Web Store and it ranks first position on Apps list, which is offered by jnuer.com

**Comment by kubejenkis** [comment]
@leogao1991 thx, I try

**Comment by bugxch** [comment]
I also come across with the issue after I upgrade my linux kernel **Linux mint 4.10.0-30-generic** , please help check the problem, thank you

**Comment by mepwang** [comment]
mep@t460s:~$ ss-qt5 
ss-qt5: error while loading shared libraries: libQtShadowsocks.so.1: cannot open shared object file: No such file or directory

**Comment by likilli** [comment]
On site: "https://github.com/shadowsocks/shadowsocks-qt5/issues/511", there are many users said it works after execute order "sudo cp /usr/lib/libQtShadowsocks.so /usr/liblibQtShadowsocks.so.1" or "sudo ln /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1". I tried and my shadowsocks-qt works wonderfully. Maybe you should have a try.

**Comment by likilli** [comment]
On site: "#511", there are many users said it works after execute order `sudo cp /usr/lib/libQtShadowsocks.so /usr/liblibQtShadowsocks.so.1` or `sudo ln /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1.` I tried and my shadowsocks-qt works wonderfully. Maybe you should have a try.

**Comment by chester256** [comment]
@mepwang  I have the same problem with you. OS: Ubuntu14.04

**Comment by Xinwei-Liu** [comment]
I have the same problem! And it doesnt work after reinstall. 
OS: Ubuntu 16.04
无论如何点击图标后，都不会显示界面，鼠标转圈后闪退，求解决方案！

**Comment by cpplucifer** [comment]
@imagainstzy  +1

**Comment by Xinwei-Liu** [comment]
解决办法
http://www.jianshu.com/u/5645dc9e4444

**Comment by likilli** [comment]
@Xinwei-Liu I meet this question either. `cp /usr/lib/libQtShadowsocks.so /usr/liblibQtShadowsocks.so.1` or make a link can slove it. I see this resolution on #511

**Comment by qk98** [comment]
cd /usr/lib
sudo mv libQtShadowsocks.so libQtShadowsocks.so.1

**Comment by JiongZhu** [comment]
I have the same problem! And it doesnt work after reinstall. Only updating ubuntu today.In Ubuntu 17.04.

**Comment by LukeEuler** [comment]
using fedora25.
cd /usr/lib64
cp libQtShadowsocks.so libQtShadowsocks.so.1
and it works now

**Comment by NanerLee** [comment]
+1

**Comment by NanerLee** [comment]
@Xinwei-Liu @likilli your command is wrong, you ingore a **'/'**,
the right is `cp /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1`

**Comment by librehat** [comment]
#512
