### ISSUE TITLE
About the LGPL license

### ISSUE THREAD

**Issue by SuperHentai** [shadowsocks/shadowsocks-qt5#514]
I am developing an open-source GUI client (exactly a GUI front-end) for the V2Ray peoject  under LGPLv3. 
Most features of my project are the same as that in the front-end part of shadowsocks-qt5 project. 
So my project is partly based on shadowsocks-qt5 project.
Some components are used in the form of entire reference (e.g., the ShareDialog and the QRCodeCapturer),the license information in these components is intact. However, some little code blocks are modified and used in separated places. Must I attach the raw license information wherever they are used? Or I just need to put the information in the LICENSE file of my project and make a statement？
I opened this issue and asked the question to avoid any unnecessary trouble.Looking forward to your reply.
Thanks.

**Comment by librehat** [comment]
Any references about the license in the source code should be kept. As long as your license is LGPL, I believe there shouldn't be any legal problems.
I'm OK with a reference or statement stating the code was part of this project.
Hope this helps you.

**Comment by SuperHentai** [comment]
Thanks for your reply!
