### ISSUE TITLE
ss-qt5: error while loading shared libraries: libQtShadowsocks.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jasonkoo** [shadowsocks/shadowsocks-qt5#515]
I installed shadowsocks-qt5 on my Ubuntu and it worked normally. 
But after I upgraded my ubuntu, I cannot open shadowsocks-qt5. When I try to start shadowsocks-qt5 in my command line with sudo ss-qt5, I got this error: ss-qt5: error while loading shared libraries: libQtShadowsocks.so.1: cannot open shared object file: No such file or directory.
Currently, my Ubuntu version is 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by LeeiFrankJaw** [comment]
In fact, I emailed the maintainer pointing out the same problem. What I did to solve the problem was the following command.

    sudo ln -s /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1

I believe this is a naming typo.

**Comment by librehat** [comment]
#512
