### ISSUE TITLE
ss qt5 经常崩溃

### ISSUE THREAD

**Issue by coderstory** [shadowsocks/shadowsocks-qt5#516]
优麒麟 16.10系统
系统已经更新

安装ss qt5  现在Android源码   峰值下载速率大概是70mbps

问题:  经常本地ss qt5代理失败 或者 ss qt5客户端自动退出  或者切换ss 节点时提示shadowsock启动失败
   重新打开ss 提示什么后台进程通信失败 可能崩溃什么的

客户端里的日志只有ss连接的日志 ，请问这个要这么看详细的日志？ 或者要怎么处理

**Comment by librehat** [comment]
Is this duplicate to #205 ?
