### ISSUE TITLE
Fedora系统更新后无法启动Shadowsocks-Qt5

### ISSUE THREAD

**Issue by xq0404** [shadowsocks/shadowsocks-qt5#517]
Fedora 26 版本 3.24.2,
Shadowsocks-Qt5 版本 2.9.0-1.fc26

**Comment by jimgreen2013** [comment]
我是Fedora 26  64位的版本，临时的解决方法是
sudo ln -s /usr/lib64/libQtShadowsocks.so /usr/lib64/libQtShadowsocks.so.1

**Comment by xq0404** [comment]
太棒了！，输入上述命令就解决了。非常感谢！

**Comment by librehat** [comment]
#512
