### ISSUE TITLE
安装后不能启动

### ISSUE THREAD

**Issue by CasparLi** [shadowsocks/shadowsocks-qt5#518]
系统版本. ubuntu16.04 
通过
sudo add-apt-repository ppa:hzwhuang/ss-qt5
sudo apt-get update
sudo apt-get install shadowsocks-qt5
安装后 不能启动.
命令行执行 ss-qt5 显示
ss-qt5: error while loading shared libraries: libQtShadowsocks.so.1: cannot open shared object file: No such file or directory

**Comment by 14061052** [comment]
我也想知道

**Comment by 14061052** [comment]
sudo ln -s /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1

**Comment by CasparLi** [comment]
已解决!
