### ISSUE TITLE
Error: libQtShadowsocks.so.1

### ISSUE THREAD

**Issue by jsonbruce** [shadowsocks/shadowsocks-qt5#523]
I can't start ss from desktop-icon
I use `ss-qt5` command got erros below:

> ss-qt5: error while loading shared libraries: libQtShadowsocks.so.1: cannot open shared object file: No such file or directory

Environment:
>OS: Ubuntu 16.04 x64

**Comment by jsonbruce** [comment]
Found Solution:
The `libQtShadowsocks.so `  renamed to `libQtShadowsocks.so.1`
1. Copy 
 `sudo cp /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1`

2. Link
 `sudo ln /usr/lib/libQtShadowsocks.so /usr/lib/libQtShadowsocks.so.1`

Now, you can start SS from GUI or CLI normaly.

**Comment by librehat** [comment]
It is now resolved. Just update your system again
