### ISSUE TITLE
Linuxmint下关闭窗口托盘会变英文

### ISSUE THREAD

**Issue by abcfy2** [shadowsocks/shadowsocks-qt5#524]
我的系统是Linuxmint 18.2，从ppa安装的ss-qt5。

第一次启动的时候，托盘上显示的是"恢复"中文:
![image](https://user-images.githubusercontent.com/5327677/29053638-bd36b672-7c23-11e7-8eab-0dcf1e534270.png)

从托盘打开窗口，关闭之后，就会变成英文"Restore":
![image](https://user-images.githubusercontent.com/5327677/29053666-e026aaca-7c23-11e7-8cd5-0a2431f5823a.png)

希望可以看看这种不一致的行为是怎么回事？

**Comment by librehat** [comment]
Try the latest build again? https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v3.0.0alpha
