### ISSUE TITLE
无法保存配置

### ISSUE THREAD

**Issue by zinc357** [shadowsocks/shadowsocks-qt5#525]
每次保存新的连接配置，重新启动ss-qt5后。都会还原成第一次的配置。

**Comment by zinc357** [comment]
即使手动保存配置没有用

**Comment by librehat** [comment]
Run it from terminal, do you see any errors? 
Can you also run `ls -a ~/.config` and paste the results here?

**Comment by zinc357** [comment]
I do not see any errors. 
zinc@zinc-W65KJ1-KK1:~$ ls -a ~/.config
.                     google-chrome         SogouPY.users
..                    gtk-2.0               sogou-qimpanel
autostart             gtk-3.0               totem
cef_user_data         ibus                  Trolltech.conf
compiz-1              libaccounts-glib      ubuntu-amazon-default
dconf                 libreoffice           ubuntu-ui-toolkit
enchant               mimeapps.list         UNDERTALE_linux_steamver
eog                   my-weather-indicator  unity
evolution             nautilus              update-notifier
fcitx                 netease-cloud-music   upstart
fcitx-qimpanel        pulse                 user-dirs.dirs
gedit                 QtProject.conf        user-dirs.locale
gnome-control-center  shadowsocks-qt5
gnome-session         SogouPY

**Comment by zinc357** [comment]
When I use the File Manager to view the folder, I found the shadowsocks-qt5 folder icon with a lock on it. Will this be the reason?

**Comment by librehat** [comment]
Yes. It means the permission is wrong. 

Make sure you have write access to the folder and the configuration file

**Comment by zinc357** [comment]
sudo chmod -R 777 shadowsocks-qt5
