### ISSUE TITLE
安卓的分享二维码的ss连接 都不能用

### ISSUE THREAD

**Issue by iwakaka** [shadowsocks/shadowsocks-qt5#527]
centos7 epel源里面yum 装个ss-qt5
安卓ss4.2.2版本 分享的二维码不能扫，ss连接也不能添加
保存不了二维码图片

**Comment by librehat** [comment]
What do you mean you can't scan? Question is not clear

**Comment by iwakaka** [comment]
重新还了系统 fedora26，不过问题还是一样的，
添加功能里的 URI添加，二维码文件添加，扫描屏幕添加，使用扫描器添加都不能用
1，URI方式 我用安卓版分享的ss://连接 添加是 OK按钮是不可状态，不过ss-qt5自己分享的ss连接可以添加(发现安卓版没有把ip和端口base64密码，两个不一样啊 不能通用)
2，屏幕上的二维码识别不出，导入文件也不识别，扫描器也不行，读取不了
3，分享的二维码不能保存， 安卓版是可以扫描识别
4，最后就是有个ss账户 在手机安卓版能用，ss-qt5不能用，提示已连接 测试延迟 出错，另一个我自己搭的ss账户能通用

最后感谢你的ss gui

**Comment by xz00311** [comment]
可惜没有32位的,尝试编译32位的都没有成功过

**Comment by librehat** [comment]
It seems they're using a different scheme now.

**Comment by adasqg** [comment]
是啊，我的也不能，但是windows跟android的QRcode是通用的

**Comment by librehat** [comment]
I guess they're using SIP002 which is not supported yet (it's implemented in libQtShadowsocks in the master branch, which breaks too many things, so it will be released later this year or early next year)

**Comment by librehat** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v3.0.0alpha
