### ISSUE TITLE
Firefox不能使用shadowsocks-qt5代理

### ISSUE THREAD

**Issue by NestaJ** [shadowsocks/shadowsocks-qt5#528]
系统：Centos7
安装shadowsocks-qt5，并且配置了服务器端信息，可以连接，并且点击“Test Latency”按钮，正常。

配置Firefox的代理，使用本地地址和本地端口号，并且是Socks5协议。
Firefox不能连接google。

日志显示：
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.

可是
Local Server Type: SOCKS5
Firefox代理配置的也是 SOCKS5

谢谢。

**Comment by librehat** [comment]
看wiki，代理只填socks不要填http（http栏留空）

**Comment by NestaJ** [comment]
多谢，只填socks就好了。
