### ISSUE TITLE
ubuntu16.04 sslocal无法使用

### ISSUE THREAD

**Issue by raine0524** [shadowsocks/shadowsocks-qt5#529]
如题，我的远程vps使用的同样是Ubuntu16.04，使用ssserver -c config.json启动服务之后，Windows客户端通过配置可以连接该服务器。但是在另外一台本地的Ubuntu16.04上使用sslocal -c config.json连接远程服务时却连接不上，配置可以保证正确，且通过wireshark抓包发现本地的sslocal根本没有把数据送出去，网络是正常的并且可以ping通远程的vps

**Comment by raine0524** [comment]
而且在本地Ubuntu系统上安装shadowsocks-qt5，同样也无法连接远程vps，抓包显示也没有数据包送出去

**Comment by librehat** [comment]
Your local network problem. Check firewall settings

**Comment by abusizhishen** [comment]
不是不能使用，而是还需要要配置代理。
http://blog.csdn.net/superbfly/article/details/54950451

**Comment by SakueaAkira** [comment]
@librehat I got similar problem. I can connect my shadowsocks server via client on Windows and Android, but I can't get it work on Ubuntu. I have shutdown the firewall. Also I have configured proxy setting on firefox. But firefox just stuck at "TLS handshaking" and timeout soon. Both command-line version and qt5 version of ss have this problem on my PC.
