### ISSUE TITLE
appimage cannot startup on ubuntu1604

### ISSUE THREAD

**Issue by luoyanghero** [shadowsocks/shadowsocks-qt5#532]
sudo ./Shadowsocks-Qt5-x86_64.AppImage 
./Shadowsocks-Qt5-x86_64.AppImage: 2: ./Shadowsocks-Qt5-x86_64.AppImage: Syntax error: newline unexpected

$ ./Shadowsocks-Qt5-x86_64.AppImage 
./Shadowsocks-Qt5-x86_64.AppImage: line 1: syntax error near unexpected token `newline'
./Shadowsocks-Qt5-x86_64.AppImage: line 1: `<?xml version="1.0" encoding="UTF-8"?>'

**Comment by luoyanghero** [comment]
Have found the error, file not download completely.

**Comment by luoyanghero** [comment]
close

**Comment by librehat** [comment]
Also please don't run it with sudo!
