### ISSUE TITLE
ubuntu unstable

### ISSUE THREAD

**Issue by luoyanghero** [shadowsocks/shadowsocks-qt5#533]
I have two ssservers, one python version(a little old), one go version. I can stablely visit web in windows with python client or go client through any ssserver. On my cell phone, it is stable too.
But I cannot stablely visit web in ubuntu with go client and qt5 client. I checked the log info, cannot find any useful info. 
How can I find the problem why ubuntu so unstable?
Where can I find ubuntu python version client?

**Comment by librehat** [comment]
It's likely your systems problem

**Comment by luoyanghero** [comment]
local.py or http2sock5 will be ok?
