### ISSUE TITLE
CXXABI_1.3.8 not found on Ubuntu 14.04 trusty

### ISSUE THREAD

**Issue by probonopd** [shadowsocks/shadowsocks-qt5#534]
On Ubuntu trusty:

`/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-7996/usr/bin/../lib/libQt5Core.so.5)`

This is because some ppa pulls in a dependency on a "too new" libstdc++.so.6.

This would not happen if you would use https://launchpad.net/~beineri/+archive/ubuntu/opt-qt59-trusty instead of what you are using now.

This prevents the AppImage from being added to https://github.com/AppImage/AppImageHub

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266236585#L556

**Comment by librehat** [comment]
I didn't build the AppImage on Ubuntu 14.04. I used Debian Jessie.

Is Ubuntu 14.04 a hard requirement for the inclusion?

**Comment by probonopd** [comment]
It is a hard requirement for an AppImage  to run on the oldest still-supported Ubuntu LTS (currently 14.04) for inclusion in AppImageHub.

Otherwise it is not a requirement for making an AppImage.

**Comment by librehat** [comment]
I've now remade a new AppImage in 3.0.0 alpha version in Ubuntu 14.04 LTS.

**Comment by probonopd** [comment]
Triggered another test, https://travis-ci.org/AppImage/appimage.github.io/builds/304306245.

**Comment by probonopd** [comment]
With `https://github.com/shadowsocks/shadowsocks-qt5/releases/download/v2.9.0/Shadowsocks-Qt5-x86_64.AppImage` we are still getting `/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-7524/usr/bin/../lib/libbotan-1.10.so.0)`. Possibly you are installing a newer compiler in your 14.04 system from a PPA, which pulls in a newer `libstdc++.so.6`. Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 for how to work around this.

Example:
https://github.com/probonopd/audacity/blob/dc63bfe95031fef953cb0e41f818319dae9ccaa0/.travis.yml#L30-L32

**Comment by xykoflz** [comment]
agree with @probonopd.
AppImage alpha3 still have libstdc++ dependency problem.
maybe a clean centos 6.9 is a proper platform to build AppImage

**Comment by librehat** [comment]
That's with 2.9.0. The build that is from Ubuntu 14.04 is in the Dropbox link in 3.0.0alpha

**Comment by probonopd** [comment]
Dropbox link? Firstly, I don't see one in this ticket. Secondly, I doubt my automated test system can download from a Dropbox link. Can you post a plain HTML download link here please?

**Comment by librehat** [comment]
I'll release it here when 3.0.0 final version is out. Reopen the ticket

**Comment by librehat** [comment]
I need a newer compiler that supports C++14. Compiling a new GCC will have the application link with the new `libstdc++` which is not shipped in the old system anyway.
@probonopd is it OK if I bundle `libstdc++.so`?

**Comment by librehat** [comment]
I have bundled the `libgcc_s.so` and `libstdc++.so` into the latest release. Please check if it works for older systems. https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v3.0.0

**Comment by probonopd** [comment]
That is not a good idea. Please follow the instructions on https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by librehat** [comment]
OK. I've followed that and created a new AppImage. [Shadowsocks-Qt5-3.0.0-x86_64.AppImage](https://github.com/shadowsocks/shadowsocks-qt5/releases/download/v3.0.0/Shadowsocks-Qt5-3.0.0-x86_64.AppImage) should work then (it works on my Fedora 27 at least)

**Comment by librehat** [comment]
Consider fixed

**Comment by xykoflz** [comment]
Sorry for the information that problem not solved completely, at least for rhel/centos7.
On ubuntu or debian, new compiler package include libstdc++.so. 
But things on rhel/centos are different. The only libstdc++ version is 4.8.5 on rhel/centos7. 
New compiler that support C++14 or C++17 is supported by package rh-devtoolset-6 or rh-devtoolset-7, which **does not include libstdc++.so**. So, for rhel/centos7, the CXXABI problem still exist.

**Comment by librehat** [comment]
It was reported that the library was not correctly loaded. Reopen

**Comment by probonopd** [comment]
Yes, possibly related to or caused by https://github.com/darealshinji/AppImageKit-checkrt/issues/9

**Comment by artpolitov** [comment]
Hi

please take me info about shadowsocks-qt5 its work with SSR server? and how it configure for work with him?

(server & client based on ubuntu..)

**Comment by librehat** [comment]
Will fix it on #687
