### ISSUE TITLE
ss-qt5-v2.9.0-win64.7z，好像不好用

### ISSUE THREAD

**Issue by hironpan** [shadowsocks/shadowsocks-qt5#536]
首先感谢Github，感谢开发者。下面阐述问题：
win7系统，添加ss服务器参数后，连接，还是无法科学上网。（测试了另一款ss软件可以，但是需要.net 4.6.2，比较麻烦）
不知道是不是我使用方法不对。

**Comment by librehat** [comment]
看wiki，设置浏览器代理

**Comment by hironpan** [comment]
3q~~
