### ISSUE TITLE
general protection  in libQt5Core.so.5.5.1

### ISSUE THREAD

**Issue by UnsGentoals** [shadowsocks/shadowsocks-qt5#541]
[90938.808936] traps: ss-qt5[14998] general protection ip:7f0730e6bfb7 sp:7fffdd305430 error:0
[90938.808946]  in libQt5Core.so.5.5.1[7f0730bde000+4c5000]

**Comment by librehat** [comment]
What did you do to trigger this? What's your environment?

**Comment by UnsGentoals** [comment]
windows version
btsync proxy to ss
when connetion is too much,
will crash.
linux  version  
system proxy to ss
when connetion is  too much,
will crash. too.

**Comment by librehat** [comment]
Latest version of ss-qt5?

**Comment by UnsGentoals** [comment]
yes 。
Version 2.9.0
Using libQtShadowsocks 1.11.0

**Comment by UnsGentoals** [comment]
@librehat
may be dump file can help .
how to get the process dump file?
 where is the default location? 
thanks

**Comment by librehat** [comment]
I suspect it is similar to #205  which means the latest code should have fixed the issue. Please re-open it if it occurs with `ss-qt5 3.0.0`  and `libqtshadowsocks 2.0.1`
