### ISSUE TITLE
Unable to establish remote connection with Botan-2 in CFB mode

### ISSUE THREAD

**Issue by HelloIK** [shadowsocks/shadowsocks-qt5#542]
ss服务器没有问题，在其他系统下都可以使用，端口和浏览器代理设置也都没有问题，但是在Ubuntu运行的时候就会出现无法上网的问题：
  打开google时chrome提示无法访问此网站，同时ss-qt日志中显示的日志为 
  **Connecting www.google.com:443 from 127.0.0.1:39082
  Remote socket debug: The remote host closed the connection**

  此时若尝试强制使用ss代理打开百度，同样也会出现无法访问的问题 
  **Connecting www.baidu.com:443 from 127.0.0.1:39120
  Remote socket debug: The remote host closed the connection**

**Comment by UnsGentoals** [comment]
这个我认为是有可能是GWF引起的。

> [``](https://www.v2ray.com/blog/2017/design.html)
参考这个。

**Comment by BLumia** [comment]
尝试使用 `shadowsocks-libqss` 连接服务器，添加 `--debug` 参数并贴一下 log ？

**Comment by pengchujin** [comment]
archlinux 今天碰见了同样的问题、找不到原因。

**Comment by xgdgsc** [comment]
我升级后也出现这个问题，已降级：
```
warning: downgrading package libqtshadowsocks (1.11.0-1 => 1.10.0-3)
warning: downgrading package shadowsocks-qt5 (2.9.0-2 => 2.9.0-1)
```

**Comment by OliverLew** [comment]
同样有这个问题，archlinux，软件是最新版本。

**Comment by wuwenjie1992** [comment]
archlinux 下：
```
downgrade libqtshadowsocks
downgrade shadowsocks-qt5
```

降级选择使用libqtshadowsocks-1.10.0-3、shadowsocks-qt5-2.9.0-1

降级后能够正常使用，供大家参考哦 2017.9.1

**Comment by IadtsoftKun** [comment]
诸位，这个问题我暂时解决了，解决方法是换了一个新的ss服务器...；现在看来可能是服务器的配置存在问题，导致linux环境无法正常科学上网（？）；现在还在排查原先服务器，打算重新配置一遍，若发现解决方法再回来comment

**Comment by Nagisa2018** [comment]
似乎新的botan用aes-256-cfb会崩...不想降级的话换成chacha20好像就行了...再去研究研究...

**Comment by metorm** [comment]
同arch系(manjaro)表示今天（20170904）滚动升级后出现了一样的问题，换sslocal后好了。

```
✘  ~  curl baidu.com -x socks5://127.0.0.1:1080 --verbose

Rebuilt URL to: baidu.com/
Trying 127.0.0.1...
TCP_NODELAY set
SOCKS5 communication to baidu.com:80
SOCKS5 connect to IPv4 111.13.101.208 (locally resolved)
SOCKS5 request granted.
Connected to 127.0.0.1 (127.0.0.1) port 1080 (#0)
GET / HTTP/1.1 Host: baidu.com User-Agent: curl/7.55.1 Accept: /

Empty reply from server
Connection #0 to host 127.0.0.1 left intact curl: (52) Empty reply from server
✘  ~  curl baidu.com --verbose

Rebuilt URL to: baidu.com/

Trying 220.181.57.217...

TCP_NODELAY set

Connected to baidu.com (220.181.57.217) port 80 (#0)

GET / HTTP/1.1 Host: baidu.com User-Agent: curl/7.55.1 Accept: /

< HTTP/1.1 200 OK < Date: Mon, 04 Sep 2017 02:48:57 GMT < Server: Apache < Last-Modified: Tue, 12 Jan 2010 13:48:00 GMT < ETag: "51-47cf7e6ee8400" < Accept-Ranges: bytes < Content-Length: 81 < Cache-Control: max-age=86400 < Expires: Tue, 05 Sep 2017 02:48:57 GMT < Connection: Keep-Alive < Content-Type: text/html < <html> <meta http-equiv="refresh" content="0;url=&lt;a href=" http:="" <a="" href="http://www.baidu.com" rel="nofollow">www.baidu.com="" "="" rel="nofollow">http://www.baidu.com/"> </html> * Connection #0 to host

baidu.com left intact
~  curl -x socks5://127.0.0.1:1080 --verbose https://www.google.com/voice/

Trying 127.0.0.1...

TCP_NODELAY set

SOCKS5 communication to www.google.com:443

SOCKS5 connect to IPv6 200:2:807:c62d:: (locally resolved)

SOCKS5 request granted.

Connected to 127.0.0.1 (127.0.0.1) port 1080 (#0)

ALPN, offering h2

ALPN, offering http/1.1

Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

successfully set certificate verify locations:

CAfile: /etc/ssl/certs/ca-certificates.crt CApath: none

TLSv1.2 (OUT), TLS handshake, Client hello (1):

OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443

stopped the pause stream!

Closing connection 0 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443

✘  ~  curl -x socks5://127.0.0.1:1080 --verbose http://cn.bing.com/

Trying 127.0.0.1...
TCP_NODELAY set
SOCKS5 communication to cn.bing.com:80
SOCKS5 connect to IPv4 202.89.233.100 (locally resolved)
SOCKS5 request granted.
Connected to 127.0.0.1 (127.0.0.1) port 1080 (#0)
GET / HTTP/1.1 Host: cn.bing.com User-Agent: curl/7.55.1 Accept: /

< HTTP/1.1 400 Bad Request < Content-Type: text/html; charset=us-ascii < Date: Mon, 04 Sep 2017 02:58:04 GMT < Connection: close < Content-Length: 326 <

<html><head><title>Bad Request</title> <meta http-equiv="Content-Type" content="text/html; charset=us-ascii"></head> <body>
Bad Request - Invalid Verb

HTTP Error 400. The request verb is invalid.
</body></html> * Closing connection 0

```

**Comment by terryding77** [comment]
arch +1, qt5界面的shadowsocks不行， 命令行下同样配置的sslocal就能使用

**Comment by metorm** [comment]
也是最近两天更新的吗？

2017年9月4日 18:08，"terryding77" <notifications@github.com<mailto:notifications@github.com>>写道：

arch +1, qt5界面的shadowsocks不行， 命令行下同样配置的sslocal就能使用

**Comment by librehat** [comment]
Shadowsocks-Qt5 并不调用sslocal

**Comment by terryding77** [comment]
恩 就这两天， 刚刚试了降级`downgrade libqtshadowsocks ` Shadowsocks-Qt5 就能用了  看来应该是新升级的lib有哪里不对

**Comment by librehat** [comment]
不确定是否是arch 更新使用botan-2引起的，各位能否测试下载release页后缀_botan2的AppImage？

**Comment by Nagisa2018** [comment]
不知是不是因为新的libqt依赖了新的botan造成的

**Comment by CoREse** [comment]
Arch+1，更新后不能用了，已换用sslocal

**Comment by librehat** [comment]
就没有人下载AppImage测试是不是botan2的问题？

**Comment by terryding77** [comment]
release下的这个AppImage是内置libqtshadowsocks的吗 用这个测试，问题存在
> Remote socket debug: The remote host closed the connection

我arch降级了lib到1.10.0，release下的这个appimage用的依然是1.11.0的lib  
![image](https://user-images.githubusercontent.com/11759109/30085199-00600000-925b-11e7-8472-956cc899147a.png)

**Comment by TalesYuan** [comment]
UBUNTU 16.04 一台机器能用（16.04.1时安装的），一台新装的机器不能用，日志显示“远程主机关闭连接。请确认是否为socks5”

**Comment by librehat** [comment]
@terryding77 OK. It seems a problem of Botan-2 then

**Comment by librehat** [comment]
I can't reproduce this on my machine. I tried botan-2 build with `ChaCha20` and `AES-128-CTR`. What encryption methods are you using?

**Comment by xgdgsc** [comment]
`aes-256-cfb`

**Comment by terryding77** [comment]
aes-256-cfb
![image](https://user-images.githubusercontent.com/11759109/30238998-5b48d1ee-9518-11e7-88ac-64ec007aed92.png)

**Comment by librehat** [comment]
I believe this is a _bug_ in Botan-2 that breaks CFB ciphers. Please use different encryption method if possible or use botan-1.10

**Comment by baozilala** [comment]
Solved by change encryption method.

**Comment by et2010** [comment]
I got same issue. Downgrading libqtshadowsocks works for me.

**Comment by librehat** [comment]
Botan 2.3.0 has been released. This should no longer be an issue
