### ISSUE TITLE
关于扫描安卓分享二维码链接不上的问题

### ISSUE THREAD

**Issue by moska9417** [shadowsocks/shadowsocks-qt5#543]
状态显示已连接但延迟显示错误。并且链接不上google。测试手机可以做到。 

下面是日志
Initialising ciphers...
AES-128/CFB (aes-128-cfb) initialised.
Running in local mode.
TCP server listen failed.
Initialising ciphers...
AES-128/CFB (aes-128-cfb) initialised.
Running in local mode.
TCP server listen failed.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Initialising ciphers...
AES-128/CFB (aes-128-cfb) initialised.
Running in local mode.
TCP server listen failed.
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen failed.
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen failed.
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen failed.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Internet connectivity test failed. Please check the connection's profile and your firewall settings.
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState 
TCP server listen at port 19861
Internet connectivity test failed. Please check the connection's profile and your firewall settings.

**Comment by librehat** [comment]
检查是否端口被占用
