### ISSUE TITLE
Shadowsocks-Qt5无法识别、扫描和捕捉二维码图形文件

### ISSUE THREAD

**Issue by xq0404** [shadowsocks/shadowsocks-qt5#545]
These do not work: 
Add from QR code image file, scan QR code on screen or scan QR code using Capturer

使用版本：
Fedora 26 版本 3.24.2,
Shadowsocks-Qt5 版本 2.9.0

**Comment by librehat** [comment]
二维码图形文件是Android生成的吗？

**Comment by xq0404** [comment]
二维码图形文件是Windows的Shaowsocks 2.1.6形成的，成功被Android和Mac OS系统读取。

**Comment by librehat** [comment]
#527 duplicate

**Comment by xq0404** [comment]
Has the problem been resolved?
