### ISSUE TITLE
Debian-9 KDE下无法显示托盘，且timeout，且test lantency程序异常退出

### ISSUE THREAD

**Issue by dvoprm** [shadowsocks/shadowsocks-qt5#546]
![screenshot_20170903_170106](https://user-images.githubusercontent.com/23055579/30001757-cedaab76-90c9-11e7-90ab-10af3b7d8029.png)

以上是在普通用户下使用的情况，
下面是root：
当点击connect的时候，程序立即退出，并有以下文字：

> root@Ren:~# ss-qt5 
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  map::at
> Aborted
> root@Ren:~# 

OK,托盘问题可以在System Tray Settings里面把auto改为shown，但是还是无法成功连接，且会异常退出

写到最后，我使用了libQtshadowsocks 和 shadowsocks-qt5的 stable版本，已经稳定运行中。谢谢你。

**Comment by librehat** [comment]
Wiki里面多次提到不要编译master分支了。。。

**Comment by dvoprm** [comment]
抱歉。事实上我英语不太好，我得一行一行地读才能发现这个要点。不过我会努力学英语的。加油。
