### ISSUE TITLE
kali make error

### ISSUE THREAD

**Issue by chenpeng112288** [shadowsocks/shadowsocks-qt5#549]
[ 62%] Building CXX object src/CMakeFiles/ss-qt5.dir/sqprofile.cpp.o
cd /root/src/shadowsocks-qt5/obj-x86_64-linux-gnu/src && /usr/bin/c++  -DAPP_VERSION=\"2.10.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/root/src/shadowsocks-qt5/obj-x86_64-linux-gnu/src -I/root/src/shadowsocks-qt5/src -I/root/src/shadowsocks-qt5/obj-x86_64-linux-gnu/src/ss-qt5_autogen/include -I/usr/include/QtShadowsocks -I/usr/include/libappindicator-0.1 -I/usr/include/libdbusmenu-glib-0.4 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus  -g -O2 -fdebug-prefix-map=/root/src/shadowsocks-qt5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fPIC -std=gnu++11 -o CMakeFiles/ss-qt5.dir/sqprofile.cpp.o -c /root/src/shadowsocks-qt5/src/sqprofile.cpp
/root/src/shadowsocks-qt5/src/connection.cpp: In member function ‘void Connection::start()’:
/root/src/shadowsocks-qt5/src/connection.cpp:87:55: **error**: no matching function for call to ‘QSS::Controller::Controller(bool, bool, Connection*)’
     controller = new QSS::Controller(true, false, this);
                                                       ^
In file included from /usr/include/QtShadowsocks/QtShadowsocks:3:0,
                 from /root/src/shadowsocks-qt5/src/connection.h:23,
                 from /root/src/shadowsocks-qt5/src/connection.cpp:1:
/usr/include/QtShadowsocks/controller.h:42:5: note: candidate: QSS::Controller::Controller(const QSS::Profile&, bool, bool, QObject*)
     Controller(const Profile & _profile,
     ^~~~~~~~~~
/usr/include/QtShadowsocks/controller.h:42:5: note:   no known conversion for argument 1 from ‘bool’ to ‘const QSS::Profile&’
/root/src/shadowsocks-qt5/src/connection.cpp:100:17: **error**: ‘class QSS::Controller’ has no member named ‘setup’; did you mean ‘stop’?
     controller->setup(qssprofile);
                 ^~~~~
                 stop
[ 66%] Building CXX object src/CMakeFiles/ss-qt5.dir/settingsdialog.cpp.o
cd /root/src/shadowsocks-qt5/obj-x86_64-linux-gnu/src && /usr/bin/c++  -DAPP_VERSION=\"2.10.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/root/src/shadowsocks-qt5/obj-x86_64-linux-gnu/src -I/root/src/shadowsocks-qt5/src -I/root/src/shadowsocks-qt5/obj-x86_64-linux-gnu/src/ss-qt5_autogen/include -I/usr/include/QtShadowsocks -I/usr/include/libappindicator-0.1 -I/usr/include/libdbusmenu-glib-0.4 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus  -g -O2 -fdebug-prefix-map=/root/src/shadowsocks-qt5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fPIC -std=gnu++11 -o CMakeFiles/ss-qt5.dir/settingsdialog.cpp.o -c /root/src/shadowsocks-qt5/src/settingsdialog.cpp
src/CMakeFiles/ss-qt5.dir/build.make:281: recipe for target 'src/CMakeFiles/ss-qt5.dir/connection.cpp.o' failed
make[3]: *** [src/CMakeFiles/ss-qt5.dir/connection.cpp.o] **Error** 1
make[3]: *** 正在等待未完成的任务....
make[3]: Leaving directory '/root/src/shadowsocks-qt5/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:89: recipe for target 'src/CMakeFiles/ss-qt5.dir/all' failed
make[2]: *** [src/CMakeFiles/ss-qt5.dir/all] Error 2
make[2]: Leaving directory '/root/src/shadowsocks-qt5/obj-x86_64-linux-gnu'
Makefile:132: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/src/shadowsocks-qt5/obj-x86_64-linux-gnu'
dh_auto_build: make -j8 returned exit code 2
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by librehat** [comment]
Don't use master branch
