### ISSUE TITLE
Ubuntu, connected SS-server, but system proxy is not set

### ISSUE THREAD

**Issue by slrslr** [shadowsocks/shadowsocks-qt5#554]
Hello,

i am using Qt version 5.7.1 on my home PC Ubuntu 17.04

I connect remote SS server (shadowsocks-libev.x86_64 0:3.0.8-2.el6) from within the SS qt app and it shows Connected, shows latency, when i view log of the connection on client, i see:

```
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 10822
```

tcp        0      0 127.0.0.1:10822         0.0.0.0:*               LISTEN      2115/ss-qt5

and on remote:
tcp        0      0 serveriphere:8388            0.0.0.0:*                   LISTEN      1465/ss-server

But when i do command "curl https://cpanel.com/showip.shtml" from my home PC to discover my public IP, i see my real IP not SS server IP.

SS server side /etc/shadowsocks-libev/config.json:
```
 {
   "server":"ssserveriphere",
    "server_port":8388,
    "local_port":1080,
    "password":"pwhere",
    "timeout":60,
    "method":"aes-256-cfb",
    "verbose": -2
}
```

How i can please make it so the terminal and other system connections are made thru proxy, not directly?

**Comment by librehat** [comment]
You need to set your PC;s proxy yourself manually. Google and you'll find many manuals
