### ISSUE TITLE
shadowsocks-qt5 doesn't work 

### ISSUE THREAD

**Issue by SeAL80s** [shadowsocks/shadowsocks-qt5#558]
System: Arch x86_64
Chrome :ersion 61.0.3163.79 (Official Build) (64-bit)
SwitchyOmega:2.5.2
Shadowsocks-qt5 2.9.0
when SS-qt5 runs ,it shows "Shadowsocks connected",Test Latency also shows delay time .but i cann't visit any of the sites .google,youtube,twitter,cn.bing.com,it shows 

"This site can’t provide a secure connection
www.google.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH" 

The log shows :+1: Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 1080
Connecting www.google.com:443 from 127.0.0.1:47778
Initialising ciphers...
AES-256/CFB (aes-256-cfb) initialised.
Running in local mode.
TCP server listen at port 1080
Connecting www.google.com:443 from 127.0.0.1:47916
Connecting www.google.com.hk:443 from 127.0.0.1:47920
Connecting www.youtube.com:443 from 127.0.0.1:47924
Connecting beacons.gcp.gvt2.com:443 from 127.0.0.1:47928
Connecting clients4.google.com:443 from 127.0.0.1:47932
Connecting beacons.gvt2.com:443 from 127.0.0.1:47936
Connecting www.youtube.com:443 from 127.0.0.1:47940
Connecting beacons2.gvt2.com:443 from 127.0.0.1:47944
Connecting raw.githubusercontent.com:443 from 127.0.0.1:47948
Connecting www.youtube.com:443 from 127.0.0.1:47952
Connecting www.google.com.hk:443 from 127.0.0.1:47956
Connecting www.youtube.com:443 from 127.0.0.1:47962
Connecting www.google.com:443 from 127.0.0.1:47966

But ,when i run #sslocal -c /etc/shadowsocks/config.json ,it works fine .So,is it a Qt upgrade problem? My Qt version is 5.9

**Comment by fifths** [comment]
me too.
when i upgrade qt version

**Comment by Hacksign** [comment]
downgrade your libqtshadowsocks to  1.10.0
there is problem ss-qt5 working with libqtshadowsocks 1.11.0

**Comment by librehat** [comment]
If you're using Arch or Arch-based Linux, see #542
