### ISSUE TITLE
"Import from gui-config.json"未设置远端端口、本地IP和本地端口

### ISSUE THREAD

**Issue by cedric-sun** [shadowsocks/shadowsocks-qt5#562]
Ubuntu 16.04
从仓库wiki里提到的PPA安装了shadowsocks-qt5 2.9.0

在gui-config.json提供了server_port和local_port两个参数的情况下，[这个issue](https://github.com/shadowsocks/shadowsocks-qt5/issues/387)提到的问题仍然存在，而且remote端口也统一为0，控制台没有任何输出。
（疑似记得安装完后第一次导入一切正常，后续的导入操作就会出现端口的问题）

另外发2个Feature Request：
- 希望能一键清空服务器列表，加个弹窗确认防止误操作
- 希望本地IP能写host名，主要是localhost

Warm regards

Yours, Cedric

**Comment by librehat** [comment]
Can you provide a sample Gui-config.json?

**Comment by cedric-sun** [comment]
@librehat Sure, I pasted it in [this gist](https://gist.github.com/cedric-sun/d2592e4d97f08978e423baa5639376a0)

**Comment by zyf0330** [comment]
Happily to find this problem fixed.
