### ISSUE TITLE
about the wiki

### ISSUE THREAD

**Issue by longgangfan** [shadowsocks/shadowsocks-qt5#568]
cmake >= 3.1.0
    qt5-qtbase-gui >= 5.2 (qtbase5 in Debian/Ubuntu)
    qrencode (libqrencode in Debian/Ubuntu)
    libQtShadowsocks >= 1.10.0 (libqtshadowsocks in Debian/Ubuntu. **DON'T use the trunk code**)
    zbar (libzbar0 in Debian/Ubuntu)
    libappindicator (libappindicator1 in Debian/Ubuntu)
above is what in your wiki, it seems too old.

As you emphasized, I compiled libQtShadowsocks stable version(1.11.0), and installed them successfully. 

When it come to shadowsocks-qt5, I found no CMakeList.txt under the latest stable version. So I try to compile under master brunch. However, the master brunch need  libQtShadowsocks >= 2.0.0, and it the begin of nightmare.

First, when in the cmake step, FindPkgConfig.CMake just says "a required package not found". And cmake stopped there. After times of test and google, finally I know it is a bug in "cmake PkgConfig: Fix error not being printed when library version was specified",as  https://gitlab.kitware.com/cmake/cmake/commit/7d8618ab1bf4c782215831da27b0b893f433fe0a

After corrected cmake bug, I get the message, I need  libQtShadowsocks >= 2.0.0. However, I think the installed stable  libQtShadowsocks  version is 1.11.0. So I changed the CMakeList.txt version required.
But when it come to make, several bugs in the src file, finally I corrected all of them. And I installed it successfully.

I don't believe, there are so many bugs. I recompiled the  libQtShadowsocks in master brunch, and installed it. This time, when I compiled  shadowsocks-qt5 everything is OK, no bugs.

For short,NO.1 the stable version libQtShadowsocks not match the current master brunch shadowsocks-qt5; NO.2 cmake have bugs,and my version is 3.5; NO.3 shadowsocks-qt5 stable version have no CMakeList.txt.

**Comment by librehat** [comment]
No you can only use the stable version with stable version
You can build the master branch of libQtShadowsocks and the master branch of Shadowsocks-Qt5 but not mixing them.

Be aware that master is not stable and something may be broken 

The wiki will be updated once I'm happy with current master branches and release a new major version (3.0 for Shadowsocks-Qt5).

**Comment by librehat** [comment]
I updated the wiki after I migrated it to use cmake but it's not updated against the latest master branch

**Comment by longgangfan** [comment]
I know, Thank you. But please add CMakeList.txt for the stable brunch.

**Comment by librehat** [comment]
You can just use qmake

**Comment by kjian** [comment]
master branch with master is work
