### ISSUE TITLE
compile in debian, with the newest libqtshadowsocks, got the getSupportedMethodList() error

### ISSUE THREAD

**Issue by kilikao** [shadowsocks/shadowsocks-qt5#570]
error: request for member ‘data’ in ‘QSS::Common::version()’, which is of non-class type ‘const char*’
             .arg(QSS::Common::version().data());

error: ‘getSupportedMethodList’ is not a member of ‘QSS::Cipher’
     QList<QByteArray> methodBA = QSS::Cipher::getSupportedMethodList();

**Comment by librehat** [comment]
Don't use the latest. You  can only compile `master` branch with `master` branch
