### ISSUE TITLE
ss-qt5连接时测试延迟一直错误

### ISSUE THREAD

**Issue by lxglife** [shadowsocks/shadowsocks-qt5#572]
查看日志如下：
访问Google连接被拒绝，这个问题怎么解决呢？
Connecting google.com:80 from 127.0.0.1:52614
Remote socket error: Connection refused
Connecting www.jiegeng.com:80 from 127.0.0.1:52617
Connecting www.jiegeng.com:80 from 127.0.0.1:52618
Remote socket error: Connection refused
Remote socket error: Connection refused
Connecting google.com:80 from 127.0.0.1:52623
Local socket debug: The remote host closed the connection

**Comment by cedric-sun** [comment]
Refer to #571 for more information.

**Comment by lxglife** [comment]
请问这个问题什么时候能解决呢？或者有什么替代方案不？

**Comment by cedric-sun** [comment]
技术上没有解决方案，ISP把链路切了就是切了。
但是肯定没有切掉所有的国际出口，我能给出的唯一建议是问问别人有没有仍然可用的服务器分享一下。
