### ISSUE TITLE
ss-qt5 显示连上了 但是实际翻不了

### ISSUE THREAD

**Issue by TenzinJamyangZHS** [shadowsocks/shadowsocks-qt5#573]
system代理用autoproxy.pac
浏览器打开墙外网址直接显示 cant be reached 都没有加载

日志如下

Initialising ciphers...
ChaCha (chacha20-ietf) initialised.
Running in local mode.
TCP server listen at port 1080
Connecting www.google.con:443 from
127.0.0.1:49546
Connecting www.google.com:443 from
127.0.0.1:49550

求教大神 怎么解决
万分感谢

**Comment by cedric-sun** [comment]
Refer to #571 for more information.

**Comment by TenzinJamyangZHS** [comment]
@cedric-sun 我知道那天有断网的事 但现在 同一个服务器 win10 mac Android都能正常使用 唯独Ubuntu不行。

**Comment by cedric-sun** [comment]
日志上看不出啥问题，除了chacha20-ietf有点不常用...
