### ISSUE TITLE
在最新最新的archlinux下安装新版本ssqt5，并运行会出错。

### ISSUE THREAD

**Issue by amaothree** [shadowsocks/shadowsocks-qt5#574]
ss-qt5: error while loading shared libraries: libbotan-2.so.2: cannot open shared

botan这个包已经是最新。

**Comment by amaothree** [comment]
ss-qt5: error while loading shared libraries: libbotan-2.so.2: cannot open shared

**Comment by amaothree** [comment]
botan这个包已经是最新。

**Comment by KeyLD** [comment]
同，不过建立一个软链接可以应急

**Comment by librehat** [comment]
Please check with Arch packager. this is not related to this project

**Comment by ZhengshuaiPENG** [comment]
@KeyLD 请问如何建立这个软链接？

**Comment by Ldream** [comment]
@ZhengshuaiPENG  sudo ln -s /usr/lib/libbotan-2.so /usr/lib/libbotan-2.so.2

**Comment by amaothree** [comment]
@ZhengshuaiPENG 现在官方库里有botan1.10的单独包了，直接安装这个就好了，卸载新botan
