### ISSUE TITLE
加密方式没有 aes-256-gcm 怎么办？

### ISSUE THREAD

**Issue by saintthor** [shadowsocks/shadowsocks-qt5#578]
服务端是别人的，指明要用 aes-256-gcm。

**Comment by Chinternet** [comment]
由于 https://github.com/shadowsocks/shadowsocks-qt5/issues/448
所以，你现在得用其他支持AEAD的客户端。
windows可以用[shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows/releases)

**Comment by saintthor** [comment]
ubuntu  64bit 用什么？

**Comment by Chinternet** [comment]
只能用命令行了[go-shadowsocks2](https://github.com/shadowsocks/go-shadowsocks2)或[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)

**Comment by saintthor** [comment]
可以了。多谢。
