### ISSUE TITLE
ReleaseNote中添加libQtShadowsocks依赖的版本

### ISSUE THREAD

**Issue by joshuafc** [shadowsocks/shadowsocks-qt5#579]
Release版本：shadowsocks-qt5-2.9.0
在Ubuntu16.04编译时，下载了libQtShadowsocks-2.0.0alpha，无法通过编译。切换为libQtShadowsocks-1.11.0后编译正常
希望能在ReleaseNote 或 Readme.md中添加当前依赖库版本的说明。

**Comment by librehat** [comment]
2.0那边都已经标记是pre-release 了。
