### ISSUE TITLE
不支持gcm 以及POLY1305 加密方式么？ 

### ISSUE THREAD

**Issue by bcahlit** [shadowsocks/shadowsocks-qt5#581]
#### 我在Arch linux 下 使用此客户端，没有找到这几个 加密方式

**Comment by Chinternet** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/issues/578

**Comment by librehat** [comment]
还没有发布，master已经实现

**Comment by bcahlit** [comment]
好的，谢谢，
