### ISSUE TITLE
debian9.2可以打开，可以连接，但是当我使用浏览器把代理设置为对应的端口后，访问中国国内的网站没事，访问谷歌后程序就自动退出了，这不是巧合，因为每次都这样！！！

### ISSUE THREAD

**Issue by NoviceKang** [shadowsocks/shadowsocks-qt5#582]
debian9.2可以打开，可以连接，但是当我使用浏览器把代理设置为对应的端口后，访问中国国内的网站没事，访问谷歌后程序就自动退出了，这不是巧合，因为每次都这样！！！

**Comment by zdzliqian** [comment]
ubuntu 17.10也是這樣 不知道怎麼辦

**Comment by NoviceKang** [comment]
sudo apt-get install shadowsocks
sslocal -s 服务器地址 -p 服务器端口 -l 本地端端口 -k 密码 -m 加密方法

**Comment by aikangs** [comment]
对,我也是这个问题.因为我刚好在安装ruby环境,装了其他很多库,我还以为是库冲突,看来不是的. 我是ubuntu 16.04 我现在的解决方案是安装shadowsocks-python版本,然后命令行启动了.

**Comment by x1596357** [comment]
需要自己编一个botan2，然后编译使用botan2的libQtShadowsocks(cmake -DUSE_BOTAN2=ON)，然后把ss-qt5更新到用新的libQtShadowsocks。ppa源里面提供的是使用botan1.10，一旦有流量就会段错误，不知道是不是加密方式不支持的原因。
