### ISSUE TITLE
请问下Linux下配置文件被导入到了哪里

### ISSUE THREAD

**Issue by lingdage** [shadowsocks/shadowsocks-qt5#585]
主要原因是 我从gui-config.json导入后，服务端和本地端口都是0，路线又有将近20条，一个一个点开修改太累了，想直接找到配置文件，批量修改

**Comment by librehat** [comment]
文件格式不一样，Qt做了二进制编码，无法手动直接改。。

**Comment by cedric-sun** [comment]
#562 已修复
