### ISSUE TITLE
可以支持新的协议吗？

### ISSUE THREAD

**Issue by greyqz** [shadowsocks/shadowsocks-qt5#586]
如题。。。Shadowsocks 更新了新的协议

**Comment by hcder** [comment]
AES-256-CTR 会挂，win10系统

**Comment by librehat** [comment]
Dupe

**Comment by greyqz** [comment]
The newest version of SS-QT5 doesn't support aes-256-gcm. Sorry for not making things clear, but I really didn't want to dupe you.

**Comment by librehat** [comment]
Duplicate to #448
