### ISSUE TITLE
chacha20-ietf-poly1305 encryption method support

### ISSUE THREAD

**Issue by hanyihong0324** [shadowsocks/shadowsocks-qt5#587]
shadowsocks-libev suggest to use chacha20-ietf-poly1305 encryption method but shadowsocks-qt5 does not support this method yet.

**Comment by librehat** [comment]
Dupe. See other closed issues

**Comment by JeffCleverley** [comment]
Would be good to link to that issue... I've searched closed issues for the duplicate, is it in Chinese only?
