### ISSUE TITLE
Could you please add fedora 27 support in copr? 

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-qt5#588]
fedora 27 is scheduled to be released on the 30th day of this month.
Would you please add fedora 27 support?
Current my work around is to use the source of fedora 26 in repo file like below, and it works.
baseurl=https://copr-be.cloud.fedoraproject.org/results/librehat/shadowsocks/fedora-26-x86_64/

**Comment by librehat** [comment]
Will do before I release 3.0.0

**Comment by librehat** [comment]
Done
