### ISSUE TITLE
cant find duplicate issue for - chacha20-ietf-poly1305 support

### ISSUE THREAD

**Issue by JeffCleverley** [shadowsocks/shadowsocks-qt5#590]
Can't find the closed issue that this is a duplicate of...

searched is:closed for chacha20, nothing that I can see... could someone point me to the closed issue that explains about lack of support for this encryption please?

**Comment by ykelvis** [comment]
#569 
chacha20-ietf-poly1305 is one of the several encrypt method brought by AEAD \[0\], you could also use keywords: aes-256-gcm/aead , or check those issues labeled with "duplicate".
#448 is among the firsts on this subject. As of today, \[1\], the implementation has already been done on libshadowsocks, and there's a pre-release version for test. I think the release version won't be far away.

\[0\]: https://shadowsocks.org/en/spec/AEAD-Ciphers.html
\[1\]: https://github.com/shadowsocks/libQtShadowsocks/issues/126

**Comment by zyf0330** [comment]
I just compile v3.0.0 with libqtshadowsocks v2.0.0, but there is no `gcm` method, isn't it? So doesn't v3.0.0 include new encrypt method still?

**Comment by librehat** [comment]
You have to compile it with Botan2

**Comment by zyf0330** [comment]
I try botan2, and there is no new method appearing in the list of ss-qt5. Maybe I do something wrongly.
