### ISSUE TITLE
Debian下构建提示Unmet build dependencies: libqtshadowsocks-dev (>= 2.0.0)

### ISSUE THREAD

**Issue by CBM1014** [shadowsocks/shadowsocks-qt5#591]
### **使用dpkg-buildpackage -uc -us -b构建失败。**
>cbm@CBM-PC:~ $ cd git/shadowsocks-qt5
>cbm@CBM-PC:~ /git/shadowsocks-qt5$ dpkg-buildpackage -uc -us -b
>dpkg-buildpackage: info: source package shadowsocks-qt5
>dpkg-buildpackage: info: source version 2.9.0-1
>dpkg-buildpackage: info: source distribution stable
>dpkg-buildpackage: info: source changed by Symeon Huang <hzwhuang@gmail.com>
>dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build shadowsocks-qt5
dpkg-checkbuilddeps: error: Unmet build dependencies: libqtshadowsocks-dev (>= 2.0.0)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**libqtshadowsocks应该是最新版**

>cbm@CBM-PC:~/git/shadowsocks-qt5$ sudo apt install libqtshadowsocks
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
libqtshadowsocks 已经是最新版 (1.11.0-1)。
>升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。

**Comment by CBM1014** [comment]
问题已解决。
可以直接使用releases中的AppImage。

**Comment by liazylee** [comment]
怎么解决的，没懂。

**Comment by zanxj** [comment]
@liazylee @CBM1014 说的是在 [releases](https://github.com/shadowsocks/shadowsocks-qt5/releases) 中直接下载 Shadowsocks-Qt5-x86_64.AppImage ，按照使用说明，先修改该文件权限，即 chmod a+x Shadowsocks-Qt5-x86_64.AppImage
 然后直接执行该文件，即 ./Shadowsocks-Qt5-x86_64.AppImage 。
这个有点像 Windows 下的绿色版程序，可以直接打开运行。

**Comment by liazylee** [comment]
看来是我没加权限，导致运行无效果？
