### ISSUE TITLE
[Feature Request] Adding a startup option to daemonize this program

### ISSUE THREAD

**Issue by wzx1996** [shadowsocks/shadowsocks-qt5#592]
The only reason I choose to use this rather than C# version is to run a SS client on a server (and then allows other computers to access the proxy without a SS client). However, this version of SS has to run in interactive mode, and thus I can't install it as a service (Windows would consider that this "service" has never completed the starting up).

Linux server isn't an option so no "screen" program available (plus "screen" also isn't the best solution in this case). I don't want to enable startup program feature (since it's a server not a workstation), nor do I want to use a probably proprietary 3rd-party daemonizing program to do the job.

My only solution for now is to run the program as a never-ending scheduled task that is triggered on system startup, which isn't the best solution since it will not automatically restart after crashes.

So, would anyone implementing the feature that, when the program is run with "--service" parameter, it will run in background rather than occupying the terminal, so that daemonizing this program (run it as a Windows or Linux service) become possible?

**Comment by librehat** [comment]
You can configure it so it automatically hide the main window when it starts. See options in general settings

**Comment by wzx1996** [comment]
Isn't libqss version command line only? Also, just hiding the terminal window isn't enough (even scheduled task won't show a window at all). What I need is, make it so the program can run as a service (which requires it to be able to release rather than hide the terminal after successfully launched), so that it would be automatically restart after crashes, just like shadowsocks-libev on linux.

The fact that I have to use a Windows server shouldn't mean that I can't run shadowsocks as a service.

**Comment by librehat** [comment]
You're reporting the issue in Shadowsocks-Qt5 which is a GUI client app

**Comment by wzx1996** [comment]
Okay, my fault, I'm moving this issue to the libqt repo
