### ISSUE TITLE
ubuntu14.04下编译成功，但运行时有问题

### ISSUE THREAD

**Issue by leomatrix** [shadowsocks/shadowsocks-qt5#596]
ubuntu14.04下编译成功，但运行时有问题，命令行输出如下：
Starting /home/yang/rsssr/build-shadowsocks-qt5-Desktop_Qt_5_7_1_GCC_64bit-Default/src/ss-qt5...
Method rc2-cfb(RC2/CFB) is not supported by Botan: Could not find any algorithm named "RC2/CFB"
Method rc2-cfb(RC2/CFB) is not supported by Botan: Could not find any algorithm named "RC2/CFB"
Initialising cipher: chacha20-ietf-poly1305
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState
TCP server listening at 127.0.0.1:1080

windows下的 Shadowsocks.exe是可以使用的，说明的我的账号是没问题的！

**Comment by cushionXY** [comment]
各位老铁，ss-qt没有cgm的加密方式怎么破

**Comment by leomatrix** [comment]
ss-qt5的使用需要配合privoxy吗？

**Comment by librehat** [comment]
That is not an error. Just debug output.
