### ISSUE TITLE
Unmet build dependencies: libqtshadowsocks-dev

### ISSUE THREAD

**Issue by zanxj** [shadowsocks/shadowsocks-qt5#597]
Kali-rolling 已经安装最新版  libqtshadowsocks-dev , 但编译 shadowsocks-qt5 时依然提示  "**Unmet build dependencies: libqtshadowsocks-dev (>= 2.0.0)**" . 请求帮助，谢谢！

lilun@kali:~/Downloads/shadowsocks-qt5# sudo apt-get install qt5-qmake qtbase5-dev libqrencode-dev libqtshadowsocks-dev libappindicator-dev libzbar-dev libbotan1.10-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
libappindicator-dev 已经是最新版 (0.4.92-5)。
libbotan1.10-dev 已经是最新版 (1.10.17-0.1)。
libqrencode-dev 已经是最新版 (3.4.4-1+b2)。
libzbar-dev 已经是最新版 (0.10+doc-10.1+b1)。
qt5-qmake 已经是最新版 (5.9.1+dfsg-9)。
qtbase5-dev 已经是最新版 (5.9.1+dfsg-9)。
**libqtshadowsocks-dev 已经是最新版** (1.11.0-1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 76 个软件包未被升级。

lilun@kali:~/Downloads/shadowsocks-qt5# dpkg-buildpackage -uc -us -b
dpkg-buildpackage: info: source package shadowsocks-qt5
dpkg-buildpackage: info: source version 2.9.0-1
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by Symeon Huang <hzwhuang@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build shadowsocks-qt5
dpkg-checkbuilddeps: error: **Unmet build dependencies: libqtshadowsocks-dev** (>= 2.0.0)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by zanxj** [comment]
我发现问题原因了，直接 git clone 下来的版本是 1.11.0 提示需要2.0.0 ，这个版本目前还是 alpha 。该问题可以关闭了，谢谢！

**Comment by zanxj** [comment]
虽然问题已解决，但问题实际是出在 shadowsocks-qt5 开发人员。现在把我的解决办法贴出来。
在 git clone 下来的目录，即 libQtShadowsocks 目录，依次找到 debian --> control 文件，编辑两处内容（如下文本加粗部分）。
系统：Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux
本机安装成功，其它 Linux 系统未作测试，仅供参考！

Source: shadowsocks-qt5
Section: net
Priority: extra
Maintainer: Symeon Huang <hzwhuang@gmail.com>
Build-Depends: debhelper (>= 9),
               pkg-config,
               cmake (>= 3.1.0) | cmake3 (>= 3.1.0),
               qtbase5-dev,
               libqrencode-dev,
               **libqtshadowsocks-dev (>= 1.0.0)**,
               libzbar-dev,
               libbotan1.10-dev
Standards-Version: 3.9.6
Homepage: https://github.com/librehat/shadowsocks-qt5
Vcs-Git: https://github.com/librehat/shadowsocks-qt5.git
Vcs-Browser: https://github.com/librehat/shadowsocks-qt5

Package: shadowsocks-qt5
Architecture: any
Depends: ${shlibs:Depends},
         **libqtshadowsocks (>= 1.0.0)**
Description: A cross-platform shadowsocks GUI client
 Shadowsocks-Qt5 is a native and cross-platform shadowsocks GUI client
 with advanced features.

**Comment by librehat** [comment]
Sorry but I will no longer update PPAs. You can try appImage https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v3.0.0alpha
