### ISSUE TITLE
安装出现问题libqtshadowsocks-dev (>= 2.0.0)

### ISSUE THREAD

**Issue by bigV4** [shadowsocks/shadowsocks-qt5#598]
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build shadowsocks-qt5
dpkg-checkbuilddeps: error: Unmet build dependencies: (>= 2.0.0)
但是我从github里拿到的 libqtshadowsocks-dev最高就是1.11

**Comment by zanxj** [comment]
就是啊，我也正为这个问题苦恼呢。希望快点解决啊！
https://github.com/shadowsocks/shadowsocks-qt5/issues/597

**Comment by librehat** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v3.0.0alpha
