### ISSUE TITLE
AppImage Issue: CXXABI_1.3.8 and GLIBCXX_3.4.20 not found on CentOS 7.4

### ISSUE THREAD

**Issue by xykoflz** [shadowsocks/shadowsocks-qt5#600]
run appimage on CentOS7.4
`/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_ShadowUwu8YR/usr/bin/../lib/libQt5Core.so.5)`
`/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/.mount_ShadowUwu8YR/usr/bin/../lib/libbotan-2.so.2)`
`/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_ShadowUwu8YR/usr/bin/../lib/libbotan-2.so.2)`

check libstdc++.so.6:
`
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
`

BTW, the version of gcc on CentOS 7.4 is 4.8.5

**Comment by xykoflz** [comment]
Tried to compile sources with rh-devtoolset-6 and make the AppImage, the CXXABI problems solved.
So, for compatibility reason, would you please to compile the project on an older distribution? Thanks

**Comment by librehat** [comment]
I'll try to setup Travis to make AppImage in Ubuntu 14.04

**Comment by librehat** [comment]
Dupe: #534
