### ISSUE TITLE
GWF 截断SS之后，SS何时能升级？建议捐赠或者众筹模式，分担开发费用。开启新一代翻墙模式。

### ISSUE THREAD

**Issue by wulongji2016** [shadowsocks/shadowsocks-qt5#601]
GFW升级可以识别SS之后，SS何时能升级？魔高一丈道高一丈。
从以前的封IP，到DNS污染，到流量特征识别，防火墙不断进步。
翻墙方式也不断变化，现在该是再次升级的时候了。
一面是有资金，有技术，有政策支持的。
一面是无资金，无技术，无政策支持的散沙大众。
这个局，怎么破？

**Comment by wulongji2016** [comment]
一面是有资金，有技术，有政策支持的。
一面是无资金，无技术，无政策支持的散沙大众。
这个局，怎么破？

**Comment by wulongji2016** [comment]
很多企业，需要联系国外客户，各种软件无法使用，都影响正常外贸了。防火墙防止政治目的的翻墙，但是不应该禁止外贸正常使用吧？ 一刀切。不分青红皂白。
VPN还是需要白名单才能用。和大清朝禁止与外界来往一样开倒车。
不搞政治的学术研究和外贸应该有区别对待。

**Comment by h2y** [comment]
现在是什么情况，貌似没有被封呀。
