### ISSUE TITLE
chacha20-ietf-poly1305 support

### ISSUE THREAD

**Issue by gejianxin** [shadowsocks/shadowsocks-qt5#602]
Since GFW has been upgraded, many shadowsocks service provider upgraded their encryption method to chacha20-ietf-poly1305 to bypass GFW.
It would be great adding new encryption method chacha20-ietf-poly1305 support.

**Comment by liweisnake** [comment]
I need, too. Hope the author can add support

**Comment by wuchuguang** [comment]
I need, too. Hope the author can add support

**Comment by willis-hu** [comment]
need, too. Hope the author can add support

**Comment by librehat** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/releases/tag/v3.0.0alpha
