### ISSUE TITLE
If v3.0.0alpha need any prerequire?

### ISSUE THREAD

**Issue by xiekeyang** [shadowsocks/shadowsocks-qt5#607]
@librehat  My Ubuntu version is 17.04. I can't connect my shadowsocks server after running  shadowsocks-qt5 3.0.0alpha. The configuration should be correct. If it need any  prerequire? Thanks

**Comment by librehat** [comment]
What do you mean you can't connect? You need to setup proxy for your browser.
Start the AppImage from terminal and check the logs?
