### ISSUE TITLE
Ubuntu 16.0.4.3 LTS 切换到别的软件时闪退

### ISSUE THREAD

**Issue by aoxiangtianji** [shadowsocks/shadowsocks-qt5#608]
我其实是elementary OS 0.4.1 Loki 64bit的系统，不过基于Ubuntu 16.0.4.3 LTS制作的，也应该没关系，问题是我打开qt5之后连接好服务器，换到其他的软件时就崩溃掉了，托盘图标也不见了。

**Comment by librehat** [comment]
什么版本？AppImage?

**Comment by yxtj** [comment]
我也是。我发现问题是：当某一个服务器处于connected状态下，尝试链接另一个服务器，就会出现问题。如果先disconnect所有的链接，再链接其他的，就不会出现问题。

**Comment by gundamlh** [comment]
Ubuntu 14 LTS similar issue, the program stops quietly

**Comment by librehat** [comment]
使用最新正式发布的3.0.0版依然有此问题吗？因为各种库的版本问题，请确认AppImage版是否能够重现并重新开启此问题。
