### ISSUE TITLE
可以增加混淆方式的配置吗？

### ISSUE THREAD

**Issue by wangjunZeroZeroSeven** [shadowsocks/shadowsocks-qt5#609]
本人在www.hdsocks.com上买了一个账号，前段时间自动升级增加了一个混淆方式配置（比如配置混淆方式为 tls1.2_ticket_auth）。　升级以后，　这个软件就不能用了，　因为不支持配置混淆方式　。　相信很多人都在这个网上上买过，　请问能解决这个问题吗　？　：－）

**Comment by wangjunZeroZeroSeven** [comment]
以前在linux机器上用的好好的　：－）

**Comment by librehat** [comment]
No
