### ISSUE TITLE
Could you please support chacha20-ietf-poly1305 encryption way?

### ISSUE THREAD

**Issue by woniulive** [shadowsocks/shadowsocks-qt5#611]
windows client have supported this way?would you like to support this too?

**Comment by xuyuliang** [comment]
3.0 alpha has supported . you can downloaded it from 
https://www.dropbox.com/sh/nqo84eld4z3lwe4/AAAOk4uF84obVaBDQir0a8SLa?dl=0&lst=
or you can search this issue from closed issues and find the same answer by the developer himself.
下载上面那个链接（得翻墙）3.0 alpha 已经支持了，我已经用上了

**Comment by LukeEuler** [comment]
but i prefer fedora to mac and windows.
