### ISSUE TITLE
Can the application be compiled on windows devlopment environment?

### ISSUE THREAD

**Issue by hitvery** [shadowsocks/shadowsocks-qt5#613]
Hi, I tried to compile the Qt project on windows, because I want to build the exe file by myself. However, I found that is impossible... It seems some dependency library only for Linux system...And there is no package manager for windows so that manually add library is too complex.
I guess you use  MXE to release an exe file on Linux? Method such as [this site](https://askubuntu.com/questions/656219/building-a-windows-executable-in-qt-on-a-linux-system)?

**Comment by librehat** [comment]
You need to build dependencies yourself
