### ISSUE TITLE
提示`libstdc++.so.6: version `CXXABI_1.3.11' not found `

### ISSUE THREAD

**Issue by rigious** [shadowsocks/shadowsocks-qt5#614]
使用`./Shadowsocks-Qt5-v3.0.0alpha-amd64.AppImage`运行时提示错误如下：
```
~/Program/ss-qt5$ ./Shadowsocks-Qt5-v3.0.0alpha-amd64.AppImage 
./Shadowsocks-Qt5-v3.0.0alpha-amd64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /tmp/.mount_Shadow6e48xa/usr/bin/../lib/libbotan-2.so.3)
./Shadowsocks-Qt5-v3.0.0alpha-amd64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/.mount_Shadow6e48xa/usr/bin/../lib/libbotan-2.so.3)
```

**Comment by librehat** [comment]
什么系统版本？

**Comment by jjit** [comment]
我也是这个错误，系统是刚刚发布的Linux Mint 18.3 “Sylvia” Cinnamon 64位的
原因应该是系统自带的libstdc++版本太旧了
去官网下载新版：http://ftp.de.debian.org/debian/pool/main/g/gcc-7/libstdc++6_7.2.0-16_amd64.deb
用命令解压 ar -x libstdc++6_4.7.2-5_i386.deb && tar xvf data.tar.xz
把里面的2个文件 libstdc++.so.6 和libstdc++.so.6.0.24 复制到 /usr/lib/x86_64-linux-gnu/

**Comment by rigious** [comment]
Ubuntu 16.04 64bit

**Comment by EdwardYuan** [comment]
更新gcc, g++到4.9:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get upgrade

**Comment by ElunDai** [comment]
you should update your gcc and g++ to a higher version.
this work for me:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-6

sudo apt install g++-6

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6    

```

**Comment by librehat** [comment]
The system is too old... Ugh, I'm trying to build a new one using ancient Debian Wheezy now

**Comment by librehat** [comment]
It duplicated #534

**Comment by whuwangyong** [comment]
here: [http://www.cnblogs.com/duanguyuan/p/8871352.html](http://www.cnblogs.com/duanguyuan/p/8871352.html)
