### ISSUE TITLE
How to install shadowsocks-qt5 in kali linux?

### ISSUE THREAD

**Issue by beesuns** [shadowsocks/shadowsocks-qt5#615]
I run kali linux (Linux kali 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux) on a live usb drive. 
While I was trying to install shadowsocks-qt5, when I run 
# sudo add-apt-repository ppa:hzwhuang/ss-qt5
The following error message show:
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Kali/kali-rolling

I run 
# sudo apt-get install qt5-qmake qtbase5-dev libqrencode-dev libqtshadowsocks-dev libappindicator-dev libzbar-dev libbotan1.10-dev
The error message show:
E: Unable to locate package libqtshadowsocks-dev

So, how can I install shadowsocks-qt5 in kali linux.
Thanks!

**Comment by librehat** [comment]
I no longer maintain PPA

**Comment by lucoxlee** [comment]
i am asking too
