### ISSUE TITLE
chacha20-ietf-poly1305 not supported

### ISSUE THREAD

**Issue by lisu60** [shadowsocks/shadowsocks-qt5#616]
I followed the installation steps for [ubuntu](https://github.com/shadowsocks/shadowsocks-qt5/wiki/Installation#ubuntu) and tried to manually add a connection. There's no option for _chacha20-ietf-poly1305_ for the "Encryption Method" field, only _chacha20_ and _chacha20-ietf_.

**Comment by firehare** [comment]
me too

**Comment by EdwardYuan** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/releases

**Comment by huangyuyao** [comment]
Any suggestion of running `sslocal`  with *chacha20-ietf-poly1305*? 

Thx a lot.

```zsh
➜  shadowsocks-qt5 sslocal -c ss-japan-2.json                   
INFO: loading config from ss-japan-2.json
2019-07-28 09:36:45 WARNING  warning: your timeout 15 seems too short
2019-07-28 09:36:45 ERROR    method chacha20-ietf-poly1305 not supported
```
