### ISSUE TITLE
It does not work on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by MichaelShen97** [shadowsocks/shadowsocks-qt5#621]
I am using campus network in China. I can link to my Vultr VPS through shadowsocks on Windows, and have fluent access to blocked websites. However when I switch to Ubuntu 16.04LTS system with the same shadowsocks configuration, although the client shows the connection has been established, I cannot connect to Google/Twitter etc. I also tried command line
`sslocal -c config.json`
 but failed again. Any advice please?

**Comment by haotong1987** [comment]
me too.

**Comment by crazyxxl** [comment]
ubuntu17.10 ,occurred

**Comment by Alibinwahid** [comment]
I am also facing issues on ubuntu 16.04. I ran Shadowsocks-Qt5 application and loaded the gui-config.json file. It shows latency and connect to server but internet still not working. on windows it worked very well

**Comment by ykelvis** [comment]
Install SwithyOmega[1] and config proxy "socks5 127.0.0.1 1080".

1: https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif

**Comment by MichaelShen97** [comment]
Thank you! problem solved.

**Comment by waiting123** [comment]
I also have the same problem, it can't work on ubuntu16.04.

**Comment by librehat** [comment]
Read wiki before ask for help. This is not even a problem.

**Comment by fazzolini** [comment]
@librehat could you please refer to which wiki I should address to make it work on Ubuntu?

**Comment by librehat** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E7%9A%84%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE

**Comment by loveplay1983** [comment]
If you are using firefox in which it is the default browser on ubuntu 16.04, you will have to configure the network proxy -> click the option of "proxy DNS when using socks v5". 
This solved my problem when i first use ss on my ubuntu 16.04, by the way, i am also using and learning things while struggling to get the freedom of the network, pursuing master degree of my computer science right now, machine learning and deep learning needs a lot of thesis references out-of-the-boundary.
