### ISSUE TITLE
请教一下  如何配置obfs plugin呢？

### ISSUE THREAD

**Issue by Ricty** [shadowsocks/shadowsocks-qt5#625]
似乎ss-qt5的配置文件不是明文，然后GUI里没看到关于obfs的配置选项。如果要自行配置的话，是要单独安装obfs软件吗？
先谢谢啦~
OS:Linux Mint 18.2

**Comment by diyijing** [comment]
I change to use libev to resolve the problem

**Comment by librehat** [comment]
Not supported
