### ISSUE TITLE
无法打开'debian/changelog' 读取数据: 没有那个文件或目录

### ISSUE THREAD

**Issue by addsun** [shadowsocks/shadowsocks-qt5#629]
在kali linux安装时出现问题，版本：kali-linux-2017.3-amd64

root@kali:~# apt-get install qt5-qmake qtbase5-dev libbotan1.10-dev pkg-config debhelper
root@kali:~# cd Downloads/
root@kali:~/Downloads# git clone https://github.com/shadowsocks/libQtShadowsocks.git
root@kali:~/Downloads# cd libQtShadowsocks/
root@kali:~/Downloads/libQtShadowsocks# dpkg-buildpackage -uc -us -b
tail: 无法打开'debian/changelog' 读取数据: 没有那个文件或目录
dpkg-buildpackage: error: tail of debian/changelog subprocess returned exit status 1

求解决方法谢谢。

**Comment by librehat** [comment]
Deb Removed

**Comment by beyondalbert** [comment]
我也遇到这个问题，这个怎么解决，求！

**Comment by addsun** [comment]
@beyondalbert https://github.com/addsun/shadowsocks-qt5
