### ISSUE TITLE
The connection's profile is invalid

### ISSUE THREAD

**Issue by SomeoneDaniel** [shadowsocks/shadowsocks-qt5#630]
The error "The connection's profile is invalid" pops up after clicking the button 'Connect' on the Shadowsocks-Qt5 version 2.9.0. My configuration file is downloaded from the web portal.shadowsocks.la which should be correct. I suppose the problem is because the Qt5 is not support the method "chacha20-ietf-poly1305". Could you help on this problem? Thx.

**Comment by kingbase** [comment]
based on the source from: https://github.com/shadowsocks/shadowsocks-qt5/blob/master/src/connection.cpp#L44
you should have serverAddress / localAddress / timeout / method setted and correct before you start the connection.
