### ISSUE TITLE
编译的时候报qrencode.h库找不到

### ISSUE THREAD

**Issue by xz00311** [shadowsocks/shadowsocks-qt5#634]
编译的时候报qrencode.h库找不到

**Comment by x1596357** [comment]
装libqrencode-dev

**Comment by xz00311** [comment]
libqrencode-dev 请问这个在那里可以找到

**Comment by xz00311** [comment]
f:/Qt/Qt5.7.1/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lQtShadowsocks 提示这个错误郁闷中

**Comment by x1596357** [comment]
Windows啊，那得自己下源码编译咯。

**Comment by xz00311** [comment]
现在都编译了又出现其他问题了郁闷中,继续找其他库

**Comment by librehat** [comment]
I've given up on Windows (very difficult...). Good luck
