### ISSUE TITLE
连接成功，测试延迟88毫秒。就是无法访问google.com

### ISSUE THREAD

**Issue by githublaohu** [shadowsocks/shadowsocks-qt5#636]
操作系统是 ubuntu16.04.1
软件版本是 shadowsocks-qt5 (2.9.0-1+201707231936

状态为 已连接 
延迟86 毫秒
本地端口未1080

本地服务器类型是 scokss

请问下，才能访问 google.com

**Comment by MistEO** [comment]
linux下需要单独配置的，比如chrome可以装插件Proxy SwitchyOmega，可以自动切换啥的，具体的网上教程还比较多。或者Ubuntu可以直接进入`系统设置-网络-网络代理-方法手动-socks主机127.0.0.1 端口1080-应用到整个系统`来设置全局代理

**Comment by caizhixing** [comment]
我遇到了同样的问题 楼上的方法试了不管用 @githublaohu 你解决了没？

**Comment by dugreen** [comment]
我是连接成功，但是延迟测试失败，连接google.com会报这个错误Remote socket error: Connection refused。

**Comment by shenmijiabing** [comment]
我也是这样，也全局设置了127.0.0.1:1080 但是还是没办法，使用pip install shadowsocks 的方法，也没办法在Linux上访问google。但是在mac上面一切正常。

**Comment by caizhixing** [comment]
chrome浏览器安了proxy helper插件 并设置为系统代理（OS Manjaro）

**Comment by gallimaufrystew** [comment]
重连无线网 重起ss 端口号搞大点 5位数啥的~

**Comment by cap-ljf** [comment]
https://www.litcc.com/2016/12/29/Ubuntu16-shadowsocks-pac/index.html。
连接之后需要配置代理，可以参考上面这篇博客配置。

**Comment by yinglang** [comment]
this is work for me, you can try:
rm ~/.config/shadowsocks-qt5 -rf
re-run ss-qt5
