### ISSUE TITLE
如何让 shadowsocks-qt5 支持 chacha20-ietf-poly1305 加密协议？ 

### ISSUE THREAD

**Issue by ooof** [shadowsocks/shadowsocks-qt5#642]
如题

**Comment by tjbdzr** [comment]
@ooof : https://github.com/shadowsocks/shadowsocks-qt5/issues/595 This may help? use botan2! ![bitmoji](https://render.bitstrips.com/v2/cpanel/3da61372-6b79-4074-b68b-464741308118-32f268c7-4660-4cef-ba36-6b71e29153c1-v1.png?transparent=1&palette=1&width=246)

**Comment by speeedturtle** [comment]
我也想知道，网上没有教程出来
