### ISSUE TITLE
2.9版本，显示连接正常，也可以读到延迟数据，但是不能访问目标内容

### ISSUE THREAD

**Issue by lizhecome** [shadowsocks/shadowsocks-qt5#643]
看了下log，显示远端服务器连接终止，但是同样的ss服务器在windows和mac上使用正常

**Comment by tony88322** [comment]
遇到同样问题   一样的帐号配置 windows 正常使用  ubuntu 16.04.3 用不了

**Comment by librehat** [comment]
Check other issues and read more thanks
