### ISSUE TITLE
AppImage doesn't work

### ISSUE THREAD

**Issue by baimafeima** [shadowsocks/shadowsocks-qt5#644]
Could you add the AppImage file directly here on GitHub? I do not have access to Dropbox from China. Thank you. 

Update: I was able to download the AppImage file from Dropbox via a VPN. Nevertheless, there was no way for me to verify its authenticity. Could you make it available here? I have also tried to run `chmod a+x Shadowsocks-Qt5-v3.0.0alpha-amd64.AppImage` in a terminal without success and am not able to get it to run. Any help is greatly appreciated.

**Comment by librehat** [comment]
I will release 3.0.0 in following days along with an updated appimage file

**Comment by lickety** [comment]
[_能释放编译好的吗****_]( @ #url)

**Comment by librehat** [comment]
Check the new 3.0.0 appimage
