### ISSUE TITLE
Offer snap to circumvent zbar issue and in order to support cross-platform installation

### ISSUE THREAD

**Issue by baimafeima** [shadowsocks/shadowsocks-qt5#645]
Could you make `shadowsocks-qt5` available as a snap? I believe there would be added security benefits with full confinement and it could be used across a wide spectrum of Linux-based distributions. On Solus, for example, `shadowsocks-qt5 `currently cannot be built due to its dependency on `zbar`.

**Comment by librehat** [comment]
I've considered snap and flatpak but I then decided to go with AppImage for now. You can just use AppImage file if there is no one packaging it for your distribution.
