### ISSUE TITLE
Compile Instruction should be listed in detail

### ISSUE THREAD

**Issue by duxingzhe** [shadowsocks/shadowsocks-qt5#646]
As for build system has changed into cmake, the tutorial can't work for me anymore. I manage to follow the guideline on your wiki. [WIKI](https://github.com/shadowsocks/shadowsocks-qt5/wiki/Compiling) But it shows a lot of errors.
Could you please offer more detailed information about compilation for better understanding of installation?
Thx.

**Comment by librehat** [comment]
It should work with latest `3.0.0` release
