### ISSUE TITLE
请教下linux mint 17 ss-qt5为什么无法运行在普通用户权限下？

### ISSUE THREAD

**Issue by unknowncodez** [shadowsocks/shadowsocks-qt5#647]
linux mint 17 按照安装教程安装好后，直接通过图形界面启动ss-qt5 闪退，通过命令行sudo启动就能正常启动。这是正常的吗？有什么办法可以使得普通用户使用ss-qt5？谢谢！

**Comment by librehat** [comment]
Run `ss-qt5` from command-line see what you have in the terminal. It's likely that you have wrong permission in `~/.config/shadowsocks-qt5`

**Comment by unknowncodez** [comment]
(process:2568): Gtk-CRITICAL **: IA__gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:2568): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2568): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:2568): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:2568): GLib-GObject-WARNING **: value "TRUE" of type 'gboolean' is invalid or out of range for property 'visible' of type 'gboolean'

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:2568): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:2568): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:2568): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:2568): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:2568): Gtk-WARNING **: Screen for GtkWindow not set; you must always set
a screen for a GtkWindow before using the window

(process:2568): Gdk-CRITICAL **: IA__gdk_screen_get_display: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): Gdk-CRITICAL **: IA__gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(process:2568): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:2568): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2568): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:2568): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:2568): Gdk-CRITICAL **: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): Gdk-CRITICAL **: IA__gdk_screen_get_display: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2568): Gdk-CRITICAL **: IA__gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed

(process:2568): Gdk-CRITICAL **: IA__gdk_screen_get_number: assertion 'GDK_IS_SCREEN (screen)' failed
段错误

**Comment by unknowncodez** [comment]
我
chmod 777 shadowsocks-qt5/
也不行，是不是我理解错了？

**Comment by librehat** [comment]
什么版本？3.0删掉了appindicator所以这些乱七八糟的gtk消息应该就没了，试试运行最新3.0版？

**Comment by unknowncodez** [comment]
./Shadowsocks-Qt5-3.0.0-x86_64.AppImage 

ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ss-qt5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ss-qt5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQt5Widgets.so.5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQt5Network.so.5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQtShadowsocks.so.2)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQtShadowsocks.so.2)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQtShadowsocks.so.2)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQt5DBus.so.5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQt5Gui.so.5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQt5Core.so.5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQt5Core.so.5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libQt5Core.so.5)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libbotan-2.so.3)
ss-qt5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.mount_ShadowTbQXA7/usr/lib/libbotan-2.so.3)

是不是只有update gcc了？谢谢解答，感恩！

**Comment by librehat** [comment]
奇怪，按理应该可以执行的，因为我都打包了c++运行库了

**Comment by librehat** [comment]
Please follow #534
