### ISSUE TITLE
LIBS += -L./ -lqrencode -lQtShadowsocks -lbotan-$$BOTAN_VER -lzbar -liconv 编译出错

### ISSUE THREAD

**Issue by xz00311** [shadowsocks/shadowsocks-qt5#651]
:-1: error: cannot find -lqrencode
:-1: error: cannot find -lQtShadowsocks
:-1: error: cannot find -lbotan-1.10
:-1: error: cannot find -lzbar
collect2.exe:-1: error: error: ld returned 1 exit status
这个要到那里找啊

**Comment by gallimaufrystew** [comment]
build the dependencies...the docs mentioned it.
