### ISSUE TITLE
点击Test latency显示连接速度多少ms后随即变成Error

### ISSUE THREAD

**Issue by Kongsea** [shadowsocks/shadowsocks-qt5#652]
Ubuntu 16.04系统。
之前一直用的好好的，今天网络出了点问题，然后重启后，开启shadowsocks-qt5，进入进行Test latency时，在显示多少ms之后，随即变成Error。
而且也无法正常使用和访问外面的网络了。
麻烦给看一下原因吧，谢谢。

**Comment by librehat** [comment]
error表示你端口,密码或者加密方式不正确

**Comment by Kongsea** [comment]
问题是我这些都没有问题。
在安卓手机上都正常连接使用，而且用sslocal也能正常连接使用。

**Comment by librehat** [comment]
可以贴出你的配置截图吗？（请屏蔽掉敏感信息）。此外，请在终端里运行ss-qt5，这样可以看到日志输出

**Comment by gallimaufrystew** [comment]
this issues seems relate to linux wireless configuration...especially if
you use wicd,wireless will be unstable...recently i give up on wicd,using
wpa_supplicant instead..

**Comment by Kongsea** [comment]
@librehat 谢谢你，不过现在又好了。
好奇怪。

**Comment by steven1227** [comment]
我也遇到了这种情况。 有什么解决办法吗

**Comment by heirish** [comment]
same problem on centos 7, and it gives following error message:
```
[shadowsocks-qt5]$ ss-qt5

(ss-qt5:6633): GLib-GObject-WARNING **: 00:53:18.352: cannot register existing type 'GdkWindow'

(ss-qt5:6633): GLib-CRITICAL **: 00:53:18.352: g_once_init_leave: assertion 'result != 0' failed

(ss-qt5:6633): GLib-GObject-CRITICAL **: 00:53:18.352: g_type_register_static: assertion 'parent_type > 0' failed

(ss-qt5:6633): GLib-CRITICAL **: 00:53:18.353: g_once_init_leave: assertion 'result != 0' failed
The method "chacha20-ietf-poly1305" is not supported.
Could not find any algorithm named "chacha20-ietf-poly1305"

Aborted (core dumped)

```

**Comment by heirish** [comment]
rebuild from source, now it works, refer [begeekmyfriend's comment ](https://github.com/shadowsocks/shadowsocks-qt5/issues/595#issuecomment-341379655)
