### ISSUE TITLE
Segmentation fault on disconnect 

### ISSUE THREAD

**Issue by xgdgsc** [shadowsocks/shadowsocks-qt5#657]
on archlinux with libqtshadowsocks 2.0.1-2  and shadowsocks-qt5 3.0.0-1 . When I click to disconnect from a Timeout server, it crashes with Segmentation fault. When start in terminal, it shows:
```
$ ss-qt5 
Initialising cipher: salsa20
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState
TCP server listening at 127.0.0.1:1080
Connecting inbox.google.com:443 from 127.0.0.1:48234
Listen UDP socket state changed to QAbstractSocket::ClosingState
Listen UDP socket state changed to QAbstractSocket::UnconnectedState
Stopped.
Segmentation fault (core dumped)
```

**Comment by cloudhan** [comment]
Same problem here

**Comment by librehat** [comment]
Hmm interesting. Which Linux distribution? What's the botan version? Which encryption method you used?

**Comment by xgdgsc** [comment]
Just checked again, doesn' t happen now. Maybe system update fixed this.

**Comment by xgdgsc** [comment]
在manjaro上先是
```
$ ss-qt5  
malloc(): memory corruption
Aborted (core dumped)
```
然后我删除了`.config/shadowsocks-qt5/config.ini` 重新配置
现在是在一个正常连接的服务器上点disconnect会出现一样的`Segmentation fault (core dumped)`

**Comment by xgdgsc** [comment]
因为manjaro的community库用的libqtshadowsocks是对archlinux版本的qt编译的，https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/libqtshadowsocks  在这里下载PKGBUILD自己重新编译一下就行。

**Comment by xgdgsc** [comment]
https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/shadowsocks-qt5 还有这个也要安装libqtshadowsocks后一起重编译

**Comment by xgdgsc** [comment]
ubuntu 18.04下 ，用appimage的包也有这个崩溃的问题
