### ISSUE TITLE
No package 'QtShadowsocks' found

### ISSUE THREAD

**Issue by AllenIrving** [shadowsocks/shadowsocks-qt5#659]
I've compiled libQtShadowsocks-2.0.1 successfully follow the guides [here](https://github.com/shadowsocks/libQtShadowsocks/wiki/Compiling), but when I try to compile shadowsocks-qt5-3.0.0, an error says

> -- Checking for module 'QtShadowsocks>=2.0.0'
--   No package 'QtShadowsocks' found
CMake Error at /usr/local/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found

I've compiled libQtShadowsocks-2.0.1 successfully.
Any help would be appreciated!

**Comment by softpaopao** [comment]
我也遇到了这个问题 o.o
> -- The CXX compiler identification is GNU 7.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'QtShadowsocks>=2.0.0'
--   No package 'QtShadowsocks' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:24 (pkg_check_modules)

**Comment by librehat** [comment]
Where did you install libQtShadowsocks? It should be installed into /usr not /usr/local. Otherwise you need to set relevant environment variables for pkg config

**Comment by zjiekai** [comment]
@librehat It would be nice to have an example of how to set the environment variables

**Comment by nufeng74** [comment]
> 我也遇到了这个问题 o.o
> 
> > -- The CXX compiler identification is GNU 7.2.1
> > -- Check for working CXX compiler: /usr/bin/c++
> > -- Check for working CXX compiler: /usr/bin/c++ -- works
> > -- Detecting CXX compiler ABI info
> > -- Detecting CXX compiler ABI info - done
> > -- Detecting CXX compile features
> > -- Detecting CXX compile features - done
> > -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
> > -- Checking for module 'QtShadowsocks>=2.0.0'
> > --   No package 'QtShadowsocks' found
> > CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
> > A required package was not found
> > Call Stack (most recent call first):
> > /usr/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
> > CMakeLists.txt:24 (pkg_check_modules)

export PKG_CONFIG_PATH=/usr/lib/pkgconfig
