### ISSUE TITLE
加密方式是否可以加入chacha20-ietf-poly1305

### ISSUE THREAD

**Issue by caizirong** [shadowsocks/shadowsocks-qt5#663]

**Comment by aglent** [comment]
希望支持新的加密方式

**Comment by librehat** [comment]
最新版支持。

**Comment by wafflebee** [comment]
最新版是“v3.0.0”？
在Fedora，shadowsocks的Copr源安装的3.0.0版中没有chacha20-ietf-poly1305。

或者所谓最新版是git clone源码后编译得到的才能使用加密方法chacha20-ietf-poly1305?

**Comment by librehat** [comment]
@wafflebee it needs to be built with botan-2
