### ISSUE TITLE
SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5

### ISSUE THREAD

**Issue by lsnmx** [shadowsocks/shadowsocks-qt5#666]
SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5SB qt5

**Comment by deicol** [comment]
super best ?
thank .
i think so .
