### ISSUE TITLE
命令行客戶端 python "ERROR    method chacha20-ietf-poly1305 not supported"

### ISSUE THREAD

**Issue by xiongmaoshouzha** [shadowsocks/shadowsocks-qt5#668]
Ubuntu 17.10 
参考的 https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/6-linux-settings.md 命令行客戶端 设置
按照加密方式 aes-256-cfb 配置后，proxychains不能使用，所以使用我换成 chacha20-ietf-poly1305，就提示：method chacha20-ietf-poly1305 not supported

**Comment by librehat** [comment]
You need botan-2 build to use AEAD ciphers
