### ISSUE TITLE
can i try to add "shadowsocksr server subscription" for this software?

### ISSUE THREAD

**Issue by dcy10000** [shadowsocks/shadowsocks-qt5#673]
because linux don't have shadowsocksr.
I think  server subscription is very convenience for us.
Can i  add shadowsocksr server subscription for this software?
Is this allowed?
I will transplant this feature from shadowsocksr.
This is  compatible when shadowsockr set orgin and plain.

**Comment by librehat** [comment]
No. ShadowocksR is not part of Shadowsocks project
