### ISSUE TITLE
Double free pointer when connect/disconnect a server

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-qt5#675]
[core.zip](https://github.com/shadowsocks/shadowsocks-qt5/files/1802038/core.zip)

**Comment by PastoralPaladin** [comment]
Same error when I disconnecting server.

**Comment by toddleo** [comment]
Same issue here.

**Comment by librehat** [comment]
What is your environment? (Qt version, libQtShadowsocks version etc)

**Comment by librehat** [comment]
Try the latest versions and if it persists, re-open the issue
