### ISSUE TITLE
debian链接上了，但是好像不起作用，还应该如何设置？

### ISSUE THREAD

**Issue by digdig** [shadowsocks/shadowsocks-qt5#679]
同样的配置文件在其他系统都可以正常上，包括ios, windows,mac，但在debian 9.3下显示可以连接但是上不老网。
![screenshot from 2018-03-20 23-21-16](https://user-images.githubusercontent.com/5459093/37664152-b33ab6a0-2c95-11e8-898d-d88e43394406.png)

我还尝试了网上说的方法，在本地设置代理，结果什么网站也上不去了。
![screenshot from 2018-03-20 23-21-30](https://user-images.githubusercontent.com/5459093/37664182-c04129c4-2c95-11e8-9604-267e67b3ffb9.png)

**Comment by SachaYuri** [comment]
ubuntu 17.10也是一样

**Comment by deleteLater** [comment]
我按照网上找的教程，把SOCKS5改成HTTPS就可以

**Comment by xclidongbo** [comment]
我也是同样的问题。 虽然显示连接了， 但还是打不开谷歌。

**Comment by digdig** [comment]
@xclidongbo 看我的设置，以及你楼上的解决方法。

**Comment by xclidongbo** [comment]
@digdig 试过，已经OK了。谢谢。
