### ISSUE TITLE
installation on ubuntu

### ISSUE THREAD

**Issue by Ravi-Jay** [shadowsocks/shadowsocks-qt5#681]
I cannot find a way to install ss-qt5 on ubuntu. why? I remember it has some instructions in Wiki

**Comment by Helwolf** [comment]
you can find it in PPA?

**Comment by leaeasy** [comment]
@Ravi-Jay Please try this ppa - https://launchpad.net/~leaeasy/+archive/ubuntu/shadowsocks

**Comment by Aazingmiao** [comment]
@leaeasy 
sudo apt-get update
----snip----
E: 仓库 “http://ppa.launchpad.net/leaeasy/shadowsocks/ubuntu artful Release” 没有 Release 文件。

then how to open it?

**Comment by librehat** [comment]
PPA is no longer maintained by me.
