### ISSUE TITLE
全局代理没有效果

### ISSUE THREAD

**Issue by jasonlee3652** [shadowsocks/shadowsocks-qt5#685]
我是在Ubuntu 16.04上工作，我按照wifi的介绍，目前已经可以在chrome中访问google了，我现在想Android Studio这款软件也能用代理去下载一些文件，我在这款软件的设置中，设置了使用系统的代理(发现行不通，我后来也设置了SOCK5的方式，都不行)。我在系统设置>网络代理>设置了SOCK主机：127.0.0.1,端口1080。发现虽然是设置了全局代理，但是其他软件还是不能使用代理，除了chrome，因为给chorme安装了SwitchyOmega插件吗。如何让其他软件也能走代理呢

**Comment by githublaohu** [comment]
请问下。你如何在ubuntu16.04上做到的。我怎么配置都无法链接google

**Comment by githublaohu** [comment]
我按照https://blog.csdn.net/mynameis121/article/details/70191057 这个博客做的。

**Comment by jasonlee3652** [comment]
@githublaohu 你可以参照这篇博客
https://blog.csdn.net/yucicheung/article/details/79332049

**Comment by githublaohu** [comment]
多谢。
