### ISSUE TITLE
Clean uninstall Shadowsocks on Debian

### ISSUE THREAD

**Issue by oipewr** [shadowsocks/shadowsocks-qt5#686]
I installed Shadowsocks just to test, and then uninstalled it. After that, Firefox shows “The proxy server is refusing connections” . Even though I can choose "No Proxy" in Firefox network proxy setting, I'd like to know where did Shadowsocks change my system proxy settings and how can I reset it back to the default. Please help me.

**Comment by 1481767320** [comment]
Did you uninstall it with the command “apt purge shadowsocks”? Remove can not delete its data.

**Comment by oipewr** [comment]
Yes, I did.

**Comment by librehat** [comment]
I don't provide any binary package support except for Fedora
