### ISSUE TITLE
fail to start after update

### ISSUE THREAD

**Issue by jimgreen2013** [shadowsocks/shadowsocks-qt5#690]
error msg is as follow:
ss-qt5: malloc.c:4030: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted (core dumped)
my computer os is fedora 27

**Comment by librehat** [comment]
I'm using F27 as well but I don't see this issue... Can you run it in gdb and paste backtrace here?

**Comment by librehat** [comment]
I believe it has now been fixed
