### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by trdmm** [shadowsocks/shadowsocks-qt5#693]
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
已放弃 (核心已转储)

**Comment by flisky** [comment]
It happens on my Archlinux. Ubuntu 18.04 is okay.

**Comment by librehat** [comment]
I believe this has been fixed if you upgrade to the latest version

**Comment by psamim** [comment]
I am also on Archlinux and have the same problem with the latest release.

**Comment by cupen** [comment]
The general release install by typing `pacman -S shadowsocks-qt5` from  [`archlinux community repo`](https://www.archlinux.org/packages/community/x86_64/shadowsocks-qt5/) works fine.
