### ISSUE TITLE
fedora 24 ss-qt5 start error

### ISSUE THREAD

**Issue by liuyu5337** [shadowsocks/shadowsocks-qt5#696]
OS: fedora 24
error:ss-qt5: symbol lookup error: /lib64/libQtShadowsocks.so.1: undefined symbol: _ZN5Botan10get_cipherERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_10Cipher_DirE

**Comment by librehat** [comment]
Please upgrade your system which has met its EOL
