### ISSUE TITLE
crash when connecting

### ISSUE THREAD

**Issue by sycnanana** [shadowsocks/shadowsocks-qt5#697]
sometimes ss-qt5 crash and sometimes not ：(
---------------------------------------------------
__4.15.14-1-ARCH__
__shadowsocks-qt5 3.0.0__

console output:
```
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState
TCP server listening at 127.0.0.1:1080
free(): invalid pointer
```

**Comment by librehat** [comment]
I saw this error recently on Fedora as well and I believe it's caused by system ugprade. Try to rebuild ss-qt5
