### ISSUE TITLE
在ubuntu18.04lts上V3.0.0无法随机启动

### ISSUE THREAD

**Issue by zoo14** [shadowsocks/shadowsocks-qt5#699]
你好！
在最新的ubuntu18.04上，V3.0.0不能跟随系统启动，虽然我已经勾选了设置中的“登录时启动”选项。
如果以后能有根据IP选择是否代理的功能就更好了。
谢谢开发者作出的所有努力。
祝好！

**Comment by librehat** [comment]
It's an AppImage issue.
