### ISSUE TITLE
ubuntu 18.04 LTS 导入的配置.json,检测延时没有问题，连接显示“The connection`s profile is invalid！”

### ISSUE THREAD

**Issue by kidkey** [shadowsocks/shadowsocks-qt5#707]
服务器端版本是centos 6.9 (Final)  shadowsocks==3.0.0
`[root@iZj6chftd4ce4l5e8q1kmxZ ~]# cat `which ssserver`
\#!/usr/bin/python
 \# EASY-INSTALL-ENTRY-SCRIPT: 'shadowsocks==3.0.0','console_scripts','ssserver'
__requires__ = 'shadowsocks==3.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('shadowsocks==3.0.0', 'console_scripts', 'ssserver')()
    )
[root@iZj6chftd4ce4l5e8q1kmxZ ~]# `

客户端是 ubuntu 18.04 LTS  Shadowsocks-Qt5-3.0.0-x86_64.AppImage

**Comment by librehat** [comment]
Can't read your question
