### ISSUE TITLE
ubuntu16.04

### ISSUE THREAD

**Issue by Hemione521** [shadowsocks/shadowsocks-qt5#709]
您好，请问下我在ubuntu16.04系统上安装了qt5后，为什么编辑节点信息的时候没有auth_aes128_md5协议呢？
命令是：

sudo add-apt-repository ppa:hzwhuang/ss-qt5
sudo apt-get update
sudo apt-get install shadowsocks-qt5

**Comment by librehat** [comment]
That's not a Shadowsocks protocol.
