### ISSUE TITLE
Ubuntu 18.04 LTS 上 Shadowsocks-Qt5-3.0.0-x86_64.AppImage 运行失败

### ISSUE THREAD

**Issue by orbitingflea** [shadowsocks/shadowsocks-qt5#711]
./Shadowsocks-Qt5-3.0.0-x86_64.AppImage 
open dir error: No such file or directory

**Comment by xianzheTM** [comment]
提这种问题认真的？

**Comment by librehat** [comment]
Not related. Check FUSE and permission
