### ISSUE TITLE
请问 shadowsocks-qt5 可以设置插件吗

### ISSUE THREAD

**Issue by duaicxx** [shadowsocks/shadowsocks-qt5#713]
在服务端我设置了插件 但在qt5下我没找到插件的设置地方

**Comment by lery3510** [comment]
附议，kcptun监听本地换回地址所以server和local其实是同一个，但我之前用的老版本设置一直都不需要手动设置local地址而这里强制填写。

**Comment by librehat** [comment]
Not supported yet
