### ISSUE TITLE
Cannot configure the `Icon` attribute in .desktop file on Ubuntu 18.04

### ISSUE THREAD

**Issue by nvl2val** [shadowsocks/shadowsocks-qt5#714]
I use the AppImage release(V3.0.0) on Ubuntu 18.04. It cannot be added to the favorites directly, so I created a `.desktop` file. However, the `Icon` attribute cannot be configured. Is there any solution?

**Comment by librehat** [comment]
Worth checking the general tips around AppImage, the issue is not particular to this project
