### ISSUE TITLE
能够启动服务,且连接上服务器,但TCP监听服务启动失败,

### ISSUE THREAD

**Issue by beaquant** [shadowsocks/shadowsocks-qt5#715]
能够启动服务,且连接上服务器,但TCP监听服务启动失败
检查过端口占用情况,无其他程序占用我要使用的1080端口.
信息如下

echo $XDG_CURRENT_DESKTOP
Unity

./Shadowsocks-Qt5-3.0.0-x86_64.AppImage
Initialising cipher: aes-256-cfb
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState
TCP server listening at 127.0.0.1:1080
Initialising cipher: aes-256-cfb
Running in local mode.
TCP server listen failed.

**Comment by librehat** [comment]
It seems to me that you just opened the second connection that uses the same port
