### ISSUE TITLE
libcrypto(OpenSSL) not found

### ISSUE THREAD

**Issue by oeliok** [shadowsocks/shadowsocks-qt5#716]
shadowsocks.sslocal -s 127.0.0.1 -p 44563 -k password
2018-05-08 01:27:05 ERROR    libcrypto(OpenSSL) not found

系统环境
Linux oeli-xm 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

我已经安装了这个软件，依然有错
sudo apt-get install libssl-dev
sudo apt-get install openssl

**Comment by librehat** [comment]
Not related to this project
