### ISSUE TITLE
The App often crashes during disconnection of a server

### ISSUE THREAD

**Issue by csy530216** [shadowsocks/shadowsocks-qt5#718]
点击“断开连接”时，App有时会崩溃。比如说系统启动的时候设置自动启动该App且自动连接某服务器，断开连接时App会崩溃退出。但重启App之后再断开该连接，一般就不会崩溃了。
从终端运行该App，尝试了几次，崩溃的时候显示“段错误（核心已转储）”。dmesg信息：
`ss-qt5[2140]: segfault at 0 ip 00007f6090caf209 sp 00007ffc092c78a0 error 4 in libQtShadowsocks.so.2[7f6090c33000+ad000]`

System: Ubuntu 18.04

**Comment by fabaff** [comment]
I see the same behavior on Fedora. 

```bash
$ ss-qt5
Initialising cipher: rc4-md5
Cannot look up the host records of server address v:1117. Please make sure your Internet connection is good and the configuration is correct
Running in local mode.
TCP server listening at 127.0.0.1:1080
Stopped.
double free or corruption (!prev)
Aborted (core dumped)
```

**Comment by iwanderer** [comment]
这个问题从很久开始就一直存在，断开连接经常会报错：

> 段错误(核心已转储)

**Comment by tydlwav** [comment]
Same behavior on Arch Linux. 
`qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: yes
Initialising cipher: aes-256-cfb
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState
SOCKS5 port is 35913
Running as a HTTP proxy server
TCP server listening at 127.0.0.1:1080
Listen UDP socket state changed to QAbstractSocket::ClosingState
Listen UDP socket state changed to QAbstractSocket::UnconnectedState
Stopped.
double free or corruption (!prev)
[1]    19874 abort (core dumped)  ss-qt5`

**Comment by librehat** [comment]
This happened to me today and it got fixed by upgrading to latest libQtShadowsocks and ss-qt5 which I just released. Please re-open if the problem persists

**Comment by csy530216** [comment]
I faced some errors when compiling v3.0.1, which seems not direct to solve (for example I need to install many dependencies). Could you kindly release an AppImage like v3.0.0? Very thanks!
By the way, I cannot reopen the issue:)

**Comment by librehat** [comment]
@csy530216 I'll make an AppImage soon, thanks
