### ISSUE TITLE
KDE桌面环境无法启动

### ISSUE THREAD

**Issue by iPeven** [shadowsocks/shadowsocks-qt5#719]
如题，Archlinux KDE无法启动软件

**Comment by iPeven** [comment]
已通过自行编译安装解决

**Comment by muzi-8** [comment]
@iPeven 你好,我的系统是linux16.04,然后查看了一下使用的桌面环境是gnome,在我的系统下面也无法启动.AppImage,然后我尝试源码编译,首先 cmake ./CMakeList.txt,生成makefile文件,之后编译 make,但是出现问题: 如下fatal error:QApplication:没有那个文件或目录
这个问题如何解决呢?谢谢!

**Comment by iPeven** [comment]
你参考wiki来: https://github.com/shadowsocks/shadowsocks-qt5/wiki/Compiling

**Comment by muzi-8** [comment]
@iPeven 谢谢你的回复，我最终还是通过双击.AppImage应用程序安装的，之前不能安装的原因在于没有权限， 参考了问题#644，添加了权限，之后就可以安装了。再次谢谢你！
