### ISSUE TITLE
Crash in Fedora 28 x64

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-qt5#722]
Version 3.0.0
Using libQtShadowsocks 2.0.2

within Fedora 28 x64 crashes when connecting to a server.

**Comment by rewqazxv** [comment]
It seems that this problem has been fixed in the latest code. Try to clone and compile it?

**Comment by GitatHub** [comment]
thanks.
I found the crash tended to occur after system update, and a reboot could solve this mostly.

**Comment by fabaff** [comment]
I guess that we are looking at the same [issue](https://github.com/shadowsocks/shadowsocks-qt5/issues/718#issuecomment-388566458).

**Comment by fabaff** [comment]
Also, https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/ seems out-dated. If the issue was resolved then an update is needed.

**Comment by rewqazxv** [comment]
Yes, latest code has fixed crash problem and add AEAD ciphers support (libQTShadowsocks compiling with botan2). Require updates for fedora copr.

![ss](https://user-images.githubusercontent.com/24662041/40321207-e0c01a60-5d60-11e8-84ba-fd59752b8b8e.png)

**Comment by librehat** [comment]
I'm not sure why this issue has started to happen, it crashed on my Fedora 27 as well. However, it disappears after I re-compile `ss-qt5`. I've released a new version, so a `dnf upgrade` should fix your problems.
