### ISSUE TITLE
在系统托盘上图标，点击不会弹出界面，会关闭程序

### ISSUE THREAD

**Issue by n0tHappy** [shadowsocks/shadowsocks-qt5#727]
我的系统是arch,用的kde桌面，设置的开机启动，隐藏到系统托盘，现在是点击托盘上的图标后无法弹出界面，想看看流量什么的都不可以，右键点击后有两个选项，一个是恢复，一个是退出，无论选哪个，都是退出。想知道怎么解决，拜托了

**Comment by vic-feng** [comment]
You can try it:
https://github.com/kooritea/electronic-wechat

**Comment by librehat** [comment]
@vic-feng Totally unrelated comment

@n0tHappy Can you stop it, and run it from terminal, check what is the issue when you click the icon in the system tray?

**Comment by n0tHappy** [comment]
@librehat when I run it from terminal:
```
$ ss-qt5
Initialising cipher: aes-256-cfb
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState
TCP server listening at 127.0.0.1:1080
corrupted size vs. prev_size
[1]    2022 abort (core dumped)  ss-qt5

```
