### ISSUE TITLE
请添加chacha20-ietf-poly1305加密方式选项

### ISSUE THREAD

**Issue by zaxtseng** [shadowsocks/shadowsocks-qt5#729]
因为我的SS是chacha20-ietf-poly1305加密方式，而现有版本没有所以连不上

**Comment by AllenMRbai** [comment]
我在ubuntu17.10上安装的Shadowsocks-Qt5-3.0.1-x86_64.AppImage能打开。但是连接后还是无法翻墙。我的加密方式也是chacha20-ietf-poly1305。

**Comment by JerrySheh** [comment]
如果你之前用apt安装了旧版本，先用 apt remove 卸载。 然后下载 release 里面的 Shadowsocks-Qt5-3.0.1-x86_64.AppImage ， chmod +x 添加执行权限后直接打开， 就有 chacha20-ietf-poly1305 加密方式可选了
