### ISSUE TITLE
Is 32 bit Kali can run Shadowsocks-Qt5-3.0.1-x86_64.AppImage ?

### ISSUE THREAD

**Issue by shangdiaibide** [shadowsocks/shadowsocks-qt5#739]
Is 32 bit Kali can run Shadowsocks-Qt5-3.0.1-x86_64.AppImage ?
I get a problem , Can't open the file , I find My os is 32 bit Kali , Do you think this is the problem , thanks for answer !

**Comment by librehat** [comment]
No. It's "x86_64" so 64-bit
