### ISSUE TITLE
Botan2-2.7.0 causes shadowsocks-qt5 to fail to start

### ISSUE THREAD

**Issue by TaoistFox** [shadowsocks/shadowsocks-qt5#741]
Today, after I performed a system update on my fedora 28, shadowsocks-qt5 could not be started. Using ss-qt5 in the terminal showed that libbotan-2.so.5 was missing, and finally botan was downgraded before returning to normal. Hope to fix this problem

PS：Now it seems that the easier way to solve this problem is to create a soft link to link the missing library files with the latest library files. If you want to solve them perfectly, you need to modify them on the code.

**Comment by gshen42** [comment]
Same problem, the botan shared library on my Fedora 28 is libbotan-2.so.7, does the last version number matter?

**Comment by TaoistFox** [comment]
@gshen42 Hello, I made a soft link according to your supplement, the software seems to work normally, but I don't know if there will be other problems, it is better to fix this problem on the source level.

**Comment by punkmonday** [comment]
Same problem, fedora28 update to linux4.17.4,then crach.
ss-qt5: error while loading shared libraries: libbotan-2.so.5: cannot open shared object file: No such file or directory

**Comment by TaoistFox** [comment]
@punkmonday The problem is not in the kernel. After the system upgrade, the version of Botan is higher than the version required by ss-qt5. You can create a soft link to libbotan-2.so.5 or return botan to the previous version. I wish you success

**Comment by punkmonday** [comment]
`ln -s /usr/lib64/libbotan-2.so.7 /usr/lib64/libbotan-2.so.5 ` 
workaround,thank you!

**Comment by Triple-Z** [comment]
![image](https://user-images.githubusercontent.com/16285716/42734410-1a5670ae-8876-11e8-81be-ebb9f78d73ad.png)

same problem.

**Comment by jiqing112** [comment]
Thank you very much, I also encountered this problem, based on this issue to solve the problem, thank you very much

**Comment by TaoistFox** [comment]
@jiqing112 不用谢，都是因为有问题才会去找解决方法^_^

**Comment by jiqing112** [comment]
我擦自己人阿

**Comment by jiqing112** [comment]
其实我是装双系统不小心把windows的引导给覆盖了，进不去windows了
其实我还想问问怎么用ssr不，我在vultr上好像用的秋水大神的脚本一键搭建的ssr，搭建成功也可以上谷歌，在fedora上找客户端愁死了。
试了https://www.jianshu.com/p/a85542348fa2
但是一些参数始终不明白怎么回事

**Comment by TaoistFox** [comment]
@jiqing112 这个事情直接在聊天软件上讨论好了@v@

**Comment by jiqing112** [comment]
解决了。聊天软件上都是吹牛比的，还是得靠自己阿。在正册河蟹之下找一些敏感内容可真不容易
https://github.com/FelisCatus/SwitchyOmega/releases

https://blog.csdn.net/huangbin123/article/details/80826933

https://blog.csdn.net/shouldnotappearcalm/article/details/77900399

**Comment by suuuummer** [comment]
非常感谢！我也用你的方法解决了问题！

**Comment by librehat** [comment]
Fedora keeps breaking this.. :( There is no workaround but to trigger a rebuild of the software. I'll make a new build in COPR

**Comment by librehat** [comment]
Upgrade your Fedora and the symbolic link to `.5.so` should not be required any longer.
