### ISSUE TITLE
Linux Mint Sylvia, AppImage appears to work but is not used.

### ISSUE THREAD

**Issue by mei-iirose** [shadowsocks/shadowsocks-qt5#744]
after successfully connecting to my server vpn, toolbar and all are saying good to go, yet dnsleak.net still shows my ISP IP and other info. tried multiple browsers, all seem to ignore the vpn.

Linux Mint Sylvia w/ Cinnamon

**Comment by IvanTurgenev** [comment]
same

**Comment by IvanTurgenev** [comment]
it seems you need to connect to the proxy locally after the set up is done, i am using xubuntu and only gnome has the network proxy settings there are some workarounds, setting the proxy per app firefox etc or try this
https://askubuntu.com/questions/150210/how-do-i-set-system-wide-proxy-servers-in-xubuntu-lubuntu-or-ubuntu-studio

**Comment by mei-iirose** [comment]
either doing something wrong in following that guide or the problem is somewhere else... still same issue

**Comment by IvanTurgenev** [comment]
you wanna router your whole connection?

**Comment by mei-iirose** [comment]
right, i dont have wrt on my router though so it needs to be done using this project. unless there is a terminal based client that can do the job, im not opposed to lacking gui

**Comment by mei-iirose** [comment]
right, i dont have wrt on my router though so it needs to be done using this project. unless there is a terminal based client that can do the job, im not opposed to lacking gui

**Comment by IvanTurgenev** [comment]
you are better of chaging to ubuntu which has UI for proxies, or setting up a VPN is harder but easier on the cleint side

**Comment by librehat** [comment]
You need to configure your applications (browser etc) to use the local proxy run by `ss-qt5`. `ss-qt5` does not change system settings automatically
