### ISSUE TITLE
AppImage文件无法执行

### ISSUE THREAD

**Issue by githublaohu** [shadowsocks/shadowsocks-qt5#763]
操作系统为 ubuntu18.0.4  64位
异常为
Something went wrong trying to read the squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory

是否要安装wine？

**Comment by librehat** [comment]
Check the requirement of AppImage and read the link
