### ISSUE TITLE
Ubuntu下连接成功，配置switchyomega代理和端口，一连接就变成下载文件了

### ISSUE THREAD

**Issue by Scheinin** [shadowsocks/shadowsocks-qt5#787]
**switchyomega**的代理**地址**和**端口**都根据所给配置，一打开需要代理的网址就下载文件，GUI能看见流量的使用

**Comment by Scheinin** [comment]
已解决,是我把SS和SSR弄错了

**Comment by pandadreamer** [comment]
@Scheinin 我也碰到一代理就生成generate_204文件，请问shadowsocks-qt5应该是SS吧，想知道您怎么解决的，谢谢

**Comment by Scheinin** [comment]
@pandadreamer 我改用了这个[https://github.com/ssrbackup/shadowsocksr](url)
