### ISSUE TITLE
lubuntu18.04  打开shadowsocks-qt5显示连接成功，但依然不能访问google

### ISSUE THREAD

**Issue by xinyangmaojian** [shadowsocks/shadowsocks-qt5#789]
如题

**Comment by xinyangmaojian** [comment]
linux小白，烦请大神协助。
是否某些未正确设置某些选项？

**Comment by TaoistMo** [comment]
> Linux的小白，烦请大神协助。
> 是否某些未正确设置某些选项？

请问你是用什么浏览器

**Comment by xinyangmaojian** [comment]
> > Linux的小白，烦请大神协助。
> > 是否某些未正确设置某些选项？
> 
> 请问你是用什么浏览器

lubuntu安装后自带的火狐

**Comment by TaoistMo** [comment]
> > > Linux的的小白，烦请大神协助。
> > > 是否某些未正确设置某些选项？
> > 
> > 
> > 请问你是用什么浏览器
> 
> lubuntu安装后自带的火狐

火狐的话你可以先在GitHub里寻找并下载个SwitchyOmega，方便设置；或者你也可以在浏览器的设置里的链接到国际互联网选项里设置

**Comment by xinyangmaojian** [comment]
> > > > Linux的的小白，烦请大神协助。
> > > > 是否某些未正确设置某些选项？
> > > 
> > > 
> > > 请问你是用什么浏览器
> > 
> > 
> > lubuntu安装后自带的火狐
> 
> 火狐的话你可以先在GitHub里寻找并下载个SwitchyOmega，方便设置；或者你也可以在浏览器的设置里的链接到国际互联网选项里设置

感谢感谢
我还想再找一种全局代理的方式，因为有时候会用命令行pull些东西，没代理可能很慢或者会失败

**Comment by xinyangmaojian** [comment]
全局代理暂时先放一边，下边是我浏览器种成功科学上网的过程：
1.下载shadowsocks-qt5并成功连接节点
2.浏览器中下载SwitchyOmega插件
3.SwitchyOmega使用时的配置参照内容：https://zhidao.baidu.com/question/618412421043248852.html?fr=iks&word=SwitchyOmega+%C5%E4%D6%C3&ie=gbk

然后科学上网了。。。。。。。
