### ISSUE TITLE
[UBUNTU] Download processes are interrupted very frequently

### ISSUE THREAD

**Issue by PhanTask** [shadowsocks/shadowsocks-qt5#794]
Very useful tools. Thanks. I tried this and found out this software is very powerful. I connected my VPS via ss-qt5 and it works really well. I can go Utube and google without any problem.
However, when I tried to download some files, my download processes are interrupted very frequently so I cannot even download one single complete file.
I tried the download tools embedded in Chrome and Firefox, and none of them could keep the download process going. The connection would be broken within 5 seconds.
I also tried proxychain + wget. No help. Sad.
I even tried ss-qt5 on another computer(Ubuntu 16.04), which encountered the same situation.
I think it won't be my server's problem since it works fine when I connect it from a Windows system.
Could you help me to figure out what the problem is?

My OS is Ubuntu 18.04 64 bit LTS.
Connection: SOCKS5
crypto: CHACHA20-IETF-POLY1305

**Comment by keai4le** [comment]
Start it in terminal and see the output of logs may help to provide more info.

**Comment by PhanTask** [comment]
@keai4le Thank you for your answer. It turned out that the problem is caused by CHACHA20-IETF-POLY1305. I replaced it with aes-256-cfb encryption method and it works fine now.
