### ISSUE TITLE
如何验证shadowsocks-qt5已连接上服务器

### ISSUE THREAD

**Issue by noodlesZheng** [shadowsocks/shadowsocks-qt5#829]
环境：Ubuntu18.4.3+shadowsocks-qt5Version 2.9.0+本机wifi环境
问题描述：根据配置说明已经连接上服务器，界面显示已连接，延迟稳定在70毫秒左右，Ubuntu系统设置里将代理改为手动，socks这项改为127.0.0.1，端口1080。chrome浏览器安SwitchyOmega，改为自动切换模式后google都上不去。直接使用系统代理也上不去。
查看本机ip地址没有变化
目前怀疑是shadowsocks-qt5没有正确连接
如何验证shadowsocks-qt5是否正常连接？或者有没有人跟我遇到过一样的情况？
请求大家帮忙！

**Comment by jessyuan24** [comment]
在ubuntu里，在网络代理设置手动，chrome不用安装SwitchOmega任何插件都可以的，如果能连接上。

**Comment by jessyuan24** [comment]
要么你配置出了问题
